const achievements = [
    { id: 1, name: '初学者', desc: '第一次打开网站', icon: '🌟', category: 'general', targetPage: 'home' },
    { id: 2, name: '第一词', desc: '背诵第一个单词', icon: '📖', category: 'recite', targetPage: 'word-recite' },
    { id: 3, name: '十词达人', desc: '背诵10个单词', icon: '✨', category: 'recite', targetPage: 'word-recite' },
    { id: 4, name: '百词英雄', desc: '背诵100个单词', icon: '🏆', category: 'recite', targetPage: 'word-recite' },
    { id: 5, name: '千词王者', desc: '背诵1000个单词', icon: '👑', category: 'recite', targetPage: 'word-recite' },
    { id: 6, name: '词汇大师', desc: '背诵全部3500词', icon: '🎓', category: 'recite', targetPage: 'word-recite' },
    { id: 7, name: '搜索新手', desc: '第一次搜索单词', icon: '🔍', category: 'search', targetPage: 'word-search' },
    { id: 8, name: '搜索达人', desc: '搜索100次', icon: '🔎', category: 'search', targetPage: 'word-search' },
    { id: 9, name: '生词收藏家', desc: '添加10个生词到生词本', icon: '📓', category: 'notebook', targetPage: 'word-notebook' },
    { id: 10, name: '生词大户', desc: '添加100个生词', icon: '📚', category: 'notebook', targetPage: 'word-notebook' },
    { id: 11, name: '复习先锋', desc: '第一次复习', icon: '📝', category: 'review', targetPage: 'word-review' },
    { id: 12, name: '复习达人', desc: '复习100次', icon: '✏️', category: 'review', targetPage: 'word-review' },
    { id: 13, name: '记忆新手', desc: '完成一次记忆卡片游戏', icon: '🎴', category: 'memory', targetPage: 'memory-cards' },
    { id: 14, name: '记忆大师', desc: '完成10次记忆卡片游戏', icon: '🃏', category: 'memory', targetPage: 'memory-cards' },
    { id: 15, name: '地下城新手', desc: '第一次进入地下城', icon: '⚔️', category: 'dungeon', targetPage: 'word-dungeon' },
    { id: 16, name: '地下城勇士', desc: '到达第5层', icon: '🛡️', category: 'dungeon', targetPage: 'word-dungeon' },
    { id: 17, name: '地下城英雄', desc: '到达第10层', icon: '🗡️', category: 'dungeon', targetPage: 'word-dungeon' },
    { id: 18, name: '地下城传奇', desc: '到达第20层', icon: '🏰', category: 'dungeon', targetPage: 'word-dungeon' },
    { id: 19, name: '打字新手', desc: '完成一次打字游戏', icon: '⌨️', category: 'typing', targetPage: 'typing-game' },
    { id: 20, name: '打字能手', desc: '打字速度达到30WPM', icon: '⌨️', category: 'typing', targetPage: 'typing-game' },
    { id: 21, name: '打字达人', desc: '打字速度达到50WPM', icon: '⌨️', category: 'typing', targetPage: 'typing-game' },
    { id: 22, name: '打字大师', desc: '打字速度达到80WPM', icon: '⌨️', category: 'typing', targetPage: 'typing-game' },
    { id: 23, name: '抽卡新手', desc: '第一次抽卡', icon: '🎰', category: 'gacha', targetPage: 'gacha' },
    { id: 24, name: '抽卡达人', desc: '抽卡100次', icon: '🎲', category: 'gacha', targetPage: 'gacha' },
    { id: 25, name: '稀有收藏家', desc: '抽到一张稀有卡', icon: '💎', category: 'gacha', targetPage: 'gacha' },
    { id: 26, name: '史诗收藏家', desc: '抽到一张史诗卡', icon: '💜', category: 'gacha', targetPage: 'gacha' },
    { id: 27, name: '集卡新手', desc: '收集10张卡', icon: '📇', category: 'gacha', targetPage: 'gacha' },
    { id: 28, name: '集卡达人', desc: '收集100张卡', icon: '🗃️', category: 'gacha', targetPage: 'gacha' },
    { id: 29, name: '集卡大师', desc: '收集全部卡牌', icon: '📦', category: 'gacha', targetPage: 'gacha' },
    { id: 30, name: '成就新手', desc: '解锁10个成就', icon: '🏅', category: 'general', targetPage: 'achievements' },
    { id: 31, name: '成就达人', desc: '解锁50个成就', icon: '🎖️', category: 'general', targetPage: 'achievements' },
    { id: 32, name: '成就大师', desc: '解锁全部成就', icon: '🏆', category: 'general', targetPage: 'achievements' },
    { id: 33, name: '听力新手', desc: '听一个音频', icon: '🎧', category: 'audio', targetPage: 'audio-listening' },
    { id: 34, name: '听力达人', desc: '听50个音频', icon: '🎧', category: 'audio', targetPage: 'audio-listening' },
    { id: 35, name: '口语新手', desc: '听一个口语音频', icon: '🎤', category: 'audio', targetPage: 'audio-speaking' },
    { id: 36, name: '口语达人', desc: '听50个口语音频', icon: '🎤', category: 'audio', targetPage: 'audio-speaking' },
    { id: 37, name: '随机单词', desc: '使用随机单词10次', icon: '🎲', category: 'recite', targetPage: 'word-random' },
    { id: 38, name: '谚语学者', desc: '查看10个谚语', icon: '📜', category: 'content', targetPage: 'proverbs' },
    { id: 39, name: '短语达人', desc: '查看50个短语', icon: '📝', category: 'content', targetPage: 'phrases' },
    { id: 40, name: '每日坚持', desc: '连续学习7天', icon: '📅', category: 'general', targetPage: 'home' },
    { id: 41, name: '学习狂人', desc: '连续学习30天', icon: '🔥', category: 'general', targetPage: 'home' },
    { id: 42, name: '积分新手', desc: '获得100积分', icon: '💰', category: 'general', targetPage: 'home' },
    { id: 43, name: '积分达人', desc: '获得1000积分', icon: '💰', category: 'general', targetPage: 'home' },
    { id: 44, name: '积分富豪', desc: '获得10000积分', icon: '💎', category: 'general', targetPage: 'home' },
    { id: 45, name: 'A字母达人', desc: '背完所有A开头的单词', icon: '🅰️', category: 'alphabet', targetPage: 'word-recite' },
    { id: 46, name: 'B字母达人', desc: '背完所有B开头的单词', icon: '🅱️', category: 'alphabet', targetPage: 'word-recite' },
    { id: 47, name: 'C字母达人', desc: '背完所有C开头的单词', icon: '🅲️', category: 'alphabet', targetPage: 'word-recite' },
    { id: 48, name: 'D字母达人', desc: '背完所有D开头的单词', icon: '🅳️', category: 'alphabet', targetPage: 'word-recite' },
    { id: 49, name: 'E字母达人', desc: '背完所有E开头的单词', icon: '🅴️', category: 'alphabet', targetPage: 'word-recite' },
    { id: 50, name: 'F字母达人', desc: '背完所有F开头的单词', icon: '🅵️', category: 'alphabet', targetPage: 'word-recite' },
    { id: 51, name: 'G字母达人', desc: '背完所有G开头的单词', icon: '🅶️', category: 'alphabet', targetPage: 'word-recite' },
    { id: 52, name: 'H字母达人', desc: '背完所有H开头的单词', icon: '🅷️', category: 'alphabet', targetPage: 'word-recite' },
    { id: 53, name: 'I字母达人', desc: '背完所有I开头的单词', icon: '🅸️', category: 'alphabet', targetPage: 'word-recite' },
    { id: 54, name: 'J字母达人', desc: '背完所有J开头的单词', icon: '🅹️', category: 'alphabet', targetPage: 'word-recite' },
    { id: 55, name: 'K字母达人', desc: '背完所有K开头的单词', icon: '🅺️', category: 'alphabet', targetPage: 'word-recite' },
    { id: 56, name: 'L字母达人', desc: '背完所有L开头的单词', icon: '🅻️', category: 'alphabet', targetPage: 'word-recite' },
    { id: 57, name: 'M字母达人', desc: '背完所有M开头的单词', icon: '🅼️', category: 'alphabet', targetPage: 'word-recite' },
    { id: 58, name: 'N字母达人', desc: '背完所有N开头的单词', icon: '🅽️', category: 'alphabet', targetPage: 'word-recite' },
    { id: 59, name: 'O字母达人', desc: '背完所有O开头的单词', icon: '🅾️', category: 'alphabet', targetPage: 'word-recite' },
    { id: 60, name: 'P字母达人', desc: '背完所有P开头的单词', icon: '🅿️', category: 'alphabet', targetPage: 'word-recite' },
    { id: 61, name: 'Q字母达人', desc: '背完所有Q开头的单词', icon: '🆀️', category: 'alphabet', targetPage: 'word-recite' },
    { id: 62, name: 'R字母达人', desc: '背完所有R开头的单词', icon: '🆁️', category: 'alphabet', targetPage: 'word-recite' },
    { id: 63, name: 'S字母达人', desc: '背完所有S开头的单词', icon: '🆂️', category: 'alphabet', targetPage: 'word-recite' },
    { id: 64, name: 'T字母达人', desc: '背完所有T开头的单词', icon: '🆃️', category: 'alphabet', targetPage: 'word-recite' },
    { id: 65, name: 'U字母达人', desc: '背完所有U开头的单词', icon: '🆄️', category: 'alphabet', targetPage: 'word-recite' },
    { id: 66, name: 'V字母达人', desc: '背完所有V开头的单词', icon: '🆅️', category: 'alphabet', targetPage: 'word-recite' },
    { id: 67, name: 'W字母达人', desc: '背完所有W开头的单词', icon: '🆆️', category: 'alphabet', targetPage: 'word-recite' },
    { id: 68, name: 'X字母达人', desc: '背完所有X开头的单词', icon: '🆇️', category: 'alphabet', targetPage: 'word-recite' },
    { id: 69, name: 'Y字母达人', desc: '背完所有Y开头的单词', icon: '🆈️', category: 'alphabet', targetPage: 'word-recite' },
    { id: 70, name: 'Z字母达人', desc: '背完所有Z开头的单词', icon: '🆉️', category: 'alphabet', targetPage: 'word-recite' },
    { id: 71, name: '完美复习', desc: '一次复习全部正确', icon: '✅', category: 'review', targetPage: 'word-review' },
    { id: 72, name: '连续正确', desc: '连续答对20个单词', icon: '🔥', category: 'review', targetPage: 'word-review' },
    { id: 73, name: '快速记忆', desc: '30秒内完成记忆卡片', icon: '⚡', category: 'memory', targetPage: 'memory-cards' },
    { id: 74, name: '完美配对', desc: '记忆卡片零错误', icon: '💯', category: 'memory', targetPage: 'memory-cards' },
    { id: 75, name: '战士之路', desc: '用战士通关10层', icon: '🛡️', category: 'dungeon', targetPage: 'word-dungeon' },
    { id: 76, name: '射手之路', desc: '用射手通关10层', icon: '🏹', category: 'dungeon', targetPage: 'word-dungeon' },
    { id: 77, name: '法师之路', desc: '用法师通关10层', icon: '🔮', category: 'dungeon', targetPage: 'word-dungeon' },
    { id: 78, name: '辅助之路', desc: '用辅助通关10层', icon: '💚', category: 'dungeon', targetPage: 'word-dungeon' },
    { id: 79, name: '无伤通关', desc: '无伤通一层', icon: '💪', category: 'dungeon', targetPage: 'word-dungeon' },
    { id: 80, name: '连击大师', desc: '连续攻击10次', icon: '⚔️', category: 'dungeon', targetPage: 'word-dungeon' },
    { id: 81, name: '暴击达人', desc: '打出5次暴击', icon: '💥', category: 'dungeon', targetPage: 'word-dungeon' },
    { id: 82, name: '极限打字', desc: '极限模式得100分', icon: '🏆', category: 'typing', targetPage: 'typing-game' },
    { id: 83, name: '百字斩', desc: '一次打字游戏打100个单词', icon: '⚡', category: 'typing', targetPage: 'typing-game' },
    { id: 84, name: '零失误', desc: '一次打字游戏零错误', icon: '✨', category: 'typing', targetPage: 'typing-game' },
    { id: 85, name: '抽卡狂人', desc: '单抽100次', icon: '🎰', category: 'gacha', targetPage: 'gacha' },
    { id: 86, name: '十连达人', desc: '十连抽50次', icon: '🎲', category: 'gacha', targetPage: 'gacha' },
    { id: 87, name: '欧皇附体', desc: '十连出3张稀有', icon: '🍀', category: 'gacha', targetPage: 'gacha' },
    { id: 88, name: '传说欧皇', desc: '十连出史诗', icon: '👑', category: 'gacha', targetPage: 'gacha' },
    { id: 89, name: '深夜学习', desc: '在23点后学习', icon: '🌙', category: 'general', targetPage: 'home' },
    { id: 90, name: '早起学习', desc: '在6点前学习', icon: '🌅', category: 'general', targetPage: 'home' },
    { id: 91, name: '午休学习', desc: '在12-14点学习', icon: '☀️', category: 'general', targetPage: 'home' },
    { id: 92, name: '学习马拉松', desc: '连续学习1小时', icon: '🏃', category: 'general', targetPage: 'home' },
    { id: 93, name: '单词收藏家', desc: '查看所有单词', icon: '📚', category: 'search', targetPage: 'word-search' },
    { id: 94, name: '例句达人', desc: '查看100个例句', icon: '📝', category: 'search', targetPage: 'word-search' },
    { id: 95, name: '发音达人', desc: '播放100次发音', icon: '🔊', category: 'audio', targetPage: 'word-recite' },
    { id: 96, name: '分享达人', desc: '分享10次', icon: '📤', category: 'general', targetPage: 'home' },
    { id: 97, name: '反馈达人', desc: '提交5次反馈', icon: '📋', category: 'general', targetPage: 'home' },
    { id: 98, name: '测试达人', desc: '完成10次测试', icon: '📝', category: 'review', targetPage: 'word-review' },
    { id: 99, name: '满分达人', desc: '测试得满分', icon: '💯', category: 'review', targetPage: 'word-review' },
    { id: 100, name: '终极学习者', desc: '解锁所有其他成就', icon: '🏆', category: 'general', targetPage: 'achievements' },
    { id: 101, name: '初次胜利', desc: '击败第一个敌人', icon: '⚔️', category: 'dungeon', targetPage: 'word-dungeon' },
    { id: 102, name: '初露锋芒', desc: '累计击杀10个敌人', icon: '🗡️', category: 'dungeon', targetPage: 'word-dungeon' },
    { id: 103, name: '杀戮机器', desc: '累计击杀50个敌人', icon: '💀', category: 'dungeon', targetPage: 'word-dungeon' },
    { id: 104, name: '死神降临', desc: '累计击杀100个敌人', icon: '☠️', category: 'dungeon', targetPage: 'word-dungeon' },
    { id: 105, name: '战场主宰', desc: '累计击杀200个敌人', icon: '🔥', category: 'dungeon', targetPage: 'word-dungeon' },
    { id: 106, name: '传奇杀手', desc: '累计击杀500个敌人', icon: '💀', category: 'dungeon', targetPage: 'word-dungeon' },
    { id: 107, name: '勇者之路', desc: '到达第15层', icon: '🗻', category: 'dungeon', targetPage: 'word-dungeon' },
    { id: 108, name: '深渊探险家', desc: '到达第25层', icon: '🌋', category: 'dungeon', targetPage: 'word-dungeon' },
    { id: 109, name: '地下城之王', desc: '到达第30层', icon: '🏰', category: 'dungeon', targetPage: 'word-dungeon' },
    { id: 110, name: '通关成功', desc: '完成一次完整的游戏', icon: '🏆', category: 'dungeon', targetPage: 'word-dungeon' },
    { id: 111, name: '常胜将军', desc: '通关5次', icon: '🎖️', category: 'dungeon', targetPage: 'word-dungeon' },
    { id: 112, name: '永恒冠军', desc: '通关25次', icon: '👑', category: 'dungeon', targetPage: 'word-dungeon' },
    { id: 113, name: '全职业大师', desc: '使用所有职业各通关一次', icon: '👑', category: 'dungeon', targetPage: 'word-dungeon' },
    { id: 114, name: '财富积累', desc: '累计获得500金币', icon: '💰', category: 'dungeon', targetPage: 'word-dungeon' },
    { id: 115, name: '小有积蓄', desc: '累计获得1000金币', icon: '💰', category: 'dungeon', targetPage: 'word-dungeon' },
    { id: 116, name: '富可敌国', desc: '累计获得2000金币', icon: '🪙', category: 'dungeon', targetPage: 'word-dungeon' },
    { id: 117, name: '黄金大亨', desc: '累计获得5000金币', icon: '💎', category: 'dungeon', targetPage: 'word-dungeon' },
    { id: 118, name: '财富之神', desc: '累计获得10000金币', icon: '🏆', category: 'dungeon', targetPage: 'word-dungeon' },
    { id: 119, name: '卡牌大师', desc: '累计打出100张卡牌', icon: '🃏', category: 'dungeon', targetPage: 'word-dungeon' },
    { id: 120, name: '卡牌宗师', desc: '累计打出500张卡牌', icon: '🎴', category: 'dungeon', targetPage: 'word-dungeon' },
    { id: 121, name: '卡牌传奇', desc: '累计打出1000张卡牌', icon: '🃏', category: 'dungeon', targetPage: 'word-dungeon' },
    { id: 122, name: '卡牌之神', desc: '累计打出2500张卡牌', icon: '🎴', category: 'dungeon', targetPage: 'word-dungeon' },
    { id: 123, name: '伤害输出', desc: '累计造成1000点伤害', icon: '💥', category: 'dungeon', targetPage: 'word-dungeon' },
    { id: 124, name: '毁灭者', desc: '累计造成5000点伤害', icon: '💣', category: 'dungeon', targetPage: 'word-dungeon' },
    { id: 125, name: '破坏之王', desc: '累计造成10000点伤害', icon: '💥', category: 'dungeon', targetPage: 'word-dungeon' },
    { id: 126, name: '毁灭天使', desc: '累计造成25000点伤害', icon: '🔥', category: 'dungeon', targetPage: 'word-dungeon' },
    { id: 127, name: '末日审判', desc: '累计造成50000点伤害', icon: '☄️', category: 'dungeon', targetPage: 'word-dungeon' },
    { id: 128, name: '完美通关', desc: '不受到任何伤害通过一层', icon: '🛡️', category: 'dungeon', targetPage: 'word-dungeon' },
    { id: 129, name: '无伤达人', desc: '累计5层无伤通关', icon: '🛡️', category: 'dungeon', targetPage: 'word-dungeon' },
    { id: 130, name: '完美战士', desc: '累计10层无伤通关', icon: '✨', category: 'dungeon', targetPage: 'word-dungeon' },
    { id: 131, name: '闪电速度', desc: '5分钟内通关', icon: '⚡', category: 'dungeon', targetPage: 'word-dungeon' },
    { id: 132, name: '极速恶魔', desc: '3分钟内通关', icon: '⚡', category: 'dungeon', targetPage: 'word-dungeon' },
    { id: 133, name: '闪电突袭', desc: '2分钟内通关', icon: '🌩️', category: 'dungeon', targetPage: 'word-dungeon' },
    { id: 134, name: 'Boss杀手', desc: '击败10个Boss', icon: '👑', category: 'dungeon', targetPage: 'word-dungeon' },
    { id: 135, name: 'Boss终结者', desc: '击败25个Boss', icon: '👑', category: 'dungeon', targetPage: 'word-dungeon' },
    { id: 136, name: 'Boss噩梦', desc: '击败50个Boss', icon: '💀', category: 'dungeon', targetPage: 'word-dungeon' },
    { id: 137, name: '精英猎人', desc: '击败25个精英敌人', icon: '⭐', category: 'dungeon', targetPage: 'word-dungeon' },
    { id: 138, name: '精英克星', desc: '击败50个精英敌人', icon: '⭐', category: 'dungeon', targetPage: 'word-dungeon' },
    { id: 139, name: '精英终结者', desc: '击败100个精英敌人', icon: '🌟', category: 'dungeon', targetPage: 'word-dungeon' },
    { id: 140, name: '常客', desc: '访问商店50次', icon: '🏪', category: 'dungeon', targetPage: 'word-dungeon' },
    { id: 141, name: 'VIP客户', desc: '访问商店100次', icon: '🛒', category: 'dungeon', targetPage: 'word-dungeon' },
    { id: 142, name: '挥金如土', desc: '累计花费2000金币', icon: '💸', category: 'dungeon', targetPage: 'word-dungeon' },
    { id: 143, name: '购物狂', desc: '累计花费5000金币', icon: '💳', category: 'dungeon', targetPage: 'word-dungeon' },
    { id: 144, name: '卡牌收藏家', desc: '收集50张不同的卡牌', icon: '📦', category: 'dungeon', targetPage: 'word-dungeon' },
    { id: 145, name: '幸运儿', desc: '连续3次答题正确', icon: '🍀', category: 'dungeon', targetPage: 'word-dungeon' },
    { id: 146, name: '答题大师', desc: '连续5次答题正确', icon: '🎯', category: 'dungeon', targetPage: 'word-dungeon' },
    { id: 147, name: '词汇专家', desc: '累计答对100题', icon: '📖', category: 'dungeon', targetPage: 'word-dungeon' },
    { id: 148, name: '词汇圣人', desc: '累计答对500题', icon: '🎓', category: 'dungeon', targetPage: 'word-dungeon' },
    { id: 149, name: '幸存者', desc: '以低于10%血量击败敌人', icon: '❤️', category: 'dungeon', targetPage: 'word-dungeon' },
    { id: 150, name: '逆转之王', desc: '以低于5%血量击败Boss', icon: '💪', category: 'dungeon', targetPage: 'word-dungeon' },
    { id: 151, name: '不可触碰', desc: '单局游戏无伤通关', icon: '👼', category: 'dungeon', targetPage: 'word-dungeon' },
    { id: 152, name: '战士大师', desc: '使用战士通关5次', icon: '🛡️', category: 'dungeon', targetPage: 'word-dungeon' },
    { id: 153, name: '法师大师', desc: '使用法师通关5次', icon: '🔮', category: 'dungeon', targetPage: 'word-dungeon' },
    { id: 154, name: '刺客大师', desc: '使用刺客通关5次', icon: '🗡️', category: 'dungeon', targetPage: 'word-dungeon' },
    { id: 155, name: '射手大师', desc: '使用射手通关5次', icon: '🏹', category: 'dungeon', targetPage: 'word-dungeon' },
    { id: 156, name: '辅助大师', desc: '使用辅助通关5次', icon: '💚', category: 'dungeon', targetPage: 'word-dungeon' },
    { id: 157, name: '死灵法师大师', desc: '使用死灵法师通关5次', icon: '💀', category: 'dungeon', targetPage: 'word-dungeon' },
    { id: 158, name: '元素师大师', desc: '使用元素师通关5次', icon: '🌊', category: 'dungeon', targetPage: 'word-dungeon' },
    { id: 159, name: '狂战士大师', desc: '使用狂战士通关5次', icon: '🔥', category: 'dungeon', targetPage: 'word-dungeon' },
    { id: 160, name: '武僧大师', desc: '使用武僧通关5次', icon: '👊', category: 'dungeon', targetPage: 'word-dungeon' },
    { id: 161, name: '召唤师大师', desc: '使用召唤师通关5次', icon: '🐉', category: 'dungeon', targetPage: 'word-dungeon' },
    { id: 162, name: '时空法师大师', desc: '使用时空法师通关5次', icon: '⏰', category: 'dungeon', targetPage: 'word-dungeon' },
    { id: 163, name: '德鲁伊大师', desc: '使用德鲁伊通关5次', icon: '🌿', category: 'dungeon', targetPage: 'word-dungeon' },
    { id: 164, name: '符文骑士大师', desc: '使用符文骑士通关5次', icon: '⚔️', category: 'dungeon', targetPage: 'word-dungeon' },
    { id: 165, name: '炼金术士大师', desc: '使用炼金术士通关5次', icon: '⚗️', category: 'dungeon', targetPage: 'word-dungeon' },
    { id: 166, name: '圣骑士大师', desc: '使用圣骑士通关5次', icon: '✝️', category: 'dungeon', targetPage: 'word-dungeon' },
    { id: 167, name: '忠实玩家', desc: '游戏总时长达到1小时', icon: '⏱️', category: 'dungeon', targetPage: 'word-dungeon' },
    { id: 168, name: '硬核玩家', desc: '游戏总时长达到5小时', icon: '🎮', category: 'dungeon', targetPage: 'word-dungeon' },
    { id: 169, name: '传奇玩家', desc: '游戏总时长达到10小时', icon: '🌟', category: 'dungeon', targetPage: 'word-dungeon' },
    { id: 170, name: '卡组构建者', desc: '创建5个自定义卡组', icon: '📝', category: 'dungeon', targetPage: 'word-dungeon' },
    { id: 171, name: '卡组大师', desc: '创建10个自定义卡组', icon: '🏆', category: 'dungeon', targetPage: 'word-dungeon' },
    { id: 172, name: '存档达人', desc: '创建10个存档', icon: '💾', category: 'dungeon', targetPage: 'word-dungeon' },
    { id: 173, name: '存档收藏家', desc: '创建50个存档', icon: '💿', category: 'dungeon', targetPage: 'word-dungeon' },
    { id: 174, name: '事件探索者', desc: '触发20个特殊事件', icon: '🎪', category: 'dungeon', targetPage: 'word-dungeon' },
    { id: 175, name: '事件大师', desc: '触发50个特殊事件', icon: '🎭', category: 'dungeon', targetPage: 'word-dungeon' },
    { id: 176, name: '暴击大师', desc: '累计造成100次暴击', icon: '💥', category: 'dungeon', targetPage: 'word-dungeon' },
    { id: 177, name: '暴击传说', desc: '累计造成500次暴击', icon: '⚡', category: 'dungeon', targetPage: 'word-dungeon' },
    { id: 178, name: '闪避大师', desc: '累计闪避50次攻击', icon: '💨', category: 'dungeon', targetPage: 'word-dungeon' },
    { id: 179, name: '钢铁意志', desc: '在血量低于20%时击败10个敌人', icon: '🦾', category: 'dungeon', targetPage: 'word-dungeon' },
    { id: 180, name: '首杀', desc: '在第一层击败第一个敌人', icon: '🩸', category: 'dungeon', targetPage: 'word-dungeon' },
    { id: 181, name: '楼层清理者', desc: '单层击败5个敌人', icon: '🧹', category: 'dungeon', targetPage: 'word-dungeon' },
    { id: 182, name: '房间探索者', desc: '进入100个房间', icon: '🚪', category: 'dungeon', targetPage: 'word-dungeon' },
    { id: 183, name: '房间大师', desc: '进入500个房间', icon: '🏠', category: 'dungeon', targetPage: 'word-dungeon' },
    { id: 184, name: '宝藏猎人', desc: '打开50个宝箱', icon: '📦', category: 'dungeon', targetPage: 'word-dungeon' },
    { id: 185, name: '宝藏大师', desc: '打开100个宝箱', icon: '🎁', category: 'dungeon', targetPage: 'word-dungeon' },
    { id: 186, name: '药剂使用者', desc: '使用25瓶药水', icon: '🧪', category: 'dungeon', targetPage: 'word-dungeon' },
    { id: 187, name: '药剂大师', desc: '使用100瓶药水', icon: '⚗️', category: 'dungeon', targetPage: 'word-dungeon' },
    { id: 188, name: '卡牌强化者', desc: '强化25张卡牌', icon: '⬆️', category: 'dungeon', targetPage: 'word-dungeon' },
    { id: 189, name: '卡牌增幅师', desc: '强化100张卡牌', icon: '📈', category: 'dungeon', targetPage: 'word-dungeon' },
    { id: 190, name: '谚语大师', desc: '查看100个谚语', icon: '📜', category: 'content', targetPage: 'proverbs' },
    { id: 191, name: '谚语专家', desc: '查看500个谚语', icon: '📜', category: 'content', targetPage: 'proverbs' },
    { id: 192, name: '谚语学者', desc: '查看全部700个谚语', icon: '🎓', category: 'content', targetPage: 'proverbs' },
    { id: 193, name: '短语专家', desc: '查看200个短语', icon: '📝', category: 'content', targetPage: 'phrases' },
    { id: 194, name: '短语大师', desc: '查看500个短语', icon: '📚', category: 'content', targetPage: 'phrases' },
    { id: 195, name: '生词本达人', desc: '添加500个生词', icon: '📓', category: 'notebook', targetPage: 'word-notebook' },
    { id: 196, name: '生词本大师', desc: '添加1000个生词', icon: '📚', category: 'notebook', targetPage: 'word-notebook' },
    { id: 197, name: '复习专家', desc: '复习500次', icon: '📝', category: 'review', targetPage: 'word-review' },
    { id: 198, name: '复习大师', desc: '复习1000次', icon: '✏️', category: 'review', targetPage: 'word-review' },
    { id: 199, name: '记忆专家', desc: '完成50次记忆卡片游戏', icon: '🎴', category: 'memory', targetPage: 'memory-cards' },
    { id: 200, name: '记忆传奇', desc: '完成100次记忆卡片游戏', icon: '🃏', category: 'memory', targetPage: 'memory-cards' },
    { id: 201, name: '搜索专家', desc: '搜索500次', icon: '🔍', category: 'search', targetPage: 'word-search' },
    { id: 202, name: '搜索大师', desc: '搜索1000次', icon: '🔎', category: 'search', targetPage: 'word-search' },
    { id: 203, name: '听力专家', desc: '听200个音频', icon: '🎧', category: 'audio', targetPage: 'audio-listening' },
    { id: 204, name: '听力大师', desc: '听500个音频', icon: '🎧', category: 'audio', targetPage: 'audio-listening' },
    { id: 205, name: '口语专家', desc: '听200个口语音频', icon: '🎤', category: 'audio', targetPage: 'audio-speaking' },
    { id: 206, name: '口语大师', desc: '听500个口语音频', icon: '🎤', category: 'audio', targetPage: 'audio-speaking' },
    { id: 207, name: '打字专家', desc: '打字速度达到100WPM', icon: '⌨️', category: 'typing', targetPage: 'typing-game' },
    { id: 208, name: '打字传奇', desc: '打字速度达到120WPM', icon: '⌨️', category: 'typing', targetPage: 'typing-game' },
    { id: 209, name: '抽卡专家', desc: '抽卡500次', icon: '🎰', category: 'gacha', targetPage: 'gacha' },
    { id: 210, name: '抽卡大师', desc: '抽卡1000次', icon: '🎲', category: 'gacha', targetPage: 'gacha' },
    { id: 211, name: '传说收藏家', desc: '抽到一张传说卡', icon: '🌟', category: 'gacha', targetPage: 'gacha' },
    { id: 212, name: '集卡专家', desc: '收集200张卡', icon: '📇', category: 'gacha', targetPage: 'gacha' },
    { id: 213, name: '连续学习14天', desc: '连续学习14天', icon: '📅', category: 'general', targetPage: 'home' },
    { id: 214, name: '连续学习60天', desc: '连续学习60天', icon: '🔥', category: 'general', targetPage: 'home' },
    { id: 215, name: '连续学习100天', desc: '连续学习100天', icon: '🏆', category: 'general', targetPage: 'home' },
    { id: 216, name: '积分王者', desc: '获得50000积分', icon: '💎', category: 'general', targetPage: 'home' },
    { id: 217, name: '积分大帝', desc: '获得100000积分', icon: '👑', category: 'general', targetPage: 'home' },
    { id: 218, name: '学习达人', desc: '连续学习2小时', icon: '🏃', category: 'general', targetPage: 'home' },
    { id: 219, name: '学习狂魔', desc: '连续学习3小时', icon: '🔥', category: 'general', targetPage: 'home' },
    { id: 220, name: '夜猫子', desc: '在凌晨0-2点学习', icon: '🦉', category: 'general', targetPage: 'home' },
    { id: 221, name: '晨鸟', desc: '在5-7点学习', icon: '🐦', category: 'general', targetPage: 'home' },
    { id: 222, name: '周末战士', desc: '在周末学习', icon: '📅', category: 'general', targetPage: 'home' },
    { id: 223, name: '节日学习', desc: '在节假日学习', icon: '🎉', category: 'general', targetPage: 'home' },
    { id: 224, name: '全能学习者', desc: '使用所有功能至少一次', icon: '🌟', category: 'general', targetPage: 'home' },
    { id: 225, name: '完美主义者', desc: '所有测试都得满分', icon: '💯', category: 'review', targetPage: 'word-review' },
    { id: 226, name: '单词新手', desc: '学习10个单词', icon: '📚', category: 'recite', targetPage: 'word-recite' },
    { id: 227, name: '单词达人', desc: '学习50个单词', icon: '📖', category: 'recite', targetPage: 'word-recite' },
    { id: 228, name: '单词专家', desc: '学习200个单词', icon: '✨', category: 'recite', targetPage: 'word-recite' },
    { id: 229, name: '单词大师', desc: '学习500个单词', icon: '🏆', category: 'recite', targetPage: 'word-recite' },
    { id: 230, name: '单词传奇', desc: '学习1000个单词', icon: '👑', category: 'recite', targetPage: 'word-recite' },
    { id: 231, name: '单词王者', desc: '学习2000个单词', icon: '💎', category: 'recite', targetPage: 'word-recite' },
    { id: 232, name: '词汇巨人', desc: '学习3000个单词', icon: '🌟', category: 'recite', targetPage: 'word-recite' },
    { id: 233, name: '词汇之神', desc: '学习全部3500个单词', icon: '🎓', category: 'recite', targetPage: 'word-recite' },
    { id: 234, name: '每日单词', desc: '每天学习10个单词', icon: '📅', category: 'recite', targetPage: 'word-recite' },
    { id: 235, name: '单词狂人', desc: '每天学习50个单词', icon: '🔥', category: 'recite', targetPage: 'word-recite' },
    { id: 236, name: '单词马拉松', desc: '每天学习100个单词', icon: '🏃', category: 'recite', targetPage: 'word-recite' },
    { id: 237, name: '单词收藏家', desc: '收藏50个单词', icon: '⭐', category: 'recite', targetPage: 'word-recite' },
    { id: 238, name: '单词收藏大师', desc: '收藏200个单词', icon: '🌟', category: 'recite', targetPage: 'word-recite' },
    { id: 239, name: '发音学习者', desc: '播放50次发音', icon: '🔊', category: 'recite', targetPage: 'word-recite' },
    { id: 240, name: '发音达人', desc: '播放200次发音', icon: '🎧', category: 'recite', targetPage: 'word-recite' },
    { id: 241, name: '发音专家', desc: '播放500次发音', icon: '🎤', category: 'recite', targetPage: 'word-recite' },
    { id: 242, name: '例句学习者', desc: '查看50个例句', icon: '📝', category: 'recite', targetPage: 'word-recite' },
    { id: 243, name: '例句达人', desc: '查看200个例句', icon: '📋', category: 'recite', targetPage: 'word-recite' },
    { id: 244, name: '例句专家', desc: '查看500个例句', icon: '📚', category: 'recite', targetPage: 'word-recite' },
    { id: 245, name: '词根学习者', desc: '学习10个词根', icon: '🌱', category: 'recite', targetPage: 'word-recite' },
    { id: 246, name: '词根达人', desc: '学习50个词根', icon: '🌿', category: 'recite', targetPage: 'word-recite' },
    { id: 247, name: '词缀学习者', desc: '学习10个词缀', icon: '🔗', category: 'recite', targetPage: 'word-recite' },
    { id: 248, name: '词缀达人', desc: '学习50个词缀', icon: '📎', category: 'recite', targetPage: 'word-recite' },
    { id: 249, name: '同义词学习者', desc: '学习50组同义词', icon: '🔄', category: 'recite', targetPage: 'word-recite' },
    { id: 250, name: '反义词学习者', desc: '学习50组反义词', icon: '↔️', category: 'recite', targetPage: 'word-recite' },
    { id: 251, name: '单词记忆王', desc: '连续7天学习单词', icon: '📅', category: 'recite', targetPage: 'word-recite' },
    { id: 252, name: '单词坚持者', desc: '连续30天学习单词', icon: '🔥', category: 'recite', targetPage: 'word-recite' },
    { id: 253, name: '单词狂热者', desc: '连续100天学习单词', icon: '🏆', category: 'recite', targetPage: 'word-recite' },
    { id: 254, name: '单词速记', desc: '1分钟内记住10个单词', icon: '⚡', category: 'recite', targetPage: 'word-recite' },
    { id: 255, name: '单词闪电', desc: '1分钟内记住20个单词', icon: '🌩️', category: 'recite', targetPage: 'word-recite' },
    { id: 256, name: '单词精准', desc: '连续答对50个单词', icon: '🎯', category: 'recite', targetPage: 'word-recite' },
    { id: 257, name: '单词完美', desc: '连续答对100个单词', icon: '💯', category: 'recite', targetPage: 'word-recite' },
    { id: 258, name: '复习新手', desc: '复习10个单词', icon: '📝', category: 'review', targetPage: 'word-review' },
    { id: 259, name: '复习达人', desc: '复习50个单词', icon: '✏️', category: 'review', targetPage: 'word-review' },
    { id: 260, name: '复习专家', desc: '复习200个单词', icon: '📋', category: 'review', targetPage: 'word-review' },
    { id: 261, name: '复习大师', desc: '复习500个单词', icon: '📚', category: 'review', targetPage: 'word-review' },
    { id: 262, name: '复习传奇', desc: '复习1000个单词', icon: '🏆', category: 'review', targetPage: 'word-review' },
    { id: 263, name: '复习王者', desc: '复习2000个单词', icon: '👑', category: 'review', targetPage: 'word-review' },
    { id: 264, name: '复习完美', desc: '一次复习全部正确', icon: '✅', category: 'review', targetPage: 'word-review' },
    { id: 265, name: '复习精准', desc: '连续10次复习全部正确', icon: '🎯', category: 'review', targetPage: 'word-review' },
    { id: 266, name: '复习之神', desc: '连续50次复习全部正确', icon: '💯', category: 'review', targetPage: 'word-review' },
    { id: 267, name: '单词本新手', desc: '添加10个单词到生词本', icon: '📓', category: 'notebook', targetPage: 'word-notebook' },
    { id: 268, name: '单词本达人', desc: '添加50个单词到生词本', icon: '📚', category: 'notebook', targetPage: 'word-notebook' },
    { id: 269, name: '单词本专家', desc: '添加200个单词到生词本', icon: '📖', category: 'notebook', targetPage: 'word-notebook' },
    { id: 270, name: '单词本大师', desc: '添加500个单词到生词本', icon: '🏆', category: 'notebook', targetPage: 'word-notebook' },
    { id: 271, name: '单词本传奇', desc: '添加1000个单词到生词本', icon: '👑', category: 'notebook', targetPage: 'word-notebook' },
    { id: 272, name: '单词本清空', desc: '清空生词本中的所有单词', icon: '🗑️', category: 'notebook', targetPage: 'word-notebook' },
    { id: 273, name: '搜索新手', desc: '搜索单词10次', icon: '🔍', category: 'search', targetPage: 'word-search' },
    { id: 274, name: '搜索达人', desc: '搜索单词50次', icon: '🔎', category: 'search', targetPage: 'word-search' },
    { id: 275, name: '搜索专家', desc: '搜索单词200次', icon: '🔍', category: 'search', targetPage: 'word-search' },
    { id: 276, name: '搜索大师', desc: '搜索单词500次', icon: '🔎', category: 'search', targetPage: 'word-search' },
    { id: 277, name: '搜索传奇', desc: '搜索单词1000次', icon: '🔍', category: 'search', targetPage: 'word-search' },
    { id: 278, name: '搜索王者', desc: '搜索单词2000次', icon: '🔎', category: 'search', targetPage: 'word-search' },
    { id: 279, name: '随机单词新手', desc: '使用随机单词功能10次', icon: '🎲', category: 'recite', targetPage: 'word-random' },
    { id: 280, name: '随机单词达人', desc: '使用随机单词功能50次', icon: '🎲', category: 'recite', targetPage: 'word-random' },
    { id: 281, name: '随机单词专家', desc: '使用随机单词功能100次', icon: '🎲', category: 'recite', targetPage: 'word-random' },
    { id: 282, name: '随机单词大师', desc: '使用随机单词功能500次', icon: '🎲', category: 'recite', targetPage: 'word-random' },
    { id: 283, name: '单词测试新手', desc: '完成10次单词测试', icon: '📝', category: 'review', targetPage: 'word-review' },
    { id: 284, name: '单词测试达人', desc: '完成50次单词测试', icon: '✏️', category: 'review', targetPage: 'word-review' },
    { id: 285, name: '单词测试专家', desc: '完成100次单词测试', icon: '📋', category: 'review', targetPage: 'word-review' },
    { id: 286, name: '单词测试大师', desc: '完成200次单词测试', icon: '📚', category: 'review', targetPage: 'word-review' },
    { id: 287, name: '单词测试满分', desc: '获得一次测试满分', icon: '💯', category: 'review', targetPage: 'word-review' },
    { id: 288, name: '单词测试满分达人', desc: '获得10次测试满分', icon: '🏆', category: 'review', targetPage: 'word-review' },
    { id: 289, name: '单词测试满分专家', desc: '获得50次测试满分', icon: '👑', category: 'review', targetPage: 'word-review' },
    { id: 290, name: '单词测试满分大师', desc: '获得100次测试满分', icon: '💎', category: 'review', targetPage: 'word-review' },
    { id: 291, name: '视频彩蛋发现者', desc: '发现隐藏的视频彩蛋', icon: '🎬', category: 'easter', targetPage: 'home' },
    { id: 292, name: '罗小黑彩蛋发现者', desc: '发现隐藏的罗小黑彩蛋', icon: '🐱', category: 'easter', targetPage: 'home' },
    { id: 293, name: '彩蛋猎人', desc: '发现所有彩蛋', icon: '🥚', category: 'easter', targetPage: 'home' },
    { id: 294, name: '神秘探索者', desc: '点击logo 10次触发彩蛋', icon: '🔍', category: 'easter', targetPage: 'home' },
    { id: 295, name: '彩蛋大师', desc: '观看视频彩蛋5次', icon: '🎥', category: 'easter', targetPage: 'home' },
    { id: 296, name: '罗小黑粉丝', desc: '查看罗小黑彩蛋10次', icon: '🖤', category: 'easter', targetPage: 'home' },
    { id: 297, name: '隐藏功能发现者', desc: '发现网站的隐藏功能', icon: '🔮', category: 'easter', targetPage: 'home' }
];

const achievementCategories = [
    { id: 'all', name: '全部', icon: '🏆' },
    { id: 'general', name: '综合', icon: '🌟' },
    { id: 'recite', name: '背诵', icon: '📖' },
    { id: 'review', name: '复习', icon: '📝' },
    { id: 'search', name: '搜索', icon: '🔍' },
    { id: 'notebook', name: '生词本', icon: '📓' },
    { id: 'memory', name: '记忆卡牌', icon: '🎴' },
    { id: 'dungeon', name: '地下城', icon: '⚔️' },
    { id: 'typing', name: '打字游戏', icon: '⌨️' },
    { id: 'gacha', name: '抽卡集卡', icon: '🎰' },
    { id: 'audio', name: '听力口语', icon: '🎧' },
    { id: 'content', name: '谚语短语', icon: '📜' },
    { id: 'alphabet', name: '字母达人', icon: '🔤' },
    { id: 'easter', name: '彩蛋', icon: '🥚' }
];

const proverbs = [
    { en: 'Practice makes perfect.', zh: '熟能生巧。' },
    { en: 'Where there is a will, there is a way.', zh: '有志者事竟成。' },
    { en: 'No pain, no gain.', zh: '一分耕耘，一分收获。' },
    { en: 'The early bird catches the worm.', zh: '早起的鸟儿有虫吃。' },
    { en: 'Actions speak louder than words.', zh: '事实胜于雄辩。' },
    { en: 'A friend in need is a friend indeed.', zh: '患难见真情。' },
    { en: 'All roads lead to Rome.', zh: '条条大路通罗马。' },
    { en: 'Well begun is half done.', zh: '好的开始是成功的一半。' },
    { en: 'Knowledge is power.', zh: '知识就是力量。' },
    { en: 'Time is money.', zh: '时间就是金钱。' },
    { en: 'Every coin has two sides.', zh: '凡事都有两面性。' },
    { en: 'God helps those who help themselves.', zh: '自助者天助之。' },
    { en: 'Rome was not built in a day.', zh: '冰冻三尺非一日之寒。' },
    { en: 'Practice what you preach.', zh: '言行一致。' },
    { en: 'The pen is mightier than the sword.', zh: '笔诛胜于剑伐。' },
    { en: 'When in Rome, do as the Romans do.', zh: '入乡随俗。' },
    { en: 'Fortune favors the bold.', zh: '勇者得胜。' },
    { en: 'All that glitters is not gold.', zh: '发光的未必都是金子。' },
    { en: 'Better late than never.', zh: '迟做总比不做好。' },
    { en: 'Honesty is the best policy.', zh: '诚实为上策。' },
    { en: 'Look before you leap.', zh: '三思而后行。' },
    { en: 'A journey of a thousand miles begins with a single step.', zh: '千里之行，始于足下。' },
    { en: 'Failure is the mother of success.', zh: '失败是成功之母。' },
    { en: 'Health is wealth.', zh: '健康就是财富。' },
    { en: 'Two heads are better than one.', zh: '三个臭皮匠，顶个诸葛亮。' },
    { en: 'A stitch in time saves nine.', zh: '小洞不补，大洞吃苦。' },
    { en: 'Birds of a feather flock together.', zh: '物以类聚，人以群分。' },
    { en: 'Blood is thicker than water.', zh: '血浓于水。' },
    { en: 'Dont count your chickens before they hatch.', zh: '不要过早乐观。' },
    { en: 'Dont put all your eggs in one basket.', zh: '不要孤注一掷。' },
    { en: 'Easy come, easy go.', zh: '来得容易去得快。' },
    { en: 'Every dog has its day.', zh: '人人都有得意时。' },
    { en: 'First come, first served.', zh: '先到先得。' },
    { en: 'Great minds think alike.', zh: '英雄所见略同。' },
    { en: 'Haste makes waste.', zh: '欲速则不达。' },
    { en: 'History repeats itself.', zh: '历史总是惊人的相似。' },
    { en: 'Home is where the heart is.', zh: '心在哪里，家就在哪里。' },
    { en: 'If you want a thing done well, do it yourself.', zh: '求人不如求己。' },
    { en: 'It never rains but it pours.', zh: '祸不单行。' },
    { en: 'Kill two birds with one stone.', zh: '一石二鸟。' },
    { en: 'Let sleeping dogs lie.', zh: '不要自找麻烦。' },
    { en: 'Life is not a bed of roses.', zh: '生活并非一帆风顺。' },
    { en: 'Like father, like son.', zh: '有其父必有其子。' },
    { en: 'Many hands make light work.', zh: '众人拾柴火焰高。' },
    { en: 'Money doesnt grow on trees.', zh: '钱来之不易。' },
    { en: 'Necessity is the mother of invention.', zh: '需要是发明之母。' },
    { en: 'Never judge a book by its cover.', zh: '不要以貌取人。' },
    { en: 'No man is an island.', zh: '没有人是一座孤岛。' },
    { en: 'Nothing ventured, nothing gained.', zh: '不入虎穴，焉得虎子。' },
    { en: 'One mans trash is another mans treasure.', zh: '甲之蜜糖，乙之砒霜。' },
    { en: 'Out of sight, out of mind.', zh: '眼不见，心不烦。' },
    { en: 'Patience is a virtue.', zh: '耐心是一种美德。' },
    { en: 'Prevention is better than cure.', zh: '预防胜于治疗。' },
    { en: 'Silence is golden.', zh: '沉默是金。' },
    { en: 'The apple doesnt fall far from the tree.', zh: '有其父必有其子。' },
    { en: 'The grass is always greener on the other side.', zh: '这山望着那山高。' },
    { en: 'The proof of the pudding is in the eating.', zh: '实践出真知。' },
    { en: 'There is no smoke without fire.', zh: '无风不起浪。' },
    { en: 'Time heals all wounds.', zh: '时间能治愈一切创伤。' },
    { en: 'Too many cooks spoil the broth.', zh: '人多手杂。' },
    { en: 'Two wrongs dont make a right.', zh: '以牙还牙不能解决问题。' },
    { en: 'Unity is strength.', zh: '团结就是力量。' },
    { en: 'What goes around comes around.', zh: '善有善报，恶有恶报。' },
    { en: 'When the going gets tough, the tough get going.', zh: '艰难困苦，玉汝于成。' },
    { en: 'Where theres smoke, theres fire.', zh: '无风不起浪。' },
    { en: 'You cant have your cake and eat it too.', zh: '鱼与熊掌不可兼得。' },
    { en: 'You cant judge a book by its cover.', zh: '人不可貌相。' },
    { en: 'A picture is worth a thousand words.', zh: '一图胜千言。' },
    { en: 'Beauty is in the eye of the beholder.', zh: '情人眼里出西施。' },
    { en: 'Better safe than sorry.', zh: '小心驶得万年船。' },
    { en: 'Dont bite off more than you can chew.', zh: '贪多嚼不烂。' },
    { en: 'Dont bite the hand that feeds you.', zh: '不要恩将仇报。' },
    { en: 'Dont judge a man until youve walked a mile in his shoes.', zh: '设身处地，换位思考。' },
    { en: 'Every cloud has a silver lining.', zh: '黑暗中总有一线光明。' },
    { en: 'Give credit where credit is due.', zh: '该表扬时就表扬。' },
    { en: 'Good things come to those who wait.', zh: '好事多磨。' },
    { en: 'Hope for the best, prepare for the worst.', zh: '抱最好的希望，做最坏的打算。' },
    { en: 'If it aint broke, dont fix it.', zh: '不要没事找事。' },
    { en: 'It takes two to tango.', zh: '一个巴掌拍不响。' },
    { en: 'Keep your friends close and your enemies closer.', zh: '知己知彼，百战不殆。' },
    { en: 'Laughter is the best medicine.', zh: '笑一笑，十年少。' },
    { en: 'Learn from yesterday, live for today, hope for tomorrow.', zh: '总结昨天，活在当下，展望明天。' },
    { en: 'Money talks.', zh: '有钱能使鬼推磨。' },
    { en: 'Old habits die hard.', zh: '江山易改，本性难移。' },
    { en: 'One good turn deserves another.', zh: '善有善报。' },
    { en: 'Practice what you preach.', zh: '身体力行。' },
    { en: 'Slow and steady wins the race.', zh: '稳扎稳打，无往不胜。' },
    { en: 'The early bird catches the worm.', zh: '早起的鸟儿有虫吃。' },
    { en: 'The squeaky wheel gets the grease.', zh: '会哭的孩子有奶吃。' },
    { en: 'There is no place like home.', zh: '金窝银窝不如自己的狗窝。' },
    { en: 'Time and tide wait for no man.', zh: '时不我待。' },
    { en: 'Variety is the spice of life.', zh: '变化是生活的调味品。' },
    { en: 'When one door closes, another opens.', zh: '天无绝人之路。' },
    { en: 'You reap what you sow.', zh: '种瓜得瓜，种豆得豆。' },
    { en: 'A mans home is his castle.', zh: '家是一个人的城堡。' },
    { en: 'An ounce of prevention is worth a pound of cure.', zh: '预防胜于治疗。' },
    { en: 'Dont cry over spilt milk.', zh: '覆水难收。' },
    { en: 'Dont put the cart before the horse.', zh: '不要本末倒置。' },
    { en: 'Every man has his price.', zh: '人各有价。' },
    { en: 'First impressions are the most lasting.', zh: '第一印象最持久。' },
    { en: 'Good fences make good neighbors.', zh: '篱笆筑得牢，邻居处得好。' },
    { en: 'If you cant beat them, join them.', zh: '打不过就加入。' },
    { en: 'Its no use crying over spilt milk.', zh: '覆水难收，后悔无用。' },
    { en: 'Let the cat out of the bag.', zh: '泄露秘密。' },
    { en: 'Make hay while the sun shines.', zh: '趁热打铁。' },
    { en: 'Necessity knows no law.', zh: '急不顾法。' },
    { en: 'Once bitten, twice shy.', zh: '一朝被蛇咬，十年怕井绳。' },
    { en: 'Strike while the iron is hot.', zh: '趁热打铁。' },
    { en: 'The best things in life are free.', zh: '人生最美好的东西都是免费的。' },
    { en: 'The devil finds work for idle hands.', zh: '闲则生非。' },
    { en: 'There is no such thing as a free lunch.', zh: '天下没有免费的午餐。' },
    { en: 'Tomorrow is another day.', zh: '明天又是新的一天。' },
    { en: 'Where there is life, there is hope.', zh: '留得青山在，不怕没柴烧。' },
    { en: 'You cant teach an old dog new tricks.', zh: '老狗学不会新把戏。' },
    { en: 'Absence makes the heart grow fonder.', zh: '距离产生美。' },
    { en: 'Actions speak louder than words.', zh: '事实胜于雄辩。' },
    { en: 'All good things come to an end.', zh: '天下没有不散的筵席。' },
    { en: 'Beauty is only skin deep.', zh: '美貌只是皮相。' },
    { en: 'Beggars cant be choosers.', zh: '乞丐没有选择权。' },
    { en: 'Better late than never.', zh: '迟做总比不做好。' },
    { en: 'Birds of a feather flock together.', zh: '物以类聚，人以群分。' },
    { en: 'Blood is thicker than water.', zh: '血浓于水。' },
    { en: 'Dont count your chickens before they hatch.', zh: '不要过早乐观。' },
    { en: 'Dont put all your eggs in one basket.', zh: '不要孤注一掷。' },
    { en: 'Every man has his price.', zh: '人各有价。' },
    { en: 'First impressions are the most lasting.', zh: '第一印象最持久。' },
    { en: 'Good things come to those who wait.', zh: '好事多磨。' },
    { en: 'Hope for the best, prepare for the worst.', zh: '抱最好的希望，做最坏的打算。' },
    { en: 'If you cant beat them, join them.', zh: '打不过就加入。' },
    { en: 'Imitation is the sincerest form of flattery.', zh: '模仿是最真诚的恭维。' },
    { en: 'It takes two to tango.', zh: '一个巴掌拍不响。' },
    { en: 'Keep your friends close and your enemies closer.', zh: '知己知彼，百战不殆。' },
    { en: 'Laughter is the best medicine.', zh: '笑一笑，十年少。' },
    { en: 'Learn from yesterday, live for today, hope for tomorrow.', zh: '总结昨天，活在当下，展望明天。' },
    { en: 'Life is what happens when youre busy making other plans.', zh: '生活就是当你忙着制定其他计划时发生的事情。' },
    { en: 'Love is blind.', zh: '爱情是盲目的。' },
    { en: 'Money doesnt grow on trees.', zh: '钱来之不易。' },
    { en: 'Necessity is the mother of invention.', zh: '需要是发明之母。' },
    { en: 'Never judge a book by its cover.', zh: '不要以貌取人。' },
    { en: 'No man is an island.', zh: '没有人是一座孤岛。' },
    { en: 'Nothing ventured, nothing gained.', zh: '不入虎穴，焉得虎子。' },
    { en: 'One mans trash is another mans treasure.', zh: '甲之蜜糖，乙之砒霜。' },
    { en: 'Out of sight, out of mind.', zh: '眼不见，心不烦。' },
    { en: 'Patience is a virtue.', zh: '耐心是一种美德。' },
    { en: 'Prevention is better than cure.', zh: '预防胜于治疗。' },
    { en: 'Rome was not built in a day.', zh: '冰冻三尺非一日之寒。' },
    { en: 'Silence is golden.', zh: '沉默是金。' },
    { en: 'The early bird catches the worm.', zh: '早起的鸟儿有虫吃。' },
    { en: 'The pen is mightier than the sword.', zh: '笔诛胜于剑伐。' },
    { en: 'There is no place like home.', zh: '金窝银窝不如自己的狗窝。' },
    { en: 'Time and tide wait for no man.', zh: '时不我待。' },
    { en: 'Two heads are better than one.', zh: '三个臭皮匠，顶个诸葛亮。' },
    { en: 'Variety is the spice of life.', zh: '变化是生活的调味品。' },
    { en: 'When in Rome, do as the Romans do.', zh: '入乡随俗。' },
    { en: 'Where theres a will, theres a way.', zh: '有志者事竟成。' },
    { en: 'You cant have your cake and eat it too.', zh: '鱼与熊掌不可兼得。' },
    { en: 'You reap what you sow.', zh: '种瓜得瓜，种豆得豆。' },
    { en: 'A rolling stone gathers no moss.', zh: '流水不腐，户枢不蠹。' },
    { en: 'An apple a day keeps the doctor away.', zh: '一天一苹果，医生远离我。' },
    { en: 'Dont bite the hand that feeds you.', zh: '不要恩将仇报。' },
    { en: 'Every cloud has a silver lining.', zh: '黑暗中总有一线光明。' },
    { en: 'Fortune favors the bold.', zh: '勇者得胜。' },
    { en: 'Honesty is the best policy.', zh: '诚实为上策。' },
    { en: 'Knowledge is power.', zh: '知识就是力量。' },
    { en: 'Look before you leap.', zh: '三思而后行。' },
    { en: 'Make hay while the sun shines.', zh: '趁热打铁。' },
    { en: 'Once bitten, twice shy.', zh: '一朝被蛇咬，十年怕井绳。' },
    { en: 'Strike while the iron is hot.', zh: '趁热打铁。' },
    { en: 'The best things in life are free.', zh: '人生最美好的东西都是免费的。' },
    { en: 'Time is money.', zh: '时间就是金钱。' },
    { en: 'Well begun is half done.', zh: '好的开始是成功的一半。' },
    { en: 'Where theres smoke, theres fire.', zh: '无风不起浪。' },
    { en: 'You cant judge a book by its cover.', zh: '人不可貌相。' },
    { en: 'A stitch in time saves nine.', zh: '小洞不补，大洞吃苦。' },
    { en: 'All that glitters is not gold.', zh: '发光的未必都是金子。' },
    { en: 'An ounce of prevention is worth a pound of cure.', zh: '预防胜于治疗。' },
    { en: 'Dont cry over spilt milk.', zh: '覆水难收。' },
    { en: 'Dont put the cart before the horse.', zh: '不要本末倒置。' },
    { en: 'Easy come, easy go.', zh: '来得容易去得快。' },
    { en: 'Every dog has its day.', zh: '人人都有得意时。' },
    { en: 'First come, first served.', zh: '先到先得。' },
    { en: 'Great minds think alike.', zh: '英雄所见略同。' },
    { en: 'Haste makes waste.', zh: '欲速则不达。' },
    { en: 'History repeats itself.', zh: '历史总是惊人的相似。' },
    { en: 'Home is where the heart is.', zh: '心在哪里，家就在哪里。' },
    { en: 'If you want a thing done well, do it yourself.', zh: '求人不如求己。' },
    { en: 'It never rains but it pours.', zh: '祸不单行。' },
    { en: 'Kill two birds with one stone.', zh: '一石二鸟。' },
    { en: 'Let sleeping dogs lie.', zh: '不要自找麻烦。' },
    { en: 'Life is not a bed of roses.', zh: '生活并非一帆风顺。' },
    { en: 'Like father, like son.', zh: '有其父必有其子。' },
    { en: 'Many hands make light work.', zh: '众人拾柴火焰高。' },
    { en: 'Old habits die hard.', zh: '江山易改，本性难移。' },
    { en: 'One good turn deserves another.', zh: '善有善报。' },
    { en: 'Practice makes perfect.', zh: '熟能生巧。' },
    { en: 'Slow and steady wins the race.', zh: '稳扎稳打，无往不胜。' },
    { en: 'The squeaky wheel gets the grease.', zh: '会哭的孩子有奶吃。' },
    { en: 'When one door closes, another opens.', zh: '天无绝人之路。' }
];

const phrases = [
    { en: 'a piece of cake', zh: '小菜一碟' },
    { en: 'break a leg', zh: '祝好运' },
    { en: 'call it a day', zh: '收工' },
    { en: 'cut corners', zh: '走捷径' },
    { en: 'piece of mind', zh: '安心' },
    { en: 'hit the hay', zh: '睡觉' },
    { en: 'on cloud nine', zh: '非常开心' },
    { en: 'spill the beans', zh: '泄露秘密' },
    { en: 'break the ice', zh: '打破沉默' },
    { en: 'cost an arm and a leg', zh: '非常昂贵' },
    { en: 'under the weather', zh: '身体不适' },
    { en: 'the ball is in your court', zh: '该你行动了' },
    { en: 'once in a blue moon', zh: '千载难逢' },
    { en: 'two peas in a pod', zh: '一模一样' },
    { en: 'beat around the bush', zh: '拐弯抹角' },
    { en: 'barking up the wrong tree', zh: '找错对象' },
    { en: 'the best of both worlds', zh: '两全其美' },
    { en: 'bite the bullet', zh: '咬紧牙关' },
    { en: 'cry over spilt milk', zh: '覆水难收' },
    { en: 'curiosity killed the cat', zh: '好奇害死猫' },
    { en: 'easy come, easy go', zh: '来得容易去得快' },
    { en: 'every cloud has a silver lining', zh: '黑暗中总有一丝光明' },
    { en: 'get out of hand', zh: '失去控制' },
    { en: 'give someone the cold shoulder', zh: '冷落某人' },
    { en: 'go the extra mile', zh: '加倍努力' },
    { en: 'hang in there', zh: '坚持住' },
    { en: 'hit the nail on the head', zh: '一针见血' },
    { en: 'keep your chin up', zh: '别灰心' },
    { en: 'kill two birds with one stone', zh: '一石二鸟' },
    { en: 'let the cat out of the bag', zh: '泄露秘密' },
    { en: 'live and let live', zh: '互相包容' },
    { en: 'make a long story short', zh: '长话短说' },
    { en: 'miss the boat', zh: '错失良机' },
    { en: 'no pain, no gain', zh: '一分耕耘，一分收获' },
    { en: 'on the ball', zh: '机灵' },
    { en: 'play it by ear', zh: '见机行事' },
    { en: 'pull someones leg', zh: '开玩笑' },
    { en: 'put yourself in someones shoes', zh: '设身处地' },
    { en: 'see eye to eye', zh: '看法一致' },
    { en: 'sit tight', zh: '耐心等待' },
    { en: 'sleep on it', zh: '把问题留到第二天再决定' },
    { en: 'speak of the devil', zh: '说曹操曹操到' },
    { en: 'take it easy', zh: '放轻松' },
    { en: 'take with a grain of salt', zh: '半信半疑' },
    { en: 'the last straw', zh: '压死骆驼的最后一根稻草' },
    { en: 'through thick and thin', zh: '风雨同舟' },
    { en: 'time flies', zh: '光阴似箭' },
    { en: 'under the gun', zh: '在压力下' },
    { en: 'up in the air', zh: '悬而未决' },
    { en: 'when pigs fly', zh: '绝无可能' },
    { en: 'wrap your head around', zh: '弄明白' },
    { en: 'your guess is as good as mine', zh: '我也不知道' },
    { en: 'a blessing in disguise', zh: '因祸得福' },
    { en: 'add insult to injury', zh: '雪上加霜' },
    { en: 'all ears', zh: '洗耳恭听' },
    { en: 'all thumbs', zh: '笨手笨脚' },
    { en: 'apple of my eye', zh: '掌上明珠' },
    { en: 'back to the drawing board', zh: '从头开始' },
    { en: 'beating around the bush', zh: '拐弯抹角' },
    { en: 'behind the scenes', zh: '幕后' },
    { en: 'bend over backwards', zh: '竭尽全力' },
    { en: 'between a rock and a hard place', zh: '进退两难' },
    { en: 'birds of a feather flock together', zh: '物以类聚' },
    { en: 'blow off steam', zh: '发泄情绪' },
    { en: 'burn the midnight oil', zh: '熬夜工作' },
    { en: 'butterflies in my stomach', zh: '紧张不安' },
    { en: 'by the skin of your teeth', zh: '勉强成功' },
    { en: 'call it quits', zh: '放弃' },
    { en: 'catch some zzzs', zh: '睡觉' },
    { en: 'chill out', zh: '冷静下来' },
    { en: 'cold feet', zh: '临阵退缩' },
    { en: 'come rain or shine', zh: '风雨无阻' },
    { en: 'cut to the chase', zh: '直奔主题' },
    { en: 'down in the dumps', zh: '情绪低落' },
    { en: 'draw the line', zh: '划定底线' },
    { en: 'drive someone up the wall', zh: '让某人抓狂' },
    { en: 'drop the ball', zh: '犯错误' },
    { en: 'eat humble pie', zh: '低声下气' },
    { en: 'elbow grease', zh: '费力工作' },
    { en: 'face the music', zh: '承担后果' },
    { en: 'feel under the weather', zh: '身体不适' },
    { en: 'fingers crossed', zh: '祈求好运' },
    { en: 'get a taste of your own medicine', zh: '自食其果' },
    { en: 'get wind of', zh: '听到风声' },
    { en: 'give it a shot', zh: '试一试' },
    { en: 'go with the flow', zh: '顺其自然' },
    { en: 'got a sweet tooth', zh: '爱吃甜食' },
    { en: 'have a blast', zh: '玩得很开心' },
    { en: 'have your hands full', zh: '忙得不可开交' },
    { en: 'head over heels', zh: '神魂颠倒' },
    { en: 'hit the road', zh: '出发' },
    { en: 'hold your horses', zh: '慢点' },
    { en: 'in hot water', zh: '有麻烦' },
    { en: 'in the same boat', zh: '同舟共济' },
    { en: 'its not rocket science', zh: '这并不难' },
    { en: 'jump on the bandwagon', zh: '随大流' },
    { en: 'keep an eye on', zh: '留意' },
    { en: 'keep your fingers crossed', zh: '祈求好运' },
    { en: 'knock on wood', zh: '祈求好运' },
    { en: 'leave no stone unturned', zh: '千方百计' },
    { en: 'let sleeping dogs lie', zh: '不要自找麻烦' },
    { en: 'live on the edge', zh: '冒险生活' },
    { en: 'lose your marbles', zh: '失去理智' },
    { en: 'make ends meet', zh: '收支平衡' },
    { en: 'make waves', zh: '兴风作浪' },
    { en: 'nip it in the bud', zh: '防患于未然' },
    { en: 'off the hook', zh: '脱身' },
    { en: 'out of the blue', zh: '出乎意料' },
    { en: 'over the moon', zh: '欣喜若狂' },
    { en: 'paint the town red', zh: '狂欢' },
    { en: 'pass the buck', zh: '推卸责任' },
    { en: 'pay the piper', zh: '承担后果' },
    { en: 'penny for your thoughts', zh: '你在想什么' },
    { en: 'pick someones brain', zh: '请教意见' },
    { en: 'play devil\'s advocate', zh: '唱反调' },
    { en: 'play it cool', zh: '装作若无其事' },
    { en: 'pull strings', zh: '走后门' },
    { en: 'push the envelope', zh: '突破极限' },
    { en: 'put all your eggs in one basket', zh: '孤注一掷' },
    { en: 'put the cart before the horse', zh: '本末倒置' },
    { en: 'rain cats and dogs', zh: '倾盆大雨' },
    { en: 'read between the lines', zh: '读懂言外之意' },
    { en: 'ring a bell', zh: '听起来耳熟' },
    { en: 'roll out the red carpet', zh: '隆重欢迎' },
    { en: 'rub someone the wrong way', zh: '惹恼某人' },
    { en: 'rule of thumb', zh: '经验法则' },
    { en: 'run out of steam', zh: '精疲力尽' },
    { en: 'save face', zh: '保全面子' },
    { en: 'second thoughts', zh: '重新考虑' },
    { en: 'see the light', zh: '恍然大悟' },
    { en: 'shoot the breeze', zh: '闲聊' },
    { en: 'short end of the stick', zh: '吃亏' },
    { en: 'slip of the tongue', zh: '口误' },
    { en: 'smooth sailing', zh: '一帆风顺' },
    { en: 'snug as a bug in a rug', zh: '非常舒适' },
    { en: 'speak your mind', zh: '直言不讳' },
    { en: 'stab in the back', zh: '背后捅刀' },
    { en: 'steal someones thunder', zh: '抢风头' },
    { en: 'stick your neck out', zh: '冒险' },
    { en: 'straight from the horses mouth', zh: '消息可靠' },
    { en: 'take a rain check', zh: '改天再说' },
    { en: 'take it with a pinch of salt', zh: '半信半疑' },
    { en: 'the whole nine yards', zh: '全部' },
    { en: 'think outside the box', zh: '跳出思维定式' },
    { en: 'throw in the towel', zh: '认输' },
    { en: 'tie the knot', zh: '结婚' },
    { en: 'tip of the iceberg', zh: '冰山一角' },
    { en: 'touch wood', zh: '祈求好运' },
    { en: 'turn a blind eye', zh: '视而不见' },
    { en: 'turn over a new leaf', zh: '改过自新' },
    { en: 'under ones breath', zh: '低声地' },
    { en: 'walk on eggshells', zh: '如履薄冰' },
    { en: 'wear your heart on your sleeve', zh: '感情外露' },
    { en: 'wild goose chase', zh: '徒劳无功' },
    { en: 'work like a dog', zh: '拼命工作' },
    { en: 'you can say that again', zh: '说得太对了' },
    { en: 'zero tolerance', zh: '零容忍' },
    { en: 'a dime a dozen', zh: '多如牛毛' },
    { en: 'a drop in the bucket', zh: '杯水车薪' },
    { en: 'a needle in a haystack', zh: '大海捞针' },
    { en: 'an arm and a leg', zh: '非常昂贵' },
    { en: 'around the clock', zh: '昼夜不停' },
    { en: 'back to square one', zh: '从头开始' },
    { en: 'ball is in your court', zh: '轮到你了' },
    { en: 'beat a dead horse', zh: '白费口舌' },
    { en: 'bend over backwards', zh: '竭尽全力' },
    { en: 'bite off more than you can chew', zh: '贪多嚼不烂' },
    { en: 'burn the candle at both ends', zh: '起早贪黑' },
    { en: 'buy a pig in a poke', zh: '盲目购买' },
    { en: 'call a spade a spade', zh: '直言不讳' },
    { en: 'carry coals to Newcastle', zh: '多此一举' },
    { en: 'cast pearls before swine', zh: '对牛弹琴' },
    { en: 'catch-22', zh: '进退两难' },
    { en: 'come clean', zh: '坦白交代' },
    { en: 'cook the books', zh: '做假账' },
    { en: 'cry wolf', zh: '虚张声势' },
    { en: 'cut both ways', zh: '有利有弊' },
    { en: 'cut the mustard', zh: '达到标准' },
    { en: 'dead as a doornail', zh: '死透了' },
    { en: 'devil is in the details', zh: '细节决定成败' },
    { en: 'do a runner', zh: '逃跑' },
    { en: 'dont hold your breath', zh: '别指望了' },
    { en: 'down for the count', zh: '彻底失败' },
    { en: 'draw a blank', zh: '想不起来' },
    { en: 'drive a hard bargain', zh: '讨价还价' },
    { en: 'eat your words', zh: '承认错误' },
    { en: 'every Tom, Dick and Harry', zh: '张三李四' },
    { en: 'fall on deaf ears', zh: '充耳不闻' },
    { en: 'far cry from', zh: '相去甚远' },
    { en: 'few and far between', zh: '寥寥无几' },
    { en: 'fly on the wall', zh: '暗中观察' },
    { en: 'for crying out loud', zh: '天哪' },
    { en: 'get a grip', zh: '冷静下来' },
    { en: 'get cold feet', zh: '临阵退缩' },
    { en: 'get wind of', zh: '听到风声' },
    { en: 'give it a rest', zh: '别说了' },
    { en: 'go down in flames', zh: '彻底失败' },
    { en: 'go for broke', zh: '孤注一掷' },
    { en: 'go the extra mile', zh: '加倍努力' },
    { en: 'good riddance', zh: '终于走了' },
    { en: 'grease someones palm', zh: '贿赂' },
    { en: 'hammer out', zh: '反复讨论' },
    { en: 'have a lot on your plate', zh: '忙得不可开交' },
    { en: 'have your cake and eat it too', zh: '鱼与熊掌兼得' },
    { en: 'hit the books', zh: '用功读书' },
    { en: 'hit the jackpot', zh: '中大奖' },
    { en: 'hold your horses', zh: '慢点' },
    { en: 'in a nutshell', zh: '简而言之' },
    { en: 'in hot water', zh: '有麻烦' },
    { en: 'in the long run', zh: '从长远来看' },
    { en: 'iron out', zh: '解决问题' },
    { en: 'jump the gun', zh: '操之过急' },
    { en: 'keep an eye on', zh: '留意' },
    { en: 'keep your chin up', zh: '别灰心' },
    { en: 'kill two birds with one stone', zh: '一石二鸟' },
    { en: 'last straw', zh: '最后一根稻草' },
    { en: 'leave well enough alone', zh: '别多事' },
    { en: 'let sleeping dogs lie', zh: '别惹麻烦' },
    { en: 'live and let live', zh: '互相包容' },
    { en: 'lose your shirt', zh: '输个精光' },
    { en: 'make a killing', zh: '大赚一笔' },
    { en: 'make do with', zh: '凑合用' },
    { en: 'miss the boat', zh: '错失良机' },
    { en: 'no pain no gain', zh: '一分耕耘一分收获' },
    { en: 'on the same page', zh: '达成共识' },
    { en: 'out of the blue', zh: '出乎意料' },
    { en: 'pass the buck', zh: '推卸责任' },
    { en: 'pay through the nose', zh: '花大价钱' },
    { en: 'play it by ear', zh: '见机行事' },
    { en: 'pull yourself together', zh: '振作起来' },
    { en: 'put your foot down', zh: '坚决反对' },
    { en: 'read between the lines', zh: '读懂言外之意' },
    { en: 'red herring', zh: '转移注意力' },
    { en: 'ride shotgun', zh: '坐副驾驶' },
    { en: 'rise and shine', zh: '起床了' },
    { en: 'roll with the punches', zh: '灵活应对' },
    { en: 'run out of steam', zh: '精疲力尽' },
    { en: 'save for a rainy day', zh: '未雨绸缪' },
    { en: 'see eye to eye', zh: '看法一致' },
    { en: 'sit on the fence', zh: '保持中立' },
    { en: 'sleep on it', zh: '考虑一晚' },
    { en: 'smooth sailing', zh: '一帆风顺' },
    { en: 'spill the beans', zh: '泄露秘密' },
    { en: 'steal the show', zh: '抢尽风头' },
    { en: 'take a hike', zh: '走开' },
    { en: 'take it with a grain of salt', zh: '半信半疑' },
    { en: 'the ball is in your court', zh: '该你决定了' },
    { en: 'throw caution to the wind', zh: '冒险一试' },
    { en: 'tighten your belt', zh: '勒紧裤腰带' },
    { en: 'under the gun', zh: '在压力下' },
    { en: 'up in the air', zh: '悬而未决' },
    { en: 'when pigs fly', zh: '绝无可能' },
    { en: 'wrap your head around', zh: '弄明白' }
];

const classes = {
    warrior: { 
        name: '战士', 
        icon: '🛡️', 
        hp: 150, 
        attack: 15, 
        defense: 10, 
        passive: '坚韧：受到伤害减少20%',
        rarity: 'rare',
        description: '坚不可摧的守护者'
    },
    archer: { 
        name: '射手', 
        icon: '🏹', 
        hp: 100, 
        attack: 20, 
        defense: 5, 
        passive: '精准：暴击率+30%',
        rarity: 'rare',
        description: '百发百中的猎手'
    },
    mage: { 
        name: '法师', 
        icon: '🔮', 
        hp: 80, 
        attack: 30, 
        defense: 3, 
        passive: '魔力：技能伤害+50%',
        rarity: 'epic',
        description: '掌控元素的智者'
    },
    support: { 
        name: '辅助', 
        icon: '💚', 
        hp: 120, 
        attack: 10, 
        defense: 8, 
        passive: '治愈：每回合恢复10%HP',
        rarity: 'common',
        description: '守护生命的医者'
    },
    assassin: { 
        name: '刺客', 
        icon: '🗡️', 
        hp: 90, 
        attack: 25, 
        defense: 4, 
        passive: '暗影：首击必定暴击',
        rarity: 'epic',
        description: '暗夜中的死神'
    },
    paladin: { 
        name: '圣骑士', 
        icon: '⚔️', 
        hp: 130, 
        attack: 18, 
        defense: 12, 
        passive: '圣光：每回合净化负面状态',
        rarity: 'legendary',
        description: '神圣的守护者'
    },
    necromancer: { 
        name: '死灵法师', 
        icon: '💀', 
        hp: 85, 
        attack: 28, 
        defense: 5, 
        passive: '亡灵：击杀敌人回复30%HP',
        rarity: 'epic',
        description: '操控生死的术士'
    },
    elementalist: { 
        name: '元素师', 
        icon: '🌪️', 
        hp: 75, 
        attack: 32, 
        defense: 2, 
        passive: '元素：技能附带元素效果',
        rarity: 'legendary',
        description: '元素之力的化身'
    },
    berserker: { 
        name: '狂战士', 
        icon: '🪓', 
        hp: 110, 
        attack: 28, 
        defense: 2, 
        passive: '狂怒：HP越低攻击越高',
        rarity: 'rare',
        description: '战场上的疯子'
    },
    monk: { 
        name: '武僧', 
        icon: '👊', 
        hp: 100, 
        attack: 22, 
        defense: 6, 
        passive: '禅意：每回合获得1点能量',
        rarity: 'rare',
        description: '内心平静的武者'
    },
    summoner: { 
        name: '召唤师', 
        icon: '🐲', 
        hp: 70, 
        attack: 15, 
        defense: 3, 
        passive: '召唤：每回合召唤一个随从',
        rarity: 'legendary',
        description: '召唤生物的主人'
    },
    timeMage: { 
        name: '时空法师', 
        icon: '⏰', 
        hp: 65, 
        attack: 25, 
        defense: 2, 
        passive: '时间：每3回合获得额外回合',
        rarity: 'legendary',
        description: '操控时间的神秘者'
    }
};

const enemyTypes = {
    normal: { name: '普通', color: '#94a3b8', hpMod: 1, atkMod: 1 },
    elite: { name: '精英', color: '#3b82f6', hpMod: 1.5, atkMod: 1.3 },
    boss: { name: 'Boss', color: '#a855f7', hpMod: 3, atkMod: 1.8 },
    legendary: { name: '传说', color: '#fbbf24', hpMod: 5, atkMod: 2.5 }
};

const enemies = [
    { name: '史莱姆', icon: '🟢', hp: 50, attack: 8, type: 'normal', skills: ['分裂'] },
    { name: '哥布林', icon: '👺', hp: 80, attack: 12, type: 'normal', skills: ['偷窃'] },
    { name: '骷髅兵', icon: '💀', hp: 100, attack: 15, type: 'normal', skills: ['复活'] },
    { name: '狼人', icon: '🐺', hp: 120, attack: 18, type: 'elite', skills: ['狂暴', '撕咬'] },
    { name: '石像鬼', icon: '🗿', hp: 140, attack: 16, type: 'normal', skills: ['石化'] },
    { name: '幽灵', icon: '👻', hp: 90, attack: 20, type: 'elite', skills: ['穿墙', '恐惧'] },
    { name: '蜘蛛女王', icon: '🕷️', hp: 130, attack: 19, type: 'elite', skills: ['蛛网', '毒液'] },
    { name: '邪眼', icon: '👁️', hp: 110, attack: 17, type: 'normal', skills: ['凝视'] },
    { name: '吸血鬼', icon: '🧛', hp: 150, attack: 22, type: 'elite', skills: ['吸血', '魅惑'] },
    { name: '巫妖', icon: '🧟', hp: 170, attack: 24, type: 'boss', skills: ['亡灵召唤', '冰霜新星'] },
    { name: '地狱犬', icon: '🐕', hp: 160, attack: 21, type: 'elite', skills: ['烈焰吐息'] },
    { name: '地狱火', icon: '🔥', hp: 190, attack: 26, type: 'elite', skills: ['燃烧', '爆炸'] },
    { name: '冰霜巨人', icon: '❄️', hp: 220, attack: 23, type: 'boss', skills: ['冰冻', '地震'] },
    { name: '暗影刺客', icon: '🥷', hp: 85, attack: 29, type: 'elite', skills: ['隐身', '背刺'] },
    { name: '巨魔', icon: '👹', hp: 180, attack: 25, type: 'elite', skills: ['再生', '狂暴'] },
    { name: '恶魔', icon: '😈', hp: 200, attack: 28, type: 'boss', skills: ['地狱火', '诅咒'] },
    { name: '神圣天使', icon: '👼', hp: 280, attack: 32, type: 'boss', skills: ['神圣之光', '复活'] },
    { name: '巨龙', icon: '🐉', hp: 300, attack: 35, type: 'boss', skills: ['龙息', '飞行'] },
    { name: '死神', icon: '💀', hp: 250, attack: 30, type: 'boss', skills: ['收割', '死亡凝视'] },
    { name: '魔王', icon: '👿', hp: 400, attack: 40, type: 'legendary', skills: ['黑暗降临', '召唤恶魔', '毁灭'] },
    { name: '混沌之主', icon: '🌑', hp: 450, attack: 45, type: 'legendary', skills: ['混沌之力', '时空裂隙', '毁灭世界'] },
    { name: '远古巨龙', icon: '🐲', hp: 500, attack: 50, type: 'legendary', skills: ['远古之火', '龙之怒', '末日审判'] }
];

const dungeonGameModes = {
    endless: {
        name: '无尽模式',
        icon: '♾️',
        description: '无限层数的挑战，看你能走多远',
        enemyScaling: 1.1,
        eventChance: 0.3,
        special: '每10层获得一个随机增益'
    },
    timeAttack: {
        name: '限时挑战',
        icon: '⏱️',
        description: '在限定时间内击败尽可能多的敌人',
        enemyScaling: 1.2,
        timeLimit: 300,
        special: '时间结束后根据击杀数结算奖励'
    },
    bossRush: {
        name: 'Bossrush',
        icon: '👑',
        description: '连续挑战Boss，体验极致战斗',
        enemyScaling: 1.5,
        bossOnly: true,
        special: '每层都是Boss敌人'
    },
    puzzle: {
        name: '解谜模式',
        icon: '🧩',
        description: '通过答题来释放技能',
        enemyScaling: 1.0,
        wordQuiz: true,
        special: '答对单词获得能量，答错受到伤害'
    },
    deckBuilder: {
        name: '构筑模式',
        icon: '🃏',
        description: '构建你的卡组，击败敌人',
        enemyScaling: 1.15,
        cardShop: true,
        special: '每层结束后可以购买新卡牌'
    },
    roguelike: {
        name: '肉鸽模式',
        icon: '🎲',
        description: '随机事件和路线选择',
        enemyScaling: 1.2,
        randomEvents: true,
        pathChoice: true,
        special: '每层可以选择不同的路线'
    }
};

const dungeonEvents = [
    { 
        type: 'treasure', 
        name: '宝箱', 
        icon: '📦', 
        description: '发现了一个神秘的宝箱',
        effect: function(game) {
            const rewards = ['gold', 'card', 'heal', 'energy'];
            const reward = rewards[Math.floor(Math.random() * rewards.length)];
            switch(reward) {
                case 'gold': return { type: 'gold', amount: Math.floor(Math.random() * 50) + 20 };
                case 'card': return { type: 'card', rarity: ['rare', 'epic', 'legendary'][Math.floor(Math.random() * 3)] };
                case 'heal': return { type: 'heal', amount: Math.floor(game.playerMaxHP * 0.3) };
                case 'energy': return { type: 'energy', amount: 1 };
            }
        }
    },
    { 
        type: 'shop', 
        name: '商店', 
        icon: '🏪', 
        description: '一个神秘的商人出现在这里',
        items: [
            { name: '生命药水', icon: '❤️', cost: 30, effect: 'heal', value: 50 },
            { name: '能量水晶', icon: '💎', cost: 50, effect: 'maxEnergy', value: 1 },
            { name: '神秘卡牌', icon: '🎴', cost: 80, effect: 'card', value: 'rare' },
            { name: '传说卡牌', icon: '⭐', cost: 200, effect: 'card', value: 'legendary' }
        ]
    },
    { 
        type: 'fountain', 
        name: '生命之泉', 
        icon: '⛲', 
        description: '清澈的泉水散发着神秘的光芒',
        effect: function(game) {
            const healAmount = Math.floor(game.playerMaxHP * 0.5);
            game.playerHP = Math.min(game.playerMaxHP, game.playerHP + healAmount);
            return { healed: healAmount };
        }
    },
    { 
        type: 'shrine', 
        name: '力量神殿', 
        icon: '🏛️', 
        description: '古老的神殿中蕴含着神秘的力量',
        choices: [
            { name: '力量祝福', effect: { attackBonus: 5 } },
            { name: '生命祝福', effect: { maxHPBonus: 20 } },
            { name: '智慧祝福', effect: { maxEnergyBonus: 1 } }
        ]
    },
    { 
        type: 'portal', 
        name: '传送门', 
        icon: '🌀', 
        description: '一个闪烁的传送门，不知道通向何方',
        effect: function(game) {
            const floors = Math.floor(Math.random() * 3) + 1;
            return { skipFloors: floors };
        }
    },
    { 
        type: 'trap', 
        name: '陷阱', 
        icon: '⚠️', 
        description: '小心！这里布满了陷阱',
        effect: function(game) {
            const damage = Math.floor(game.playerMaxHP * 0.15);
            game.playerHP -= damage;
            return { damage: damage };
        }
    },
    { 
        type: 'mystery', 
        name: '神秘事件', 
        icon: '❓', 
        description: '前方有一个神秘的符文',
        choices: [
            { name: '触碰符文', risk: 0.5, goodEffect: { gold: 100, heal: 30 }, badEffect: { damage: 30 } },
            { name: '离开', effect: {} }
        ]
    }
];

const cardEffects = {
    attack: { name: '攻击', desc: '造成基础伤害', effect: 'damage', power: 1 },
    heavy_attack: { name: '重击', desc: '造成1.5倍伤害', effect: 'damage', power: 1.5 },
    double_attack: { name: '连击', desc: '攻击两次', effect: 'double_damage', power: 1 },
    triple_attack: { name: '三连击', desc: '攻击三次', effect: 'triple_damage', power: 1 },
    quad_attack: { name: '四连击', desc: '攻击四次', effect: 'quad_damage', power: 1 },
    heal: { name: '治愈', desc: '恢复20%生命值', effect: 'heal', amount: 0.2 },
    big_heal: { name: '大治愈', desc: '恢复40%生命值', effect: 'heal', amount: 0.4 },
    full_heal: { name: '完全治愈', desc: '恢复全部生命值', effect: 'full_heal', amount: 1 },
    shield: { name: '护盾', desc: '下次受到的伤害减半', effect: 'shield', power: 1 },
    big_shield: { name: '大护盾', desc: '下次受到的伤害减为25%', effect: 'big_shield', power: 1 },
    power_up: { name: '强化', desc: '下次攻击伤害翻倍', effect: 'power_up', power: 2 },
    super_power_up: { name: '超级强化', desc: '下次攻击伤害三倍', effect: 'super_power_up', power: 3 },
    ultimate_power_up: { name: '究极强化', desc: '下次攻击伤害五倍', effect: 'ultimate_power_up', power: 5 },
    poison: { name: '剧毒', desc: '敌人每回合损失10%HP', effect: 'poison', damage: 0.1 },
    super_poison: { name: '致命剧毒', desc: '敌人每回合损失20%HP', effect: 'super_poison', damage: 0.2 },
    stun: { name: '眩晕', desc: '敌人跳过下一回合', effect: 'stun', power: 1 },
    sleep: { name: '催眠', desc: '敌人跳过两回合', effect: 'sleep', power: 1 },
    draw: { name: '抽牌', desc: '额外抽2张牌', effect: 'draw', count: 2 },
    big_draw: { name: '大抽牌', desc: '额外抽4张牌', effect: 'big_draw', count: 4 },
    refresh: { name: '刷新', desc: '抽满手牌', effect: 'refresh', power: 1 },
    critical: { name: '暴击', desc: '必定暴击', effect: 'critical', power: 2 },
    super_critical: { name: '超级暴击', desc: '必定三倍暴击', effect: 'super_critical', power: 3 },
    ultimate_critical: { name: '究极暴击', desc: '必定五倍暴击', effect: 'ultimate_critical', power: 5 },
    lifesteal: { name: '吸血', desc: '回复造成伤害的50%', effect: 'lifesteal', rate: 0.5 },
    big_lifesteal: { name: '大吸血', desc: '回复造成伤害的100%', effect: 'big_lifesteal', rate: 1 },
    fireball: { name: '火球', desc: '造成伤害并附加灼烧', effect: 'fireball', power: 1.5 },
    ice_shield: { name: '冰盾', desc: '获得护盾并冻结敌人', effect: 'ice_shield', power: 1 },
    thunder: { name: '雷霆', desc: '造成伤害并有概率眩晕', effect: 'thunder', power: 1.3 },
    regeneration: { name: '再生', desc: '每回合恢复10%HP', effect: 'regeneration', amount: 0.1 },
    super_regeneration: { name: '超级再生', desc: '每回合恢复20%HP', effect: 'super_regeneration', amount: 0.2 },
    energy_restore: { name: '能量恢复', desc: '恢复2点能量', effect: 'energy_restore', amount: 2 },
    full_energy: { name: '能量满格', desc: '能量恢复至满', effect: 'full_energy', power: 1 },
    damage_reduction: { name: '减伤', desc: '受到的伤害减少30%', effect: 'damage_reduction', rate: 0.3 },
    damage_immunity: { name: '免疫', desc: '本回合免疫所有伤害', effect: 'damage_immunity', power: 1 },
    damage_boost: { name: '伤害提升', desc: '所有伤害提升30%', effect: 'damage_boost', rate: 0.3 },
    double_damage: { name: '双倍伤害', desc: '所有伤害翻倍', effect: 'double_damage', rate: 1 },
    draw_risk: { name: '冒险抽牌', desc: '抽5张牌但敌人也回20%血', effect: 'draw_risk', count: 5 },
    counter: { name: '反击', desc: '反弹下次受到的50%伤害', effect: 'counter', rate: 0.5 },
    big_counter: { name: '大反击', desc: '反弹下次受到的100%伤害', effect: 'big_counter', rate: 1 },
    curse: { name: '诅咒', desc: '敌人攻击降低30%持续3回合', effect: 'curse', rate: 0.3 },
    berserk: { name: '狂暴', desc: '攻击+50%但受到伤害+30%', effect: 'berserk', attackRate: 0.5, damageRate: 0.3 },
    holy_light: { name: '圣光', desc: '恢复30%HP并净化所有负面效果', effect: 'holy_light', amount: 0.3 },
    shadow_step: { name: '暗影步', desc: '下次攻击必定暴击且无视防御', effect: 'shadow_step', power: 1 },
    time_warp: { name: '时间扭曲', desc: '额外获得一个回合', effect: 'time_warp', power: 1 },
    soul_reap: { name: '灵魂收割', desc: '造成伤害并偷取敌人一个正面效果', effect: 'soul_reap', power: 1.2 },
    elemental_fury: { name: '元素之怒', desc: '造成火、冰、雷三种元素伤害', effect: 'elemental_fury', power: 2 },
    divine_shield: { name: '神圣护盾', desc: '免疫3次伤害', effect: 'divine_shield', charges: 3 },
    arcane_missiles: { name: '奥术飞弹', desc: '随机造成3-5次伤害', effect: 'arcane_missiles', power: 0.8 },
    void_rift: { name: '虚空裂隙', desc: '造成2倍伤害但自己也受到50%伤害', effect: 'void_rift', power: 2, selfDamage: 0.5 },
    phoenix_blessing: { name: '凤凰祝福', desc: '下次死亡时复活并恢复50%HP', effect: 'phoenix_blessing', power: 1 },
    chaos_storm: { name: '混沌风暴', desc: '随机触发3种不同效果', effect: 'chaos_storm', power: 1 },
    guardian_angel: { name: '守护天使', desc: '本回合免疫伤害并恢复20%HP', effect: 'guardian_angel', amount: 0.2 },
    blood_pact: { name: '血之契约', desc: '消耗30%HP，造成4倍伤害', effect: 'blood_pact', power: 4, cost: 0.3 },
    arcane_blast: { name: '奥术冲击', desc: '造成1.8倍伤害并消耗所有能量造成额外伤害', effect: 'arcane_blast', power: 1.8 }
};

const rarityWeights = {
    common: 0.60,
    rare: 0.25,
    epic: 0.12,
    legendary: 0.03
};

let gameState = {
    score: 0,
    notebook: [],
    reviewed: [],
    achievements: [],
    collection: [],
    reciteProgress: 0,
    streak: 0,
    todayLearned: 0,
    lastLoginDate: null,
    audioPlaylist: []
};

function loadGameState() {
    const saved = localStorage.getItem('englishLearningState_v2');
    if (saved) {
        gameState = JSON.parse(saved);
    }
    checkDailyLogin();
}

function saveGameState() {
    localStorage.setItem('englishLearningState_v2', JSON.stringify(gameState));
}

function checkDailyLogin() {
    const today = new Date().toDateString();
    if (gameState.lastLoginDate !== today) {
        if (gameState.lastLoginDate) {
            const yesterday = new Date();
            yesterday.setDate(yesterday.getDate() - 1);
            if (gameState.lastLoginDate === yesterday.toDateString()) {
                gameState.streak++;
            } else {
                gameState.streak = 1;
            }
        } else {
            gameState.streak = 1;
        }
        gameState.todayLearned = 0;
        gameState.lastLoginDate = today;
        addScore(10);
        saveGameState();
    }
}

function addScore(amount) {
    gameState.score += amount;
    saveGameState();
    updateScoreDisplay();
}

function unlockAchievement(id) {
    if (!gameState.achievements.includes(id)) {
        gameState.achievements.push(id);
        if (!gameState.achievementTimes) gameState.achievementTimes = {};
        gameState.achievementTimes[id] = new Date().toLocaleString('zh-CN');
        saveGameState();
        const ach = achievements.find(a => a.id === id);
        if (ach) {
            showAchievementToast(ach);
        }
        if (typeof displayAchievementsRedesigned === 'function') {
            displayAchievementsRedesigned();
        }
        if (typeof updateAchievementStats === 'function') {
            updateAchievementStats();
        }
    }
}

function showAchievementToast(ach) {
    const toast = document.getElementById('achievement-toast');
    const toastName = document.getElementById('achievement-toast-name');
    if (toast && toastName) {
        toastName.textContent = ach.name;
        toast.classList.remove('hidden');
        toast.classList.add('show');
        setTimeout(() => {
            toast.classList.remove('show');
            toast.classList.add('hidden');
        }, 4000);
    }
}

function updateScoreDisplay() {
    const scoreDisplay = document.getElementById('score-display');
    const gachaScore = document.getElementById('gacha-score');
    if (scoreDisplay) scoreDisplay.textContent = gameState.score;
    if (gachaScore) gachaScore.textContent = gameState.score;
}

function generateCardRarity() {
    const rand = Math.random();
    let cumulative = 0;
    for (const [rarity, weight] of Object.entries(rarityWeights)) {
        cumulative += weight;
        if (rand < cumulative) return rarity;
    }
    return 'common';
}

function getEffectByRarity(rarity) {
    const effects = Object.keys(cardEffects);
    let availableEffects;
    switch(rarity) {
        case 'legendary':
            availableEffects = ['stun', 'sleep', 'refresh', 'critical', 'super_critical', 'ultimate_critical', 'lifesteal', 'big_lifesteal', 'fireball', 'ice_shield', 'thunder', 'super_regeneration', 'full_energy', 'damage_immunity', 'double_damage', 'draw_risk', 'holy_light', 'shadow_step', 'time_warp', 'soul_reap', 'elemental_fury', 'divine_shield', 'phoenix_blessing', 'chaos_storm', 'guardian_angel', 'blood_pact', 'arcane_blast'];
            break;
        case 'epic':
            availableEffects = ['double_attack', 'triple_attack', 'quad_attack', 'shield', 'big_shield', 'poison', 'super_poison', 'draw', 'big_draw', 'fireball', 'ice_shield', 'energy_restore', 'damage_reduction', 'damage_boost', 'counter', 'big_counter', 'curse', 'berserk', 'arcane_missiles', 'void_rift'];
            break;
        case 'rare':
            availableEffects = ['heavy_attack', 'heal', 'big_heal', 'power_up', 'super_power_up', 'thunder', 'regeneration', 'damage_reduction', 'damage_boost', 'counter'];
            break;
        default:
            availableEffects = ['attack', 'heal', 'shield', 'power_up'];
    }
    return availableEffects[Math.floor(Math.random() * availableEffects.length)];
}

loadGameState();