var phrasesData = {
    phrases: [
        { id: 1, english: "a piece of cake", chinese: "小菜一碟，轻而易举", category: "idiom" },
        { id: 2, english: "break a leg", chinese: "祝你好运", category: "idiom" },
        { id: 3, english: "hit the books", chinese: "用功读书", category: "study" },
        { id: 4, english: "let the cat out of the bag", chinese: "泄露秘密", category: "idiom" },
        { id: 5, english: "pull someone's leg", chinese: "开某人玩笑", category: "idiom" },
        { id: 6, english: "under the weather", chinese: "身体不适", category: "health" },
        { id: 7, english: "cost an arm and a leg", chinese: "非常昂贵", category: "money" },
        { id: 8, english: "once in a blue moon", chinese: "千载难逢，极少", category: "frequency" },
        { id: 9, english: "see eye to eye", chinese: "看法一致", category: "agreement" },
        { id: 10, english: "kill two birds with one stone", chinese: "一石二鸟", category: "efficiency" },
        { id: 11, english: "let sleeping dogs lie", chinese: "不要惹事生非", category: "conflict" },
        { id: 12, english: "speak of the devil", chinese: "说曹操曹操到", category: "coincidence" },
        { id: 13, english: "time flies", chinese: "光阴似箭", category: "time" },
        { id: 14, english: "better late than never", chinese: "迟做总比不做好", category: "proverb" },
        { id: 15, english: "no pain, no gain", chinese: "一分耕耘一分收获", category: "effort" },
        { id: 16, english: "hang in there", chinese: "坚持下去", category: "encouragement" },
        { id: 17, english: "go with the flow", chinese: "顺其自然", category: "attitude" },
        { id: 18, english: "keep it up", chinese: "继续保持", category: "encouragement" },
        { id: 19, english: "take it easy", chinese: "放轻松", category: "relaxation" },
        { id: 20, english: "give it a shot", chinese: "试一试", category: "attempt" },
        { id: 21, english: "make up one's mind", chinese: "下定决心", category: "decision" },
        { id: 22, english: "keep an eye on", chinese: "留意，照看", category: "attention" },
        { id: 23, english: "call it a day", chinese: "收工，结束一天的工作", category: "work" },
        { id: 24, english: "cut to the chase", chinese: "直奔主题", category: "communication" },
        { id: 25, english: "get out of hand", chinese: "失去控制", category: "control" },
        { id: 26, english: "ring a bell", chinese: "听起来熟悉", category: "memory" },
        { id: 27, english: "barking up the wrong tree", chinese: "找错对象了", category: "mistake" },
        { id: 28, english: "bite off more than you can chew", chinese: "贪多嚼不烂", category: "mistake" },
        { id: 29, english: "burn the midnight oil", chinese: "熬夜工作或学习", category: "work" },
        { id: 30, english: "catch some Z's", chinese: "睡觉", category: "sleep" },
        { id: 31, english: "crack someone up", chinese: "让某人大笑", category: "emotion" },
        { id: 32, english: "cut corners", chinese: "偷工减料", category: "quality" },
        { id: 33, english: "drive someone up the wall", chinese: "让某人抓狂", category: "emotion" },
        { id: 34, english: "drop someone a line", chinese: "给某人写信", category: "communication" },
        { id: 35, english: "feel under the weather", chinese: "感觉不舒服", category: "health" },
        { id: 36, english: "fill someone in", chinese: "告诉某人详情", category: "communication" },
        { id: 37, english: "get something off one's chest", chinese: "倾诉心声", category: "emotion" },
        { id: 38, english: "give someone the cold shoulder", chinese: "冷落某人", category: "relationship" },
        { id: 39, english: "go Dutch", chinese: "AA制", category: "money" },
        { id: 40, english: "hit the sack", chinese: "上床睡觉", category: "sleep" },
        { id: 41, english: "in the heat of the moment", chinese: "一时冲动", category: "emotion" },
        { id: 42, english: "keep one's chin up", chinese: "不气馁", category: "encouragement" },
        { id: 43, english: "lose one's cool", chinese: "失去冷静", category: "emotion" },
        { id: 44, english: "miss the boat", chinese: "错失良机", category: "opportunity" },
        { id: 45, english: "on the ball", chinese: "机灵，能干", category: "ability" },
        { id: 46, english: "play it by ear", chinese: "见机行事", category: "planning" },
        { id: 47, english: "rule of thumb", chinese: "经验法则", category: "guideline" },
        { id: 48, english: "sleep on it", chinese: "把问题留到第二天再决定", category: "decision" },
        { id: 49, english: "take with a grain of salt", chinese: "半信半疑", category: "skepticism" },
        { id: 50, english: "through thick and thin", chinese: "风雨同舟", category: "loyalty" },
        { id: 51, english: "throw in the towel", chinese: "认输", category: "defeat" },
        { id: 52, english: "touch and go", chinese: "形势危急", category: "situation" },
        { id: 53, english: "turn a blind eye", chinese: "视而不见", category: "ignorance" },
        { id: 54, english: "up in the air", chinese: "悬而未决", category: "uncertainty" },
        { id: 55, english: "walk on eggshells", chinese: "如履薄冰", category: "caution" },
        { id: 56, english: "when pigs fly", chinese: "绝不可能", category: "impossibility" },
        { id: 57, english: "wrap one's head around", chinese: "理解，弄明白", category: "understanding" },
        { id: 58, english: "your guess is as good as mine", chinese: "我也不知道", category: "uncertainty" },
        { id: 59, english: "a dime a dozen", chinese: "多得很，不稀罕", category: "value" },
        { id: 60, english: "beat around the bush", chinese: "拐弯抹角", category: "communication" },
        { id: 61, english: "bite the bullet", chinese: "硬着头皮做", category: "courage" },
        { id: 62, english: "blow off steam", chinese: "发泄情绪", category: "emotion" },
        { id: 63, english: "by the skin of one's teeth", chinese: "勉强成功", category: "success" },
        { id: 64, english: "cry over spilt milk", chinese: "为无法挽回的事后悔", category: "regret" },
        { id: 65, english: "cut someone some slack", chinese: "对某人宽容些", category: "tolerance" },
        { id: 66, english: "draw the line", chinese: "划定界限", category: "boundary" },
        { id: 67, english: "get a kick out of", chinese: "从...中获得乐趣", category: "enjoyment" },
        { id: 68, english: "get wind of", chinese: "听到风声", category: "information" },
        { id: 69, english: "have a blast", chinese: "玩得很开心", category: "enjoyment" },
        { id: 70, english: "hit the nail on the head", chinese: "一针见血", category: "accuracy" },
        { id: 71, english: "jump to conclusions", chinese: "草率下结论", category: "judgment" },
        { id: 72, english: "keep one's fingers crossed", chinese: "祈求好运", category: "luck" },
        { id: 73, english: "leave no stone unturned", chinese: "千方百计", category: "effort" },
        { id: 74, english: "live and let live", chinese: "互相宽容", category: "tolerance" },
        { id: 75, english: "make a long story short", chinese: "长话短说", category: "communication" },
        { id: 76, english: "nip in the bud", chinese: "防患于未然", category: "prevention" },
        { id: 77, english: "off the hook", chinese: "脱身，摆脱困境", category: "freedom" },
        { id: 78, english: "on the same page", chinese: "达成共识", category: "agreement" },
        { id: 79, english: "out of the blue", chinese: "出乎意料", category: "surprise" },
        { id: 80, english: "pass the buck", chinese: "推卸责任", category: "responsibility" },
        { id: 81, english: "pick someone's brain", chinese: "向某人请教", category: "learning" },
        { id: 82, english: "pull strings", chinese: "走后门", category: "influence" },
        { id: 83, english: "put all one's eggs in one basket", chinese: "孤注一掷", category: "risk" },
        { id: 84, english: "read between the lines", chinese: "领会言外之意", category: "understanding" },
        { id: 85, english: "run out of steam", chinese: "精疲力竭", category: "energy" },
        { id: 86, english: "see which way the wind blows", chinese: "观望形势", category: "observation" },
        { id: 87, english: "sit on the fence", chinese: "保持中立", category: "decision" },
        { id: 88, english: "spill the beans", chinese: "泄露秘密", category: "secrecy" },
        { id: 89, english: "steal someone's thunder", chinese: "抢风头", category: "attention" },
        { id: 90, english: "take the bull by the horns", chinese: "当机立断", category: "courage" },
        { id: 91, english: "the last straw", chinese: "压死骆驼的最后一根稻草", category: "tolerance" },
        { id: 92, english: "throw caution to the wind", chinese: "冒险一试", category: "risk" },
        { id: 93, english: "under one's nose", chinese: "眼皮底下", category: "location" },
        { id: 94, english: "wait for the other shoe to drop", chinese: "等待另一只靴子落地", category: "anticipation" },
        { id: 95, english: "wear one's heart on one's sleeve", chinese: "感情外露", category: "emotion" },
        { id: 96, english: "work one's tail off", chinese: "拼命工作", category: "work" },
        { id: 97, english: "you can say that again", chinese: "说得对", category: "agreement" },
        { id: 98, english: "a blessing in disguise", chinese: "因祸得福", category: "fortune" },
        { id: 99, english: "add insult to injury", chinese: "雪上加霜", category: "misfortune" },
        { id: 100, english: "back to the drawing board", chinese: "从头开始", category: "restart" },
        { id: 101, english: "ball is in your court", chinese: "该你行动了", category: "action" },
        { id: 102, english: "barking up the wrong tree", chinese: "找错人了", category: "mistake" },
        { id: 103, english: "be glad to see the back of", chinese: "很高兴某人离开", category: "relief" },
        { id: 104, english: "beat a dead horse", chinese: "白费口舌", category: "futility" },
        { id: 105, english: "bend over backwards", chinese: "竭尽全力", category: "effort" },
        { id: 106, english: "best thing since sliced bread", chinese: "极好的东西", category: "praise" },
        { id: 107, english: "blessing in disguise", chinese: "因祸得福", category: "fortune" },
        { id: 108, english: "burn the candle at both ends", chinese: "起早贪黑", category: "work" },
        { id: 109, english: "can't judge a book by its cover", chinese: "不能以貌取人", category: "judgment" },
        { id: 110, english: "caught between two stools", chinese: "两头落空", category: "dilemma" },
        { id: 111, english: "chip on your shoulder", chinese: "心怀不满", category: "attitude" },
        { id: 112, english: "close but no cigar", chinese: "功亏一篑", category: "failure" },
        { id: 113, english: "come hell or high water", chinese: "无论如何", category: "determination" },
        { id: 114, english: "cross that bridge when you come to it", chinese: "船到桥头自然直", category: "planning" },
        { id: 115, english: "cry wolf", chinese: "虚张声势", category: "deception" },
        { id: 116, english: "curiosity killed the cat", chinese: "好奇害死猫", category: "caution" },
        { id: 117, english: "cut both ways", chinese: "有利有弊", category: "balance" },
        { id: 118, english: "devil's advocate", chinese: "唱反调的人", category: "argument" },
        { id: 119, english: "don't count your chickens", chinese: "不要过早乐观", category: "caution" },
        { id: 120, english: "don't give up the day job", chinese: "别放弃正职", category: "advice" },
        { id: 121, english: "don't put all your eggs in one basket", chinese: "不要孤注一掷", category: "risk" },
        { id: 122, english: "down for the count", chinese: "彻底失败", category: "defeat" },
        { id: 123, english: "down to the wire", chinese: "到最后时刻", category: "deadline" },
        { id: 124, english: "draw a blank", chinese: "想不起来", category: "memory" },
        { id: 125, english: "drive someone up the wall", chinese: "让某人抓狂", category: "annoyance" },
        { id: 126, english: "easy come, easy go", chinese: "来得容易去得快", category: "money" },
        { id: 127, english: "elephant in the room", chinese: "显而易见却被忽视的问题", category: "problem" },
        { id: 128, english: "every cloud has a silver lining", chinese: "黑暗中总有一线光明", category: "optimism" },
        { id: 129, english: "far cry from", chinese: "相去甚远", category: "comparison" },
        { id: 130, english: "feeling under the weather", chinese: "身体不适", category: "health" },
        { id: 131, english: "fight fire with fire", chinese: "以牙还牙", category: "conflict" },
        { id: 132, english: "first things first", chinese: "要事优先", category: "priority" },
        { id: 133, english: "flash in the pan", chinese: "昙花一现", category: "temporary" },
        { id: 134, english: "fly by the seat of your pants", chinese: "凭感觉行事", category: "improvisation" },
        { id: 135, english: "foam at the mouth", chinese: "暴怒", category: "anger" },
        { id: 136, english: "from the horse's mouth", chinese: "从可靠来源得知", category: "information" },
        { id: 137, english: "get a taste of your own medicine", chinese: "自食其果", category: "consequence" },
        { id: 138, english: "get wind of something", chinese: "听到风声", category: "information" },
        { id: 139, english: "give it a rest", chinese: "别再说了", category: "stop" },
        { id: 140, english: "give someone the cold shoulder", chinese: "冷落某人", category: "relationship" },
        { id: 141, english: "go down in flames", chinese: "惨败", category: "failure" },
        { id: 142, english: "go for broke", chinese: "全力以赴", category: "effort" },
        { id: 143, english: "go on a wild goose chase", chinese: "徒劳无功", category: "futility" },
        { id: 144, english: "good things come to those who wait", chinese: "好事多磨", category: "patience" },
        { id: 145, english: "grease someone's palm", chinese: "贿赂", category: "corruption" },
        { id: 146, english: "hair of the dog", chinese: "以毒攻毒", category: "remedy" },
        { id: 147, english: "hand in hand", chinese: "密不可分", category: "relationship" },
        { id: 148, english: "hang in the balance", chinese: "悬而未决", category: "uncertainty" },
        { id: 149, english: "have a bone to pick", chinese: "有账要算", category: "conflict" },
        { id: 150, english: "have your cake and eat it too", chinese: "鱼和熊掌兼得", category: "choice" },
        { id: 151, english: "head over heels", chinese: "神魂颠倒", category: "love" },
        { id: 152, english: "hear it on the grapevine", chinese: "道听途说", category: "information" },
        { id: 153, english: "hit the nail on the head", chinese: "说到点子上了", category: "accuracy" },
        { id: 154, english: "hold your horses", chinese: "慢点", category: "patience" },
        { id: 155, english: "ignorance is bliss", chinese: "无知是福", category: "knowledge" },
        { id: 156, english: "in a nutshell", chinese: "简而言之", category: "summary" },
        { id: 157, english: "in hot water", chinese: "惹上麻烦", category: "trouble" },
        { id: 158, english: "in the heat of the moment", chinese: "一时冲动", category: "impulse" },
        { id: 159, english: "it takes two to tango", chinese: "一个巴掌拍不响", category: "relationship" },
        { id: 160, english: "ivory tower", chinese: "象牙塔", category: "isolation" },
        { id: 161, english: "jack of all trades", chinese: "万事通", category: "skill" },
        { id: 162, english: "jump on the bandwagon", chinese: "跟风", category: "trend" },
        { id: 163, english: "keep your chin up", chinese: "别灰心", category: "encouragement" },
        { id: 164, english: "keep your eyes peeled", chinese: "睁大眼睛", category: "attention" },
        { id: 165, english: "kick the bucket", chinese: "翘辫子", category: "death" },
        { id: 166, english: "kill the goose that lays the golden egg", chinese: "杀鸡取卵", category: "shortsighted" },
        { id: 167, english: "last straw", chinese: "最后一根稻草", category: "tolerance" },
        { id: 168, english: "left high and dry", chinese: "孤立无援", category: "abandonment" },
        { id: 169, english: "let the cat out of the bag", chinese: "泄露秘密", category: "secrecy" },
        { id: 170, english: "live and let live", chinese: "互相宽容", category: "tolerance" },
        { id: 171, english: "lose your shirt", chinese: "输得精光", category: "loss" },
        { id: 172, english: "make ends meet", chinese: "收支平衡", category: "finance" },
        { id: 173, english: "make waves", chinese: "兴风作浪", category: "trouble" },
        { id: 174, english: "miss the point", chinese: "没抓住重点", category: "understanding" },
        { id: 175, english: "money talks", chinese: "金钱万能", category: "money" },
        { id: 176, english: "needle in a haystack", chinese: "大海捞针", category: "difficulty" },
        { id: 177, english: "no pain, no gain", chinese: "不劳无获", category: "effort" },
        { id: 178, english: "no time like the present", chinese: "趁现在", category: "opportunity" },
        { id: 179, english: "not my cup of tea", chinese: "不是我喜欢的", category: "preference" },
        { id: 180, english: "off the record", chinese: "私下说", category: "confidential" },
        { id: 181, english: "old as the hills", chinese: "古老", category: "age" },
        { id: 182, english: "on the dot", chinese: "准时", category: "time" },
        { id: 183, english: "once in a lifetime", chinese: "千载难逢", category: "opportunity" },
        { id: 184, english: "out of the frying pan and into the fire", chinese: "刚出虎穴又入狼窝", category: "misfortune" },
        { id: 185, english: "over the moon", chinese: "欣喜若狂", category: "happiness" },
        { id: 186, english: "paint the town red", chinese: "狂欢", category: "celebration" },
        { id: 187, english: "pay the piper", chinese: "承担后果", category: "consequence" },
        { id: 188, english: "pen is mightier than the sword", chinese: "笔杆子比枪杆子更有力量", category: "power" },
        { id: 189, english: "picture paints a thousand words", chinese: "一幅画胜过千言万语", category: "communication" },
        { id: 190, english: "piece of cake", chinese: "小菜一碟", category: "easy" },
        { id: 191, english: "pot calling the kettle black", chinese: "五十步笑百步", category: "hypocrisy" },
        { id: 192, english: "practice makes perfect", chinese: "熟能生巧", category: "learning" },
        { id: 193, english: "pull the plug", chinese: "终止", category: "stop" },
        { id: 194, english: "put the cart before the horse", chinese: "本末倒置", category: "order" },
        { id: 195, english: "put your best foot forward", chinese: "全力以赴", category: "effort" },
        { id: 196, english: "quick and dirty", chinese: "快速但不完美", category: "method" },
        { id: 197, english: "rain cats and dogs", chinese: "倾盆大雨", category: "weather" },
        { id: 198, english: "read between the lines", chinese: "读懂言外之意", category: "understanding" },
        { id: 199, english: "red herring", chinese: "转移注意力的东西", category: "distraction" },
        { id: 200, english: "right off the bat", chinese: "立刻", category: "time" },
        { id: 201, english: "rock the boat", chinese: "捣乱", category: "trouble" },
        { id: 202, english: "roll with the punches", chinese: "灵活应对", category: "adaptation" },
        { id: 203, english: "rub salt in the wound", chinese: "伤口撒盐", category: "cruelty" },
        { id: 204, english: "saved by the bell", chinese: "死里逃生", category: "rescue" },
        { id: 205, english: "see eye to eye", chinese: "看法一致", category: "agreement" },
        { id: 206, english: "short end of the stick", chinese: "吃亏", category: "disadvantage" },
        { id: 207, english: "shot in the dark", chinese: "瞎猜", category: "guess" },
        { id: 208, english: "sit tight", chinese: "耐心等待", category: "patience" },
        { id: 209, english: "skin of your teeth", chinese: "勉强", category: "narrow" },
        { id: 210, english: "slap on the wrist", chinese: "轻微惩罚", category: "punishment" },
        { id: 211, english: "sleep like a log", chinese: "睡得很香", category: "sleep" },
        { id: 212, english: "slip of the tongue", chinese: "口误", category: "mistake" },
        { id: 213, english: "slow and steady wins the race", chinese: "稳扎稳打", category: "patience" },
        { id: 214, english: "smell a rat", chinese: "感觉不对劲", category: "suspicion" },
        { id: 215, english: "snake in the grass", chinese: "阴险的人", category: "deception" },
        { id: 216, english: "snowball effect", chinese: "滚雪球效应", category: "growth" },
        { id: 217, english: "so far so good", chinese: "到目前为止一切顺利", category: "progress" },
        { id: 218, english: "speak of the devil", chinese: "说曹操曹操到", category: "coincidence" },
        { id: 219, english: "spill the beans", chinese: "泄露秘密", category: "secrecy" },
        { id: 220, english: "spill the tea", chinese: "爆料八卦", category: "gossip" },
        { id: 221, english: "spitting image", chinese: "一模一样", category: "resemblance" },
        { id: 222, english: "stab someone in the back", chinese: "背后捅刀", category: "betrayal" },
        { id: 223, english: "storm in a teacup", chinese: "小题大做", category: "exaggeration" },
        { id: 224, english: "straight from the horse's mouth", chinese: "从可靠来源得知", category: "information" },
        { id: 225, english: "strike while the iron is hot", chinese: "趁热打铁", category: "opportunity" },
        { id: 226, english: "take a rain check", chinese: "改天再说", category: "postponement" },
        { id: 227, english: "take it with a grain of salt", chinese: "半信半疑", category: "skepticism" },
        { id: 228, english: "take someone to task", chinese: "责备某人", category: "criticism" },
        { id: 229, english: "the ball is in your court", chinese: "该你行动了", category: "action" },
        { id: 230, english: "the best of both worlds", chinese: "两全其美", category: "advantage" },
        { id: 231, english: "the devil is in the details", chinese: "细节决定成败", category: "detail" },
        { id: 232, english: "the early bird catches the worm", chinese: "早起的鸟儿有虫吃", category: "opportunity" },
        { id: 233, english: "the elephant in the room", chinese: "显而易见却被忽视的问题", category: "problem" },
        { id: 234, english: "the whole nine yards", chinese: "全部", category: "completeness" },
        { id: 235, english: "there's no such thing as a free lunch", chinese: "天下没有免费的午餐", category: "reality" },
        { id: 236, english: "third time's the charm", chinese: "第三次一定成功", category: "luck" },
        { id: 237, english: "throw in the towel", chinese: "认输", category: "defeat" },
        { id: 238, english: "tighten your belt", chinese: "勒紧裤腰带", category: "economy" },
        { id: 239, english: "time and time again", chinese: "一次又一次", category: "frequency" },
        { id: 240, english: "tip of the iceberg", chinese: "冰山一角", category: "visibility" },
        { id: 241, english: "to each his own", chinese: "各有所好", category: "preference" },
        { id: 242, english: "tongue in cheek", chinese: "半开玩笑", category: "humor" },
        { id: 243, english: "too little, too late", chinese: "太少太晚", category: "insufficient" },
        { id: 244, english: "turn a blind eye", chinese: "视而不见", category: "ignorance" },
        { id: 245, english: "turn over a new leaf", chinese: "改过自新", category: "change" },
        { id: 246, english: "two peas in a pod", chinese: "一模一样", category: "similarity" },
        { id: 247, english: "under the gun", chinese: "压力之下", category: "pressure" },
        { id: 248, english: "up in arms", chinese: "愤怒抗议", category: "protest" },
        { id: 249, english: "vanish into thin air", chinese: "凭空消失", category: "disappearance" },
        { id: 250, english: "walk on eggshells", chinese: "如履薄冰", category: "caution" },
        { id: 251, english: "want someone's head on a platter", chinese: "要某人的脑袋", category: "anger" },
        { id: 252, english: "watch your back", chinese: "小心背后", category: "caution" },
        { id: 253, english: "wear your heart on your sleeve", chinese: "感情外露", category: "emotion" },
        { id: 254, english: "weather the storm", chinese: "渡过难关", category: "endurance" },
        { id: 255, english: "weigh your options", chinese: "权衡选择", category: "decision" },
        { id: 256, english: "what goes around comes around", chinese: "善有善报", category: "karma" },
        { id: 257, english: "when it rains, it pours", chinese: "祸不单行", category: "misfortune" },
        { id: 258, english: "when pigs fly", chinese: "绝不可能", category: "impossibility" },
        { id: 259, english: "when the going gets tough, the tough get going", chinese: "艰难困苦，玉汝于成", category: "perseverance" },
        { id: 260, english: "where there's smoke, there's fire", chinese: "无风不起浪", category: "truth" },
        { id: 261, english: "wild goose chase", chinese: "徒劳无功", category: "futility" },
        { id: 262, english: "win by a nose", chinese: "险胜", category: "victory" },
        { id: 263, english: "wolf in sheep's clothing", chinese: "披着羊皮的狼", category: "deception" },
        { id: 264, english: "work like a dog", chinese: "拼命工作", category: "work" },
        { id: 265, english: "worth its weight in gold", chinese: "价值连城", category: "value" },
        { id: 266, english: "you can lead a horse to water, but you can't make it drink", chinese: "你可以带马到河边，但不能强迫它喝水", category: "willpower" },
        { id: 267, english: "you can't have your cake and eat it too", chinese: "鱼和熊掌不可兼得", category: "choice" },
        { id: 268, english: "you can't make an omelet without breaking eggs", chinese: "有所得必有所失", category: "sacrifice" },
        { id: 269, english: "you reap what you sow", chinese: "种瓜得瓜，种豆得豆", category: "consequence" },
        { id: 270, english: "your guess is as good as mine", chinese: "我也不知道", category: "uncertainty" },
        { id: 271, english: "a bird in the hand is worth two in the bush", chinese: "一鸟在手胜过双鸟在林", category: "certainty" },
        { id: 272, english: "a bitter pill to swallow", chinese: "难以接受的事实", category: "difficulty" },
        { id: 273, english: "a breath of fresh air", chinese: "耳目一新", category: "refreshment" },
        { id: 274, english: "a chain is only as strong as its weakest link", chinese: "链条的强度取决于最弱的一环", category: "strength" },
        { id: 275, english: "a day late and a dollar short", chinese: "太迟了", category: "lateness" },
        { id: 276, english: "a drop in the bucket", chinese: "杯水车薪", category: "insignificance" },
        { id: 277, english: "a fool and his money are soon parted", chinese: "傻瓜的钱留不住", category: "money" },
        { id: 278, english: "a friend in need is a friend indeed", chinese: "患难见真情", category: "friendship" },
        { id: 279, english: "a little bird told me", chinese: "有人私下告诉我", category: "information" },
        { id: 280, english: "a lot on one's plate", chinese: "忙得不可开交", category: "busy" },
        { id: 281, english: "a needle in a haystack", chinese: "大海捞针", category: "difficulty" },
        { id: 282, english: "a penny for your thoughts", chinese: "你在想什么", category: "inquiry" },
        { id: 283, english: "a penny saved is a penny earned", chinese: "省一分就是赚一分", category: "saving" },
        { id: 284, english: "a picture is worth a thousand words", chinese: "一图胜千言", category: "communication" },
        { id: 285, english: "a slap on the wrist", chinese: "轻微惩罚", category: "punishment" },
        { id: 286, english: "a snowball's chance in hell", chinese: "毫无机会", category: "impossibility" },
        { id: 287, english: "a stone's throw away", chinese: "近在咫尺", category: "distance" },
        { id: 288, english: "a storm in a teacup", chinese: "小题大做", category: "exaggeration" },
        { id: 289, english: "a taste of your own medicine", chinese: "自食其果", category: "consequence" },
        { id: 290, english: "a wolf in sheep's clothing", chinese: "披着羊皮的狼", category: "deception" },
        { id: 291, english: "actions speak louder than words", chinese: "事实胜于雄辩", category: "action" },
        { id: 292, english: "all ears", chinese: "洗耳恭听", category: "attention" },
        { id: 293, english: "all in the same boat", chinese: "同舟共济", category: "situation" },
        { id: 294, english: "all thumbs", chinese: "笨手笨脚", category: "clumsiness" },
        { id: 295, english: "an arm and a leg", chinese: "非常昂贵", category: "money" },
        { id: 296, english: "apple of my eye", chinese: "掌上明珠", category: "affection" },
        { id: 297, english: "as cool as a cucumber", chinese: "镇定自若", category: "calm" },
        { id: 298, english: "at the drop of a hat", chinese: "毫不犹豫", category: "readiness" },
        { id: 299, english: "back to square one", chinese: "从头开始", category: "restart" },
        { id: 300, english: "backhanded compliment", chinese: "明褒暗贬", category: "compliment" },
        { id: 301, english: "bad blood", chinese: "不和", category: "conflict" },
        { id: 302, english: "beating around the bush", chinese: "拐弯抹角", category: "communication" },
        { id: 303, english: "bend the truth", chinese: "歪曲事实", category: "deception" },
        { id: 304, english: "best of both worlds", chinese: "两全其美", category: "advantage" },
        { id: 305, english: "between a rock and a hard place", chinese: "进退两难", category: "dilemma" },
        { id: 306, english: "birds of a feather flock together", chinese: "物以类聚", category: "similarity" },
        { id: 307, english: "bite your tongue", chinese: "保持沉默", category: "silence" },
        { id: 308, english: "blood is thicker than water", chinese: "血浓于水", category: "family" },
        { id: 309, english: "blow off some steam", chinese: "发泄情绪", category: "emotion" },
        { id: 310, english: "born with a silver spoon in one's mouth", chinese: "含着金汤匙出生", category: "wealth" },
        { id: 311, english: "break the ice", chinese: "打破僵局", category: "social" },
        { id: 312, english: "bring home the bacon", chinese: "养家糊口", category: "work" },
        { id: 313, english: "burn bridges", chinese: "自断后路", category: "relationship" },
        { id: 314, english: "buy a pig in a poke", chinese: "盲目购买", category: "purchase" },
        { id: 315, english: "by the book", chinese: "按规矩办事", category: "procedure" },
        { id: 316, english: "call it quits", chinese: "放弃", category: "stop" },
        { id: 317, english: "can't stand the heat, get out of the kitchen", chinese: "受不了就离开", category: "tolerance" },
        { id: 318, english: "cast in stone", chinese: "一成不变", category: "permanence" },
        { id: 319, english: "cat got your tongue", chinese: "怎么不说话", category: "silence" },
        { id: 320, english: "catch someone red-handed", chinese: "当场抓获", category: "crime" },
        { id: 321, english: "change of heart", chinese: "改变主意", category: "change" },
        { id: 322, english: "chew the fat", chinese: "闲聊", category: "conversation" },
        { id: 323, english: "chicken out", chinese: "临阵退缩", category: "cowardice" },
        { id: 324, english: "clean slate", chinese: "重新开始", category: "fresh" },
        { id: 325, english: "clear the air", chinese: "消除误会", category: "communication" },
        { id: 326, english: "cold feet", chinese: "临阵退缩", category: "nervousness" },
        { id: 327, english: "come clean", chinese: "坦白", category: "honesty" },
        { id: 328, english: "cook the books", chinese: "做假账", category: "fraud" },
        { id: 329, english: "cool as a cucumber", chinese: "镇定自若", category: "calm" },
        { id: 330, english: "copycat", chinese: "模仿者", category: "imitation" },
        { id: 331, english: "count your blessings", chinese: "知足常乐", category: "gratitude" },
        { id: 332, english: "cover someone's back", chinese: "为某人撑腰", category: "support" },
        { id: 333, english: "crack down on", chinese: "严厉打击", category: "enforcement" },
        { id: 334, english: "cream of the crop", chinese: "精英", category: "quality" },
        { id: 335, english: "crocodile tears", chinese: "假慈悲", category: "deception" },
        { id: 336, english: "cry over spilled milk", chinese: "为无法挽回的事后悔", category: "regret" },
        { id: 337, english: "cut to the chase", chinese: "直奔主题", category: "communication" },
        { id: 338, english: "dark horse", chinese: "黑马", category: "surprise" },
        { id: 339, english: "dead as a doornail", chinese: "死透了", category: "death" },
        { id: 340, english: "devil's advocate", chinese: "唱反调的人", category: "argument" },
        { id: 341, english: "die hard", chinese: "顽固不化", category: "persistence" },
        { id: 342, english: "do the trick", chinese: "起作用", category: "effectiveness" },
        { id: 343, english: "don't bite the hand that feeds you", chinese: "不要恩将仇报", category: "gratitude" },
        { id: 344, english: "don't hold your breath", chinese: "别抱太大希望", category: "expectation" },
        { id: 345, english: "don't judge a book by its cover", chinese: "不要以貌取人", category: "judgment" },
        { id: 346, english: "don't rock the boat", chinese: "不要惹事", category: "caution" },
        { id: 347, english: "down in the dumps", chinese: "情绪低落", category: "sadness" },
        { id: 348, english: "down to earth", chinese: "脚踏实地", category: "personality" },
        { id: 349, english: "drag your feet", chinese: "拖延", category: "procrastination" },
        { id: 350, english: "draw the line", chinese: "划定界限", category: "boundary" }
    ]
};
