var proverbsData = {
    proverbs: [
        { id: 1, english: "A friend in need is a friend indeed.", chinese: "患难见真情。", category: "friendship" },
        { id: 2, english: "Actions speak louder than words.", chinese: "事实胜于雄辩。", category: "action" },
        { id: 3, english: "All that glitters is not gold.", chinese: "闪光的不一定是金子。", category: "appearance" },
        { id: 4, english: "A picture is worth a thousand words.", chinese: "一图胜千言。", category: "communication" },
        { id: 5, english: "Better late than never.", chinese: "迟做总比不做好。", category: "time" },
        { id: 6, english: "Birds of a feather flock together.", chinese: "物以类聚，人以群分。", category: "friendship" },
        { id: 7, english: "Blood is thicker than water.", chinese: "血浓于水。", category: "family" },
        { id: 8, english: "Don't count your chickens before they hatch.", chinese: "不要过早乐观。", category: "planning" },
        { id: 9, english: "Don't put all your eggs in one basket.", chinese: "不要孤注一掷。", category: "planning" },
        { id: 10, english: "Early to bed and early to rise makes a man healthy, wealthy and wise.", chinese: "早睡早起使人健康、富有和聪明。", category: "health" },
        { id: 11, english: "Easy come, easy go.", chinese: "来得容易去得快。", category: "money" },
        { id: 12, english: "Every cloud has a silver lining.", chinese: "黑暗中总有一线光明。", category: "optimism" },
        { id: 13, english: "Every dog has its day.", chinese: "人人都有得意时。", category: "opportunity" },
        { id: 14, english: "Failure is the mother of success.", chinese: "失败是成功之母。", category: "success" },
        { id: 15, english: "God helps those who help themselves.", chinese: "天助自助者。", category: "effort" },
        { id: 16, english: "Good things come to those who wait.", chinese: "好事多磨。", category: "patience" },
        { id: 17, english: "Haste makes waste.", chinese: "欲速则不达。", category: "patience" },
        { id: 18, english: "Health is wealth.", chinese: "健康就是财富。", category: "health" },
        { id: 19, english: "Honesty is the best policy.", chinese: "诚实是上策。", category: "honesty" },
        { id: 20, english: "If you want a thing done well, do it yourself.", chinese: "求人不如求己。", category: "effort" },
        { id: 21, english: "It never rains but it pours.", chinese: "祸不单行。", category: "misfortune" },
        { id: 22, english: "Knowledge is power.", chinese: "知识就是力量。", category: "knowledge" },
        { id: 23, english: "Laughter is the best medicine.", chinese: "笑是最好的良药。", category: "health" },
        { id: 24, english: "Learn from yesterday, live for today, hope for tomorrow.", chinese: "从昨天学习，为今天而活，为明天希望。", category: "life" },
        { id: 25, english: "Let sleeping dogs lie.", chinese: "不要惹是生非。", category: "conflict" },
        { id: 26, english: "Life is what you make it.", chinese: "生活是由你自己创造的。", category: "life" },
        { id: 27, english: "Look before you leap.", chinese: "三思而后行。", category: "planning" },
        { id: 28, english: "Love me, love my dog.", chinese: "爱屋及乌。", category: "love" },
        { id: 29, english: "Many hands make light work.", chinese: "众人拾柴火焰高。", category: "teamwork" },
        { id: 30, english: "Money doesn't grow on trees.", chinese: "钱不是大风刮来的。", category: "money" },
        { id: 31, english: "Necessity is the mother of invention.", chinese: "需要是发明之母。", category: "innovation" },
        { id: 32, english: "Never judge a book by its cover.", chinese: "不要以貌取人。", category: "appearance" },
        { id: 33, english: "No pain, no gain.", chinese: "一分耕耘，一分收获。", category: "effort" },
        { id: 34, english: "Old habits die hard.", chinese: "江山易改，本性难移。", category: "habit" },
        { id: 35, english: "Once bitten, twice shy.", chinese: "一朝被蛇咬，十年怕井绳。", category: "experience" },
        { id: 36, english: "One man's trash is another man's treasure.", chinese: "一个人的垃圾是另一个人的宝藏。", category: "value" },
        { id: 37, english: "Practice makes perfect.", chinese: "熟能生巧。", category: "learning" },
        { id: 38, english: "Rome was not built in a day.", chinese: "罗马不是一天建成的。", category: "patience" },
        { id: 39, english: "Seeing is believing.", chinese: "眼见为实。", category: "truth" },
        { id: 40, english: "Silence is golden.", chinese: "沉默是金。", category: "communication" },
        { id: 41, english: "The early bird catches the worm.", chinese: "早起的鸟儿有虫吃。", category: "opportunity" },
        { id: 42, english: "The pen is mightier than the sword.", chinese: "笔杆子比枪杆子更有力量。", category: "power" },
        { id: 43, english: "Time is money.", chinese: "时间就是金钱。", category: "time" },
        { id: 44, english: "Time heals all wounds.", chinese: "时间能治愈一切创伤。", category: "healing" },
        { id: 45, english: "Two heads are better than one.", chinese: "三个臭皮匠，顶个诸葛亮。", category: "teamwork" },
        { id: 46, english: "United we stand, divided we fall.", chinese: "团结则存，分裂则亡。", category: "unity" },
        { id: 47, english: "Variety is the spice of life.", chinese: "变化是生活的调味品。", category: "life" },
        { id: 48, english: "When in Rome, do as the Romans do.", chinese: "入乡随俗。", category: "culture" },
        { id: 49, english: "Where there's a will, there's a way.", chinese: "有志者事竟成。", category: "willpower" },
        { id: 50, english: "You can't have your cake and eat it too.", chinese: "鱼和熊掌不可兼得。", category: "choice" },
        { id: 51, english: "You reap what you sow.", chinese: "种瓜得瓜，种豆得豆。", category: "consequence" },
        { id: 52, english: "A rolling stone gathers no moss.", chinese: "流水不腐，户枢不蠹。", category: "change" },
        { id: 53, english: "Absence makes the heart grow fonder.", chinese: "小别胜新婚。", category: "love" },
        { id: 54, english: "An apple a day keeps the doctor away.", chinese: "一天一苹果，医生远离我。", category: "health" },
        { id: 55, english: "Beauty is in the eye of the beholder.", chinese: "情人眼里出西施。", category: "beauty" },
        { id: 56, english: "Beggars can't be choosers.", chinese: "乞丐不能挑肥拣瘦。", category: "choice" },
        { id: 57, english: "Better safe than sorry.", chinese: "小心驶得万年船。", category: "caution" },
        { id: 58, english: "Cleanliness is next to godliness.", chinese: "清洁近乎神圣。", category: "cleanliness" },
        { id: 59, english: "Don't bite the hand that feeds you.", chinese: "不要恩将仇报。", category: "gratitude" },
        { id: 60, english: "Don't judge a man until you've walked a mile in his shoes.", chinese: "设身处地为他人着想。", category: "empathy" },
        { id: 61, english: "Every man has his price.", chinese: "人人都有价码。", category: "humanity" },
        { id: 62, english: "Fortune favors the bold.", chinese: "勇者得天助。", category: "courage" },
        { id: 63, english: "Give a man a fish, and you feed him for a day. Teach a man to fish, and you feed him for a lifetime.", chinese: "授人以鱼不如授人以渔。", category: "teaching" },
        { id: 64, english: "Good fences make good neighbors.", chinese: "好篱笆造就好邻居。", category: "relationship" },
        { id: 65, english: "Home is where the heart is.", chinese: "心在哪里，家就在哪里。", category: "home" },
        { id: 66, english: "If it ain't broke, don't fix it.", chinese: "没坏就别修。", category: "change" },
        { id: 67, english: "It takes two to tango.", chinese: "一个巴掌拍不响。", category: "relationship" },
        { id: 68, english: "Kill two birds with one stone.", chinese: "一石二鸟。", category: "efficiency" },
        { id: 69, english: "Knowledge comes from experience.", chinese: "知识来源于经验。", category: "knowledge" },
        { id: 70, english: "Live and let live.", chinese: "自己活也让别人活。", category: "tolerance" },
        { id: 71, english: "Make hay while the sun shines.", chinese: "趁热打铁。", category: "opportunity" },
        { id: 72, english: "Money can't buy happiness.", chinese: "金钱买不到幸福。", category: "happiness" },
        { id: 73, english: "Nothing ventured, nothing gained.", chinese: "不入虎穴，焉得虎子。", category: "risk" },
        { id: 74, english: "Out of sight, out of mind.", chinese: "眼不见，心不烦。", category: "memory" },
        { id: 75, english: "People who live in glass houses shouldn't throw stones.", chinese: "自己有弱点就不要攻击别人。", category: "hypocrisy" },
        { id: 76, english: "Slow and steady wins the race.", chinese: "稳扎稳打，无往不胜。", category: "patience" },
        { id: 77, english: "Still waters run deep.", chinese: "静水流深。", category: "personality" },
        { id: 78, english: "The apple doesn't fall far from the tree.", chinese: "有其父必有其子。", category: "family" },
        { id: 79, english: "The grass is always greener on the other side.", chinese: "这山望着那山高。", category: "contentment" },
        { id: 80, english: "The proof of the pudding is in the eating.", chinese: "实践出真知。", category: "experience" },
        { id: 81, english: "There's no place like home.", chinese: "金窝银窝不如自己的狗窝。", category: "home" },
        { id: 82, english: "Too many cooks spoil the broth.", chinese: "人多手杂反而坏事。", category: "teamwork" },
        { id: 83, english: "Two wrongs don't make a right.", chinese: "两个错误不等于一个正确。", category: "justice" },
        { id: 84, english: "When the going gets tough, the tough get going.", chinese: "艰难困苦，玉汝于成。", category: "perseverance" },
        { id: 85, english: "Where there's smoke, there's fire.", chinese: "无风不起浪。", category: "truth" },
        { id: 86, english: "You can lead a horse to water, but you can't make it drink.", chinese: "你可以带马到河边，但不能强迫它喝水。", category: "willpower" },
        { id: 87, english: "You can't teach an old dog new tricks.", chinese: "老狗学不会新把戏。", category: "change" },
        { id: 88, english: "A bird in the hand is worth two in the bush.", chinese: "一鸟在手胜过双鸟在林。", category: "choice" },
        { id: 89, english: "A stitch in time saves nine.", chinese: "小洞不补，大洞吃苦。", category: "prevention" },
        { id: 90, english: "All good things come to an end.", chinese: "天下没有不散的筵席。", category: "ending" },
        { id: 91, english: "An ounce of prevention is worth a pound of cure.", chinese: "预防胜于治疗。", category: "prevention" },
        { id: 92, english: "Curiosity killed the cat.", chinese: "好奇害死猫。", category: "curiosity" },
        { id: 93, english: "Don't burn your bridges.", chinese: "不要自断后路。", category: "planning" },
        { id: 94, english: "Don't cry over spilt milk.", chinese: "覆水难收，后悔无益。", category: "regret" },
        { id: 95, english: "Every rose has its thorn.", chinese: "每朵玫瑰都有刺。", category: "reality" },
        { id: 96, english: "First things first.", chinese: "要事优先。", category: "priority" },
        { id: 97, english: "Great minds think alike.", chinese: "英雄所见略同。", category: "agreement" },
        { id: 98, english: "Hope for the best, prepare for the worst.", chinese: "抱最好的希望，做最坏的打算。", category: "planning" },
        { id: 99, english: "If you can't beat them, join them.", chinese: "打不过就加入。", category: "strategy" },
        { id: 100, english: "It's no use crying over spilt milk.", chinese: "覆水难收。", category: "regret" },
        { id: 101, english: "A closed mouth catches no flies.", chinese: "祸从口出。", category: "caution" },
        { id: 102, english: "A drowning man will clutch at a straw.", chinese: "病急乱投医。", category: "desperation" },
        { id: 103, english: "A man is known by the company he keeps.", chinese: "观其友知其人。", category: "friendship" },
        { id: 104, english: "A miss is as good as a mile.", chinese: "差之毫厘，谬以千里。", category: "precision" },
        { id: 105, english: "A new broom sweeps clean.", chinese: "新官上任三把火。", category: "change" },
        { id: 106, english: "A soft answer turns away wrath.", chinese: "婉言可以息怒。", category: "communication" },
        { id: 107, english: "A word to the wise is enough.", chinese: "智者一言足矣。", category: "wisdom" },
        { id: 108, english: "All's well that ends well.", chinese: "结果好就是好。", category: "outcome" },
        { id: 109, english: "An idle brain is the devil's workshop.", chinese: "游手好闲是万恶之源。", category: "work" },
        { id: 110, english: "As you sow, so shall you reap.", chinese: "种瓜得瓜，种豆得豆。", category: "consequence" },
        { id: 111, english: "Be just before you are generous.", chinese: "先公正后慷慨。", category: "justice" },
        { id: 112, english: "Beauty is only skin deep.", chinese: "美貌只是皮相。", category: "beauty" },
        { id: 113, english: "Behind every successful man there is a woman.", chinese: "每个成功男人的背后都有一个女人。", category: "success" },
        { id: 114, english: "Better the devil you know than the devil you don't.", chinese: "已知的危险胜过未知的危险。", category: "choice" },
        { id: 115, english: "Beware of little expenses.", chinese: "小钱积大祸。", category: "money" },
        { id: 116, english: "Charity begins at home.", chinese: "仁爱始于家。", category: "charity" },
        { id: 117, english: "Constant dripping wears away the stone.", chinese: "滴水穿石。", category: "perseverance" },
        { id: 118, english: "Content is better than riches.", chinese: "知足常乐。", category: "contentment" },
        { id: 119, english: "Dead men tell no tales.", chinese: "死人不会说话。", category: "secrecy" },
        { id: 120, english: "Diamonds cut diamonds.", chinese: "棋逢对手。", category: "competition" },
        { id: 121, english: "Do as I say, not as I do.", chinese: "照我说的做，别照我做的做。", category: "hypocrisy" },
        { id: 122, english: "Do unto others as you would have them do unto you.", chinese: "己所不欲，勿施于人。", category: "ethics" },
        { id: 123, english: "Dogs that put up many hares kill none.", chinese: "贪多嚼不烂。", category: "focus" },
        { id: 124, english: "Don't cross the bridge till you get to it.", chinese: "船到桥头自然直。", category: "worry" },
        { id: 125, english: "Don't speak to the man at the wheel.", chinese: "不要干扰负责的人。", category: "interference" },
        { id: 126, english: "Doubt is the beginning of wisdom.", chinese: "怀疑是智慧的开端。", category: "wisdom" },
        { id: 127, english: "Enough is as good as a feast.", chinese: "知足常乐。", category: "contentment" },
        { id: 128, english: "Even a worm will turn.", chinese: "兔子急了也咬人。", category: "patience" },
        { id: 129, english: "Every bullet has its billet.", chinese: "生死有命。", category: "fate" },
        { id: 130, english: "Every man for himself.", chinese: "人人为己。", category: "selfishness" },
        { id: 131, english: "Every man has his faults.", chinese: "人无完人。", category: "humanity" },
        { id: 132, english: "Experience is the best teacher.", chinese: "经验是最好的老师。", category: "learning" },
        { id: 133, english: "Faint heart never won fair lady.", chinese: "胆小鬼得不到美人。", category: "courage" },
        { id: 134, english: "Faith will move mountains.", chinese: "信念可以移山。", category: "faith" },
        { id: 135, english: "Familiarity breeds contempt.", chinese: "熟悉生轻视。", category: "relationship" },
        { id: 136, english: "Fine feathers make fine birds.", chinese: "人靠衣装。", category: "appearance" },
        { id: 137, english: "Fine words butter no parsnips.", chinese: "空话无济于事。", category: "action" },
        { id: 138, english: "Fire is a good servant but a bad master.", chinese: "火是好的仆人，却是坏的主人。", category: "control" },
        { id: 139, english: "First come, first served.", chinese: "先到先得。", category: "fairness" },
        { id: 140, english: "Fish begins to stink at the head.", chinese: "上梁不正下梁歪。", category: "leadership" },
        { id: 141, english: "Forbidden fruit is sweet.", chinese: "禁果最甜。", category: "temptation" },
        { id: 142, english: "Give credit where credit is due.", chinese: "该表扬时就表扬。", category: "recognition" },
        { id: 143, english: "Go the whole hog or none.", chinese: "要么全做，要么不做。", category: "commitment" },
        { id: 144, english: "Good wine needs no bush.", chinese: "好酒不怕巷子深。", category: "quality" },
        { id: 145, english: "Grasp all, lose all.", chinese: "贪多必失。", category: "greed" },
        { id: 146, english: "Great talkers are little doers.", chinese: "说的多做的少。", category: "action" },
        { id: 147, english: "Half a loaf is better than no bread.", chinese: "有总比没有好。", category: "compromise" },
        { id: 148, english: "Handsome is as handsome does.", chinese: "行为美才是真美。", category: "character" },
        { id: 149, english: "Happy is the bride that the sun shines on.", chinese: "阳光照耀的新娘最幸福。", category: "marriage" },
        { id: 150, english: "Hard words break no bones.", chinese: "恶语伤不到人。", category: "words" },
        { id: 151, english: "Horses for courses.", chinese: "人尽其才。", category: "suitability" },
        { id: 152, english: "Idle hands are the devil's workshop.", chinese: "游手好闲是万恶之源。", category: "work" },
        { id: 153, english: "If a job is worth doing, it is worth doing well.", chinese: "值得做的事就值得做好。", category: "quality" },
        { id: 154, english: "If at first you don't succeed, try, try again.", chinese: "失败是成功之母。", category: "perseverance" },
        { id: 155, english: "If the mountain will not come to Muhammad, then Muhammad must go to the mountain.", chinese: "山不就我，我往就山。", category: "adaptation" },
        { id: 156, english: "If wishes were horses, beggars would ride.", chinese: "如果愿望是马，乞丐也能骑。", category: "reality" },
        { id: 157, english: "Imitation is the sincerest form of flattery.", chinese: "模仿是最真诚的恭维。", category: "flattery" },
        { id: 158, english: "In for a penny, in for a pound.", chinese: "一不做，二不休。", category: "commitment" },
        { id: 159, english: "It takes all sorts to make a world.", chinese: "大千世界，无奇不有。", category: "diversity" },
        { id: 160, english: "It's a long lane that has no turning.", chinese: "路必有弯，事必有变。", category: "change" },
        { id: 161, english: "It's an ill wind that blows nobody good.", chinese: "坏事也有好的一面。", category: "optimism" },
        { id: 162, english: "It's no use locking the stable door after the horse has bolted.", chinese: "亡羊补牢，为时已晚。", category: "prevention" },
        { id: 163, english: "Jack of all trades, master of none.", chinese: "样样通，样样松。", category: "skill" },
        { id: 164, english: "Keep your friends close and your enemies closer.", chinese: "近敌者智。", category: "strategy" },
        { id: 165, english: "Keep your mouth shut and your eyes open.", chinese: "多看少说。", category: "caution" },
        { id: 166, english: "Laugh and the world laughs with you, weep and you weep alone.", chinese: "欢笑世界同乐，哭泣独自悲伤。", category: "emotion" },
        { id: 167, english: "Learn to walk before you run.", chinese: "先学走，再学跑。", category: "learning" },
        { id: 168, english: "Least said, soonest mended.", chinese: "少说为妙。", category: "communication" },
        { id: 169, english: "Let bygones be bygones.", chinese: "过去的事就让它过去吧。", category: "forgiveness" },
        { id: 170, english: "Life is not a bed of roses.", chinese: "生活并非一帆风顺。", category: "reality" },
        { id: 171, english: "Life is not all beer and skittles.", chinese: "人生并非尽是乐事。", category: "reality" },
        { id: 172, english: "Lightning never strikes twice in the same place.", chinese: "祸不重至。", category: "fortune" },
        { id: 173, english: "Little knowledge is a dangerous thing.", chinese: "一知半解是危险的。", category: "knowledge" },
        { id: 174, english: "Little strokes fell great oaks.", chinese: "滴水穿石。", category: "perseverance" },
        { id: 175, english: "Little things please little minds.", chinese: "小人无大志。", category: "character" },
        { id: 176, english: "Live not to eat, but eat to live.", chinese: "活着不是为了吃，吃是为了活着。", category: "life" },
        { id: 177, english: "Long absent, soon forgotten.", chinese: "别久情疏。", category: "memory" },
        { id: 178, english: "Love is blind.", chinese: "爱情是盲目的。", category: "love" },
        { id: 179, english: "Make the best of a bad job.", chinese: "善处逆境。", category: "attitude" },
        { id: 180, english: "Man does not live by bread alone.", chinese: "人不仅靠面包生活。", category: "life" },
        { id: 181, english: "Man proposes, God disposes.", chinese: "谋事在人，成事在天。", category: "fate" },
        { id: 182, english: "Manners maketh man.", chinese: "礼仪造就人。", category: "manners" },
        { id: 183, english: "Many a little makes a mickle.", chinese: "积少成多。", category: "accumulation" },
        { id: 184, english: "Many hands make light work.", chinese: "人多力量大。", category: "teamwork" },
        { id: 185, english: "Marry in haste, repent at leisure.", chinese: "草率结婚，后悔莫及。", category: "marriage" },
        { id: 186, english: "Might is right.", chinese: "强权即公理。", category: "power" },
        { id: 187, english: "Milk and honey.", chinese: "富饶之地。", category: "prosperity" },
        { id: 188, english: "Money begets money.", chinese: "钱生钱。", category: "money" },
        { id: 189, english: "Money is the root of all evil.", chinese: "金钱是万恶之源。", category: "money" },
        { id: 190, english: "Money makes the mare go.", chinese: "有钱能使鬼推磨。", category: "money" },
        { id: 191, english: "More haste, less speed.", chinese: "欲速则不达。", category: "patience" },
        { id: 192, english: "Music has charms to soothe the savage breast.", chinese: "音乐能抚慰野蛮的心灵。", category: "music" },
        { id: 193, english: "Nature abhors a vacuum.", chinese: "自然界厌恶真空。", category: "nature" },
        { id: 194, english: "Necessity knows no law.", chinese: "需要面前无法律。", category: "necessity" },
        { id: 195, english: "Never look a gift horse in the mouth.", chinese: "不要对礼物吹毛求疵。", category: "gratitude" },
        { id: 196, english: "Never put off till tomorrow what you can do today.", chinese: "今日事今日毕。", category: "procrastination" },
        { id: 197, english: "Never say die.", chinese: "永不言弃。", category: "perseverance" },
        { id: 198, english: "Never speak ill of the dead.", chinese: "死者为大。", category: "respect" },
        { id: 199, english: "No gain without pain.", chinese: "不劳无获。", category: "effort" },
        { id: 200, english: "No man can serve two masters.", chinese: "一仆不能事二主。", category: "loyalty" },
        { id: 201, english: "No man is an island.", chinese: "没有人是一座孤岛。", category: "connection" },
        { id: 202, english: "No news is good news.", chinese: "没有消息就是好消息。", category: "optimism" },
        { id: 203, english: "No smoke without fire.", chinese: "无风不起浪。", category: "truth" },
        { id: 204, english: "Nobody is perfect.", chinese: "人无完人。", category: "humanity" },
        { id: 205, english: "Nothing is certain but death and taxes.", chinese: "只有死亡和税收是确定的。", category: "certainty" },
        { id: 206, english: "Nothing succeeds like success.", chinese: "一事成功，事事顺利。", category: "success" },
        { id: 207, english: "Oil and water don't mix.", chinese: "水火不容。", category: "incompatibility" },
        { id: 208, english: "Old friends and old wine are best.", chinese: "陈酒味醇，老友情深。", category: "friendship" },
        { id: 209, english: "One good turn deserves another.", chinese: "善有善报。", category: "kindness" },
        { id: 210, english: "One man's meat is another man's poison.", chinese: "甲之蜜糖，乙之砒霜。", category: "preference" },
        { id: 211, english: "One swallow does not make a summer.", chinese: "一燕不成夏。", category: "caution" },
        { id: 212, english: "Opportunity seldom knocks twice.", chinese: "机不可失，时不再来。", category: "opportunity" },
        { id: 213, english: "Opposites attract.", chinese: "异性相吸。", category: "attraction" },
        { id: 214, english: "Penny wise and pound foolish.", chinese: "小事精明，大事糊涂。", category: "wisdom" },
        { id: 215, english: "People in glass houses shouldn't throw stones.", chinese: "自己有弱点就不要攻击别人。", category: "hypocrisy" },
        { id: 216, english: "Pleasure has a sting in its tail.", chinese: "乐极生悲。", category: "pleasure" },
        { id: 217, english: "Possession is nine-tenths of the law.", chinese: "占有即所有。", category: "ownership" },
        { id: 218, english: "Power corrupts; absolute power corrupts absolutely.", chinese: "权力导致腐败，绝对权力导致绝对腐败。", category: "power" },
        { id: 219, english: "Prevention is better than cure.", chinese: "预防胜于治疗。", category: "prevention" },
        { id: 220, english: "Pride comes before a fall.", chinese: "骄兵必败。", category: "pride" },
        { id: 221, english: "Procrastination is the thief of time.", chinese: "拖延是时间之贼。", category: "procrastination" },
        { id: 222, english: "Promise is debt.", chinese: "一诺千金。", category: "promise" },
        { id: 223, english: "Prosperity makes friends, adversity tries them.", chinese: "富贵交友易，患难见真情。", category: "friendship" },
        { id: 224, english: "Put the cart before the horse.", chinese: "本末倒置。", category: "order" },
        { id: 225, english: "Rain before seven, fine before eleven.", chinese: "七点前下雨，十一点前放晴。", category: "weather" },
        { id: 226, english: "Rats desert a sinking ship.", chinese: "树倒猢狲散。", category: "loyalty" },
        { id: 227, english: "Revenge is a dish best served cold.", chinese: "君子报仇，十年不晚。", category: "revenge" },
        { id: 228, english: "Revenge is sweet.", chinese: "复仇是甜美的。", category: "revenge" },
        { id: 229, english: "Riches have wings.", chinese: "财富易逝。", category: "money" },
        { id: 230, english: "Save for a rainy day.", chinese: "未雨绸缪。", category: "planning" },
        { id: 231, english: "Self-help is the best help.", chinese: "自助者天助。", category: "self-reliance" },
        { id: 232, english: "Set a thief to catch a thief.", chinese: "以贼捕贼。", category: "strategy" },
        { id: 233, english: "Silence gives consent.", chinese: "沉默即同意。", category: "consent" },
        { id: 234, english: "Spare the rod and spoil the child.", chinese: "不打不成器。", category: "discipline" },
        { id: 235, english: "Speak of the devil and he appears.", chinese: "说曹操，曹操到。", category: "coincidence" },
        { id: 236, english: "Speech is silver, silence is golden.", chinese: "雄辩是银，沉默是金。", category: "communication" },
        { id: 237, english: "Sticks and stones may break my bones, but words will never hurt me.", chinese: "棍棒伤身，言语不伤人。", category: "words" },
        { id: 238, english: "Strike while the iron is hot.", chinese: "趁热打铁。", category: "opportunity" },
        { id: 239, english: "Success has many fathers, while failure is an orphan.", chinese: "成功有许多父亲，失败却是孤儿。", category: "success" },
        { id: 240, english: "Take care of the pence and the pounds will take care of themselves.", chinese: "积少成多。", category: "money" },
        { id: 241, english: "Talk of the devil, and he is sure to appear.", chinese: "说曹操，曹操到。", category: "coincidence" },
        { id: 242, english: "Tastes differ.", chinese: "人各有所好。", category: "preference" },
        { id: 243, english: "Tell me who your friends are and I'll tell you who you are.", chinese: "观其友知其人。", category: "friendship" },
        { id: 244, english: "That which does not kill us makes us stronger.", chinese: "那些杀不死我们的，让我们更强大。", category: "strength" },
        { id: 245, english: "The best things in life are free.", chinese: "人生最美好的东西是免费的。", category: "value" },
        { id: 246, english: "The darkest hour is just before the dawn.", chinese: "黎明前最黑暗。", category: "optimism" },
        { id: 247, english: "The devil finds work for idle hands.", chinese: "游手好闲是万恶之源。", category: "work" },
        { id: 248, english: "The early bird catches the worm.", chinese: "早起的鸟儿有虫吃。", category: "opportunity" },
        { id: 249, english: "The end justifies the means.", chinese: "目的证明手段正确。", category: "ethics" },
        { id: 250, english: "The exception proves the rule.", chinese: "例外证明规则。", category: "rules" },
        { id: 251, english: "The first step is the hardest.", chinese: "万事开头难。", category: "beginning" },
        { id: 252, english: "The love of money is the root of all evil.", chinese: "贪财是万恶之源。", category: "money" },
        { id: 253, english: "The more you have, the more you want.", chinese: "越有越贪。", category: "greed" },
        { id: 254, english: "The onlooker sees most of the game.", chinese: "旁观者清。", category: "perspective" },
        { id: 255, english: "The pot calling the kettle black.", chinese: "五十步笑百步。", category: "hypocrisy" },
        { id: 256, english: "The road to hell is paved with good intentions.", chinese: "好心办坏事。", category: "intentions" },
        { id: 257, english: "The spirit is willing but the flesh is weak.", chinese: "心有余而力不足。", category: "weakness" },
        { id: 258, english: "The squeaky wheel gets the grease.", chinese: "会哭的孩子有奶吃。", category: "assertiveness" },
        { id: 259, english: "The way to a man's heart is through his stomach.", chinese: "要抓住男人的心，先抓住他的胃。", category: "love" },
        { id: 260, english: "There are none so blind as those who will not see.", chinese: "视而不见者最盲。", category: "ignorance" },
        { id: 261, english: "There is a time and a place for everything.", chinese: "凡事皆有时。", category: "timing" },
        { id: 262, english: "There is honor among thieves.", chinese: "盗亦有道。", category: "honor" },
        { id: 263, english: "There is no accounting for taste.", chinese: "人各有所好。", category: "preference" },
        { id: 264, english: "There is no fool like an old fool.", chinese: "老糊涂最糊涂。", category: "foolishness" },
        { id: 265, english: "There is no place like home.", chinese: "金窝银窝不如自己的狗窝。", category: "home" },
        { id: 266, english: "There is no smoke without fire.", chinese: "无风不起浪。", category: "truth" },
        { id: 267, english: "There's a sucker born every minute.", chinese: "每分钟都有一个傻瓜出生。", category: "gullibility" },
        { id: 268, english: "There's always someone worse off than yourself.", chinese: "比上不足，比下有余。", category: "perspective" },
        { id: 269, english: "There's many a slip 'twixt cup and lip.", chinese: "功败垂成。", category: "uncertainty" },
        { id: 270, english: "There's more than one way to skin a cat.", chinese: "条条大路通罗马。", category: "alternatives" },
        { id: 271, english: "Third time lucky.", chinese: "事不过三。", category: "luck" },
        { id: 272, english: "Those who can, do; those who can't, teach.", chinese: "能者做，不能者教。", category: "ability" },
        { id: 273, english: "Those who live in glass houses shouldn't throw stones.", chinese: "自己有弱点就不要攻击别人。", category: "hypocrisy" },
        { id: 274, english: "Time and tide wait for no man.", chinese: "岁月不待人。", category: "time" },
        { id: 275, english: "Time flies when you're having fun.", chinese: "快乐时光过得快。", category: "time" },
        { id: 276, english: "Time heals all wounds.", chinese: "时间能治愈一切创伤。", category: "healing" },
        { id: 277, english: "Time is a great healer.", chinese: "时间是良药。", category: "healing" },
        { id: 278, english: "To err is human; to forgive, divine.", chinese: "犯错人皆难免，宽恕则属神圣。", category: "forgiveness" },
        { id: 279, english: "Tomorrow is another day.", chinese: "明天又是新的一天。", category: "optimism" },
        { id: 280, english: "Tomorrow never comes.", chinese: "明日复明日，明日何其多。", category: "procrastination" },
        { id: 281, english: "Too many cooks spoil the broth.", chinese: "人多手杂反而坏事。", category: "teamwork" },
        { id: 282, english: "Truth is stranger than fiction.", chinese: "真相比小说更离奇。", category: "truth" },
        { id: 283, english: "Two heads are better than one.", chinese: "三个臭皮匠，顶个诸葛亮。", category: "teamwork" },
        { id: 284, english: "Two is company, three is a crowd.", chinese: "两人成伴，三人不欢。", category: "relationship" },
        { id: 285, english: "Two wrongs don't make a right.", chinese: "以牙还牙不对。", category: "justice" },
        { id: 286, english: "Union is strength.", chinese: "团结就是力量。", category: "unity" },
        { id: 287, english: "Variety is the spice of life.", chinese: "变化是生活的调味品。", category: "variety" },
        { id: 288, english: "Virtue is its own reward.", chinese: "美德本身就是回报。", category: "virtue" },
        { id: 289, english: "Walls have ears.", chinese: "隔墙有耳。", category: "secrecy" },
        { id: 290, english: "Waste not, want not.", chinese: "不浪费，不缺乏。", category: "thrift" },
        { id: 291, english: "Well begun is half done.", chinese: "好的开始是成功的一半。", category: "beginning" },
        { id: 292, english: "What can't be cured must be endured.", chinese: "无法改变的事只能忍受。", category: "acceptance" },
        { id: 293, english: "What goes around comes around.", chinese: "善有善报，恶有恶报。", category: "karma" },
        { id: 294, english: "What goes up must come down.", chinese: "有起必有落。", category: "cycles" },
        { id: 295, english: "What the eye doesn't see, the heart doesn't grieve over.", chinese: "眼不见，心不烦。", category: "ignorance" },
        { id: 296, english: "What you don't know can't hurt you.", chinese: "不知者无罪。", category: "ignorance" },
        { id: 297, english: "Whatever will be, will be.", chinese: "顺其自然。", category: "acceptance" },
        { id: 298, english: "When the cat's away, the mice will play.", chinese: "山中无老虎，猴子称大王。", category: "opportunity" },
        { id: 299, english: "Where there's life, there's hope.", chinese: "留得青山在，不怕没柴烧。", category: "hope" },
        { id: 300, english: "Where there's muck, there's brass.", chinese: "脏活累活赚大钱。", category: "work" },
        { id: 301, english: "While there's life, there's hope.", chinese: "活着就有希望。", category: "hope" },
        { id: 302, english: "Who pays the piper calls the tune.", chinese: "出钱的人说了算。", category: "control" },
        { id: 303, english: "Winners never quit and quitters never win.", chinese: "胜者不弃，弃者不胜。", category: "perseverance" },
        { id: 304, english: "Wishes don't wash dishes.", chinese: "愿望不能当饭吃。", category: "reality" },
        { id: 305, english: "With age comes wisdom.", chinese: "年纪大，智慧多。", category: "wisdom" },
        { id: 306, english: "Women and children first.", chinese: "妇女儿童优先。", category: "priority" },
        { id: 307, english: "Work expands to fill the time available.", chinese: "工作会自动膨胀，占满所有可用的时间。", category: "work" },
        { id: 308, english: "Worrying never did anyone any good.", chinese: "担忧无益。", category: "worry" },
        { id: 309, english: "You are never too old to learn.", chinese: "活到老，学到老。", category: "learning" },
        { id: 310, english: "You are what you eat.", chinese: "人如其食。", category: "health" },
        { id: 311, english: "You can lead a horse to water, but you can't make it drink.", chinese: "你可以带马到河边，但不能强迫它喝水。", category: "willpower" },
        { id: 312, english: "You can't have your cake and eat it too.", chinese: "鱼和熊掌不可兼得。", category: "choice" },
        { id: 313, english: "You can't make an omelet without breaking eggs.", chinese: "有所得必有所失。", category: "sacrifice" },
        { id: 314, english: "You can't make bricks without straw.", chinese: "巧妇难为无米之炊。", category: "resources" },
        { id: 315, english: "You can't teach an old dog new tricks.", chinese: "老狗学不会新把戏。", category: "change" },
        { id: 316, english: "You can't tell a book by its cover.", chinese: "不能以貌取人。", category: "appearance" },
        { id: 317, english: "You have to crawl before you can walk.", chinese: "先学爬，再学走。", category: "learning" },
        { id: 318, english: "You never know what you've got till it's gone.", chinese: "失去了才知道珍惜。", category: "appreciation" },
        { id: 319, english: "You only live once.", chinese: "人生只有一次。", category: "life" },
        { id: 320, english: "You reap what you sow.", chinese: "种瓜得瓜，种豆得豆。", category: "consequence" },
        { id: 321, english: "Youth is wasted on the young.", chinese: "青春被年轻人浪费了。", category: "youth" },
        { id: 322, english: "A bad workman blames his tools.", chinese: "不会撑船怪河弯。", category: "responsibility" },
        { id: 323, english: "A bargain is a bargain.", chinese: "达成的协议不可更改。", category: "agreement" },
        { id: 324, english: "A chain is no stronger than its weakest link.", chinese: "链条的强度取决于最弱的一环。", category: "strength" },
        { id: 325, english: "A change is as good as a rest.", chinese: "改变和休息一样好。", category: "change" },
        { id: 326, english: "A constant guest is never welcome.", chinese: "常客不受欢迎。", category: "hospitality" },
        { id: 327, english: "A cracked bell can never sound well.", chinese: "破钟声音不亮。", category: "quality" },
        { id: 328, english: "A drowning man will catch at a straw.", chinese: "溺水者抓稻草。", category: "desperation" },
        { id: 329, english: "A fault confessed is half redressed.", chinese: "承认错误等于改正一半。", category: "mistake" },
        { id: 330, english: "A flower blooms more than once.", chinese: "花有重开日。", category: "opportunity" },
        { id: 331, english: "A fool and his money are soon parted.", chinese: "傻瓜的钱留不住。", category: "money" },
        { id: 332, english: "A fool may give a wise man counsel.", chinese: "愚者千虑，必有一得。", category: "wisdom" },
        { id: 333, english: "A friend to all is a friend to none.", chinese: "滥交者无友。", category: "friendship" },
        { id: 334, english: "A golden key can open any door.", chinese: "有钱能使鬼推磨。", category: "money" },
        { id: 335, english: "A good beginning makes a good ending.", chinese: "善始善终。", category: "beginning" },
        { id: 336, english: "A good conscience is a soft pillow.", chinese: "问心无愧，高枕无忧。", category: "conscience" },
        { id: 337, english: "A good example is the best sermon.", chinese: "身教重于言教。", category: "teaching" },
        { id: 338, english: "A good name is better than riches.", chinese: "名声胜过财富。", category: "reputation" },
        { id: 339, english: "A good wife makes a good husband.", chinese: "妻贤夫祸少。", category: "marriage" },
        { id: 340, english: "A great talker is a great liar.", chinese: "说大话者多谎言。", category: "honesty" },
        { id: 341, english: "A hedge between keeps friendship green.", chinese: "君子之交淡如水。", category: "friendship" },
        { id: 342, english: "A horse stumbles that has four legs.", chinese: "人非圣贤，孰能无过。", category: "mistake" },
        { id: 343, english: "A house divided against itself cannot stand.", chinese: "家不和，外人欺。", category: "unity" },
        { id: 344, english: "A hungry man is an angry man.", chinese: "饿汉易怒。", category: "need" },
        { id: 345, english: "A journey of a thousand miles begins with a single step.", chinese: "千里之行，始于足下。", category: "beginning" },
        { id: 346, english: "A king's chaff is worth more than other men's corn.", chinese: "王者的糠比凡人的谷值钱。", category: "value" },
        { id: 347, english: "A little knowledge is a dangerous thing.", chinese: "一知半解是危险的。", category: "knowledge" },
        { id: 348, english: "A little pot is soon hot.", chinese: "量小易怒。", category: "temper" },
        { id: 349, english: "A living dog is better than a dead lion.", chinese: "活狗胜过死狮。", category: "life" },
        { id: 350, english: "A man can die but once.", chinese: "人固有一死。", category: "death" },
        { id: 351, english: "A man is known by the company he keeps.", chinese: "观其友，知其人。", category: "friendship" },
        { id: 352, english: "A man of many talents.", chinese: "多才多艺的人。", category: "talent" },
        { id: 353, english: "A miss is as good as a mile.", chinese: "毫厘之差也是差。", category: "mistake" },
        { id: 354, english: "A new broom sweeps clean.", chinese: "新官上任三把火。", category: "change" },
        { id: 355, english: "A penny for your thoughts.", chinese: "你在想什么？", category: "communication" },
        { id: 356, english: "A penny saved is a penny earned.", chinese: "省一分就是赚一分。", category: "money" },
        { id: 357, english: "A quiet conscience sleeps in thunder.", chinese: "问心无愧，雷打不惊。", category: "conscience" },
        { id: 358, english: "A rolling stone gathers no moss.", chinese: "滚石不生苔。", category: "change" },
        { id: 359, english: "A soft answer turns away wrath.", chinese: "婉言可以息怒。", category: "communication" },
        { id: 360, english: "A sound mind in a sound body.", chinese: "健全的精神寓于健康的身体。", category: "health" },
        { id: 361, english: "A stitch in time saves nine.", chinese: "及时一针省九针。", category: "prevention" },
        { id: 362, english: "A storm in a teacup.", chinese: "小题大做。", category: "exaggeration" },
        { id: 363, english: "A straw shows which way the wind blows.", chinese: "见微知著。", category: "observation" },
        { id: 364, english: "A thing of beauty is a joy forever.", chinese: "美的事物是永恒的喜悦。", category: "beauty" },
        { id: 365, english: "A watched pot never boils.", chinese: "心急吃不了热豆腐。", category: "patience" },
        { id: 366, english: "A wise man changes his mind, a fool never will.", chinese: "智者通权达变，愚者刚愎自用。", category: "wisdom" },
        { id: 367, english: "A word to the wise is enough.", chinese: "智者一言足矣。", category: "wisdom" },
        { id: 368, english: "A word spoken is past recalling.", chinese: "一言既出，驷马难追。", category: "speech" },
        { id: 369, english: "Accidents will happen.", chinese: "意外难免发生。", category: "accident" },
        { id: 370, english: "Actions speak louder than words.", chinese: "行胜于言。", category: "action" },
        { id: 371, english: "Adversity is a good discipline.", chinese: "逆境是良师。", category: "adversity" },
        { id: 372, english: "Adversity makes strange bedfellows.", chinese: "逆境使人结成奇怪的伙伴。", category: "adversity" },
        { id: 373, english: "Advice is cheap.", chinese: "忠告不值钱。", category: "advice" },
        { id: 374, english: "Advice is least heeded when most needed.", chinese: "最需要忠告时，最听不进去。", category: "advice" },
        { id: 375, english: "After a storm comes a calm.", chinese: "风暴过后是平静。", category: "calm" },
        { id: 376, english: "After dinner sit a while; after supper walk a mile.", chinese: "午餐后坐坐，晚餐后走走。", category: "health" },
        { id: 377, english: "After meat, mustard.", chinese: "雨后送伞。", category: "timing" },
        { id: 378, english: "All are not friends that speak us fair.", chinese: "说好话的不都是朋友。", category: "friendship" },
        { id: 379, english: "All are not hunters that blow the horn.", chinese: "吹号角的不都是猎人。", category: "deception" },
        { id: 380, english: "All covet, all lose.", chinese: "贪多必失。", category: "greed" },
        { id: 381, english: "All good things come to an end.", chinese: "天下无不散之筵席。", category: "ending" },
        { id: 382, english: "All is fair in love and war.", chinese: "情场战场，不择手段。", category: "love" },
        { id: 383, english: "All is fish that comes to the net.", chinese: "进网的都是鱼。", category: "opportunity" },
        { id: 384, english: "All is not gold that glitters.", chinese: "发光的不都是金子。", category: "appearance" },
        { id: 385, english: "All is well that ends well.", chinese: "结果好就是好。", category: "ending" },
        { id: 386, english: "All roads lead to Rome.", chinese: "条条大路通罗马。", category: "method" },
        { id: 387, english: "All that glitters is not gold.", chinese: "闪闪发光的不一定是金子。", category: "appearance" },
        { id: 388, english: "All things are difficult before they are easy.", chinese: "万事开头难。", category: "difficulty" },
        { id: 389, english: "All things come to him who waits.", chinese: "耐心等待，终有所得。", category: "patience" },
        { id: 390, english: "All work and no play makes Jack a dull boy.", chinese: "只工作不玩耍，聪明孩子也变傻。", category: "balance" },
        { id: 391, english: "Almost never killed a fly.", chinese: "差不多就行。", category: "perfection" },
        { id: 392, english: "Among the blind the one-eyed man is king.", chinese: "盲人国里，独眼为王。", category: "comparison" },
        { id: 393, english: "An apple a day keeps the doctor away.", chinese: "一天一苹果，医生远离我。", category: "health" },
        { id: 394, english: "An army marches on its stomach.", chinese: "兵马未动，粮草先行。", category: "preparation" },
        { id: 395, english: "An ass is but an ass, though laden with gold.", chinese: "驴子驮金仍是驴。", category: "nature" },
        { id: 396, english: "An empty barrel makes more noise.", chinese: "空桶响声大。", category: "emptiness" },
        { id: 397, english: "An empty sack cannot stand upright.", chinese: "空袋子站不直。", category: "emptiness" },
        { id: 398, english: "An enemy's mouth seldom speaks well.", chinese: "敌人嘴里没好话。", category: "enemy" },
        { id: 399, english: "An Englishman's home is his castle.", chinese: "英国人的家是城堡。", category: "privacy" },
        { id: 400, english: "An eye for an eye, a tooth for a tooth.", chinese: "以眼还眼，以牙还牙。", category: "justice" },
        { id: 401, english: "An idle brain is the devil's workshop.", chinese: "闲散的头脑是魔鬼的工场。", category: "idleness" },
        { id: 402, english: "An ill workman quarrels with his tools.", chinese: "拙匠常怪工具差。", category: "responsibility" },
        { id: 403, english: "An onion will not produce a rose.", chinese: "洋葱长不出玫瑰。", category: "nature" },
        { id: 404, english: "An ounce of discretion is worth a pound of learning.", chinese: "一分谨慎胜过十分学问。", category: "discretion" },
        { id: 405, english: "An ounce of prevention is worth a pound of cure.", chinese: "预防胜于治疗。", category: "prevention" },
        { id: 406, english: "Anger and haste hinder good counsel.", chinese: "愤怒和急躁阻碍良言。", category: "anger" },
        { id: 407, english: "Anger is a short madness.", chinese: "愤怒是短暂的疯狂。", category: "anger" },
        { id: 408, english: "Anger punishes itself.", chinese: "愤怒自受其害。", category: "anger" },
        { id: 409, english: "Another man's poison.", chinese: "甲之蜜糖，乙之砒霜。", category: "preference" },
        { id: 410, english: "Appearances are deceptive.", chinese: "外表是欺骗性的。", category: "appearance" },
        { id: 411, english: "Appetite comes with eating.", chinese: "越吃越想吃。", category: "appetite" },
        { id: 412, english: "Art is long, life is short.", chinese: "艺术长存，人生苦短。", category: "art" },
        { id: 413, english: "As a man sows, so he shall reap.", chinese: "种瓜得瓜，种豆得豆。", category: "consequence" },
        { id: 414, english: "As drunk as a lord.", chinese: "烂醉如泥。", category: "drunkenness" },
        { id: 415, english: "As fit as a fiddle.", chinese: "非常健康。", category: "health" },
        { id: 416, english: "As like as two peas.", chinese: "一模一样。", category: "similarity" },
        { id: 417, english: "As old as the hills.", chinese: "古老得很。", category: "age" },
        { id: 418, english: "As poor as a church mouse.", chinese: "一贫如洗。", category: "poverty" },
        { id: 419, english: "As sure as eggs is eggs.", chinese: "千真万确。", category: "certainty" },
        { id: 420, english: "As the call, so the echo.", chinese: "怎么喊就怎么回。", category: "consequence" },
        { id: 421, english: "As the old cock crows, the young one learns.", chinese: "老公鸡叫，小公鸡学。", category: "learning" },
        { id: 422, english: "As the tree falls, so shall it lie.", chinese: "树倒在哪里就躺在哪里。", category: "fate" },
        { id: 423, english: "As you make your bed, so you must lie in it.", chinese: "自作自受。", category: "consequence" },
        { id: 424, english: "As you sow, so shall you reap.", chinese: "种瓜得瓜，种豆得豆。", category: "consequence" },
        { id: 425, english: "Ask no questions and hear no lies.", chinese: "不问就不听谎话。", category: "truth" },
        { id: 426, english: "At open doors dogs come in.", chinese: "门开着狗就会进来。", category: "caution" },
        { id: 427, english: "Attack is the best form of defence.", chinese: "进攻是最好的防守。", category: "strategy" },
        { id: 428, english: "Avoid a questioner, for he is also a tattler.", chinese: "避开好问者，因为他也是搬弄是非者。", category: "caution" },
        { id: 429, english: "Bacchus has drowned more men than Neptune.", chinese: "酒神淹死的人比海神多。", category: "drinking" },
        { id: 430, english: "Bad news has wings.", chinese: "坏消息长翅膀。", category: "news" },
        { id: 431, english: "Bad news travels fast.", chinese: "坏事传千里。", category: "news" },
        { id: 432, english: "Barking dogs seldom bite.", chinese: "会叫的狗不咬人。", category: "threat" },
        { id: 433, english: "Be just before you are generous.", chinese: "先公正，再慷慨。", category: "justice" },
        { id: 434, english: "Be slow to promise and quick to perform.", chinese: "慢承诺，快执行。", category: "promise" },
        { id: 435, english: "Be slow in choosing a friend, slower in changing.", chinese: "择友宜慎，弃友更慎。", category: "friendship" },
        { id: 436, english: "Beauty and folly are often companions.", chinese: "美貌与愚蠢常相伴。", category: "beauty" },
        { id: 437, english: "Beauty fades like a flower.", chinese: "美貌如花易凋谢。", category: "beauty" },
        { id: 438, english: "Beauty is but skin deep.", chinese: "美貌只是皮相。", category: "beauty" },
        { id: 439, english: "Beauty is in the eye of the beholder.", chinese: "情人眼里出西施。", category: "beauty" },
        { id: 440, english: "Beauty without virtue is a flower without perfume.", chinese: "无德之美如无香之花。", category: "beauty" },
        { id: 441, english: "Bed is a medicine.", chinese: "睡眠是良药。", category: "health" },
        { id: 442, english: "Bed is the poor man's opera.", chinese: "床是穷人的歌剧。", category: "comfort" },
        { id: 443, english: "Before you make a friend eat a bushel of salt with him.", chinese: "交友前先共吃一蒲式耳盐。", category: "friendship" },
        { id: 444, english: "Beggars should not be choosers.", chinese: "乞丐不能挑肥拣瘦。", category: "choice" },
        { id: 445, english: "Behind bad luck comes good luck.", chinese: "否极泰来。", category: "luck" },
        { id: 446, english: "Believe no tales from the enemy.", chinese: "不要相信敌人的故事。", category: "trust" },
        { id: 447, english: "Believe not all that you see nor half what you hear.", chinese: "眼见未必实，耳听半为虚。", category: "belief" },
        { id: 448, english: "Believe only half of what you see and nothing that you hear.", chinese: "眼见只信一半，耳闻全不可信。", category: "belief" },
        { id: 449, english: "Benefits please like flowers, while they are fresh.", chinese: "恩惠如花，新鲜时才悦人。", category: "gratitude" },
        { id: 450, english: "Best is cheapest.", chinese: "最好的最便宜。", category: "quality" },
        { id: 451, english: "Better a glorious death than a shameful life.", chinese: "宁为玉碎，不为瓦全。", category: "honor" },
        { id: 452, english: "Better a lean peace than a fat victory.", chinese: "宁可和平相处，不要惨胜。", category: "peace" },
        { id: 453, english: "Better a little fire to warm us, than a great one to burn us.", chinese: "小火取暖胜过大火烧身。", category: "moderation" },
        { id: 454, english: "Better a live coward than a dead hero.", chinese: "宁做活懦夫，不做死英雄。", category: "life" },
        { id: 455, english: "Better a neighbor over the wall than a brother over the sea.", chinese: "远亲不如近邻。", category: "neighbor" },
        { id: 456, english: "Better an egg today than a hen tomorrow.", chinese: "今天一个蛋胜过明天一只鸡。", category: "present" },
        { id: 457, english: "Better an open enemy than a false friend.", chinese: "公开的敌人比虚伪的朋友好。", category: "friendship" },
        { id: 458, english: "Better be alone than in bad company.", chinese: "宁可独处，不交恶友。", category: "friendship" },
        { id: 459, english: "Better be born lucky than wise.", chinese: "生来幸运胜过生来聪明。", category: "luck" },
        { id: 460, english: "Better be envied than pitied.", chinese: "被人嫉妒胜过被人怜悯。", category: "envy" },
        { id: 461, english: "Better be poor than wicked.", chinese: "宁可贫穷，不可邪恶。", category: "morality" },
        { id: 462, english: "Better be the head of a dog than the tail of a lion.", chinese: "宁为鸡头，不为凤尾。", category: "position" },
        { id: 463, english: "Better bend than break.", chinese: "宁弯不折。", category: "flexibility" },
        { id: 464, english: "Better deny at once than promise long.", chinese: "与其久许不兑，不如立即拒绝。", category: "promise" },
        { id: 465, english: "Better early than late.", chinese: "宁早勿晚。", category: "time" },
        { id: 466, english: "Better go about than fall into the ditch.", chinese: "宁可绕道，不可掉沟。", category: "caution" },
        { id: 467, english: "Better go home and make a net than stand here and watch the fish.", chinese: "临渊羡鱼，不如退而结网。", category: "action" },
        { id: 468, english: "Better late than never.", chinese: "迟做总比不做好。", category: "time" },
        { id: 469, english: "Better lose a jest than a friend.", chinese: "宁可少开玩笑，不可失去朋友。", category: "friendship" },
        { id: 470, english: "Better one-eyed than stone-blind.", chinese: "独眼胜过全盲。", category: "comparison" },
        { id: 471, english: "Better safe than sorry.", chinese: "小心驶得万年船。", category: "caution" },
        { id: 472, english: "Better the devil you know than the devil you don't.", chinese: "已知的魔鬼胜过未知的魔鬼。", category: "choice" },
        { id: 473, english: "Better to do well than to say well.", chinese: "说得好不如做得好。", category: "action" },
        { id: 474, english: "Better to have loved and lost than never to have loved at all.", chinese: "爱过失去胜过从未爱过。", category: "love" },
        { id: 475, english: "Better to light one candle than to curse the darkness.", chinese: "与其诅咒黑暗，不如点亮蜡烛。", category: "action" },
        { id: 476, english: "Better wear out than rust out.", chinese: "与其锈坏，不如用坏。", category: "activity" },
        { id: 477, english: "Between two stools one falls to the ground.", chinese: "脚踏两凳，终会跌倒。", category: "choice" },
        { id: 478, english: "Beware of a silent dog and still water.", chinese: "当心不叫的狗和静止的水。", category: "caution" },
        { id: 479, english: "Beware of little expenses.", chinese: "当心小开支。", category: "money" },
        { id: 480, english: "Big fish eat little fish.", chinese: "大鱼吃小鱼。", category: "nature" },
        { id: 481, english: "Birds in their little nests agree.", chinese: "同巢之鸟不相争。", category: "harmony" },
        { id: 482, english: "Birds of a feather flock together.", chinese: "物以类聚，人以群分。", category: "friendship" },
        { id: 483, english: "Bitter pills may have blessed effects.", chinese: "良药苦口。", category: "medicine" },
        { id: 484, english: "Black will take no other hue.", chinese: "黑色染不上其他颜色。", category: "nature" },
        { id: 485, english: "Blessed is he who expects nothing, for he shall never be disappointed.", chinese: "无所期待者有福，因其永不失望。", category: "expectation" },
        { id: 486, english: "Blood is thicker than water.", chinese: "血浓于水。", category: "family" },
        { id: 487, english: "Blood will tell.", chinese: "血统会说话。", category: "family" },
        { id: 488, english: "Borrowed garments never fit well.", chinese: "借来的衣服不合身。", category: "borrowing" },
        { id: 489, english: "Boys will be boys.", chinese: "男孩子就是男孩子。", category: "nature" },
        { id: 490, english: "Bread is the staff of life.", chinese: "面包是生命的支柱。", category: "food" },
        { id: 491, english: "Brevity is the soul of wit.", chinese: "简洁是智慧的灵魂。", category: "communication" },
        { id: 492, english: "Build a better mousetrap and the world will beat a path to your door.", chinese: "造出更好的捕鼠器，世界会踏破你的门槛。", category: "innovation" },
        { id: 493, english: "Burn not your house to rid it of the mouse.", chinese: "不要为了赶老鼠而烧房子。", category: "excess" },
        { id: 494, english: "Business before pleasure.", chinese: "先工作，后娱乐。", category: "priority" },
        { id: 495, english: "Business is business.", chinese: "公事公办。", category: "business" },
        { id: 496, english: "By doing nothing we learn to do ill.", chinese: "无所事事，学做坏事。", category: "idleness" },
        { id: 497, english: "By the street of 'Bye and Bye' we arrive at the house of 'Never'.", chinese: "沿着'改天'的路，我们走到'永不'的房子。", category: "procrastination" },
        { id: 498, english: "By their fruits ye shall know them.", chinese: "观其果而知其树。", category: "judgment" },
        { id: 499, english: "By writing you learn to write.", chinese: "写作中学写作。", category: "learning" },
        { id: 500, english: "Calamity is man's true touchstone.", chinese: "灾难是人的试金石。", category: "adversity" },
        { id: 501, english: "Call a spade a spade.", chinese: "直言不讳。", category: "honesty" },
        { id: 502, english: "Call no man happy till he dies.", chinese: "盖棺定论。", category: "happiness" },
        { id: 503, english: "Can the leopard change his spots?", chinese: "豹子能改变它的斑点吗？", category: "nature" },
        { id: 504, english: "Care killed the cat.", chinese: "忧虑害死猫。", category: "worry" },
        { id: 505, english: "Cast no dirt into the well that gives you water.", chinese: "不要往给你水的井里扔脏东西。", category: "gratitude" },
        { id: 506, english: "Cast not the first stone.", chinese: "不要先扔石头。", category: "judgment" },
        { id: 507, english: "Catch as catch can.", chinese: "能抓就抓。", category: "opportunity" },
        { id: 508, english: "Caution is the parent of safety.", chinese: "谨慎是安全之源。", category: "caution" },
        { id: 509, english: "Charity begins at home.", chinese: "仁爱始于家。", category: "charity" },
        { id: 510, english: "Charity covers a multitude of sins.", chinese: "慈善遮盖许多罪过。", category: "charity" },
        { id: 511, english: "Cheats never prosper.", chinese: "骗子永远不会成功。", category: "honesty" },
        { id: 512, english: "Cheerfulness is the best promoter of health.", chinese: "快乐是健康最好的促进者。", category: "health" },
        { id: 513, english: "Children and fools must not play with edged tools.", chinese: "孩子和傻瓜不能玩利器。", category: "caution" },
        { id: 514, english: "Children and fools speak the truth.", chinese: "孩子和傻瓜说真话。", category: "truth" },
        { id: 515, english: "Children are poor men's riches.", chinese: "孩子是穷人的财富。", category: "family" },
        { id: 516, english: "Children should be seen and not heard.", chinese: "孩子应该被看见而不是被听见。", category: "children" },
        { id: 517, english: "Choose a wife by your ear rather than by your eye.", chinese: "选妻用耳不用眼。", category: "marriage" },
        { id: 518, english: "Choose an author as you choose a friend.", chinese: "选作者如选朋友。", category: "choice" },
        { id: 519, english: "Christmas comes but once a year.", chinese: "圣诞节一年只有一次。", category: "occasion" },
        { id: 520, english: "Circumstances alter cases.", chinese: "情况改变事态。", category: "circumstance" },
        { id: 521, english: "Cleanliness is next to godliness.", chinese: "清洁近乎神圣。", category: "cleanliness" },
        { id: 522, english: "Clothes do not make the man.", chinese: "人靠衣装是假象。", category: "appearance" },
        { id: 523, english: "Clothes make the man.", chinese: "人靠衣装。", category: "appearance" },
        { id: 524, english: "Cold hands, warm heart.", chinese: "手冷心热。", category: "personality" },
        { id: 525, english: "Coming events cast their shadows before.", chinese: "未来之事有先兆。", category: "prediction" },
        { id: 526, english: "Command your man and do it yourself.", chinese: "指挥别人，自己动手。", category: "leadership" },
        { id: 527, english: "Comparisons are odious.", chinese: "比较是可憎的。", category: "comparison" },
        { id: 528, english: "Conscience does make cowards of us all.", chinese: "良心使我们成为懦夫。", category: "conscience" },
        { id: 529, english: "Constant dripping wears away the stone.", chinese: "滴水穿石。", category: "persistence" },
        { id: 530, english: "Content is better than riches.", chinese: "知足胜过财富。", category: "contentment" },
        { id: 531, english: "Content is happiness.", chinese: "知足常乐。", category: "happiness" },
        { id: 532, english: "Cooks spoil the broth.", chinese: "厨师太多烧坏汤。", category: "cooperation" },
        { id: 533, english: "Corner a dog in a dead-end street and it will turn and bite.", chinese: "狗急跳墙。", category: "desperation" },
        { id: 534, english: "Courage is the ladder on which all other virtues mount.", chinese: "勇气是所有美德攀登的梯子。", category: "courage" },
        { id: 535, english: "Courtesy is the inseparable companion of virtue.", chinese: "礼貌是美德不可分离的伴侣。", category: "courtesy" },
        { id: 536, english: "Cover your head by day as much as you will, by night as much as you can.", chinese: "白天随意遮头，晚上尽力遮头。", category: "caution" },
        { id: 537, english: "Cowards die many times before their deaths.", chinese: "胆怯者在死前已死过多次。", category: "courage" },
        { id: 538, english: "Credit lost is like a Venice glass broken.", chinese: "失去信用如威尼斯玻璃破碎。", category: "credit" },
        { id: 539, english: "Cross the stream where it is ebbest.", chinese: "在最浅处过河。", category: "strategy" },
        { id: 540, english: "Crows do not pick crow's eyes.", chinese: "乌鸦不啄乌鸦眼。", category: "loyalty" },
        { id: 541, english: "Cruelty is a tyrant that's always attended by fear.", chinese: "残忍是永远伴随着恐惧的暴君。", category: "cruelty" },
        { id: 542, english: "Curses, like chickens, come home to roost.", chinese: "诅咒如鸡，终归回巢。", category: "consequence" },
        { id: 543, english: "Custom is a second nature.", chinese: "习惯是第二天性。", category: "habit" },
        { id: 544, english: "Custom makes all things easy.", chinese: "习惯使一切变得容易。", category: "habit" },
        { id: 545, english: "Cut your coat according to your cloth.", chinese: "量体裁衣。", category: "planning" },
        { id: 546, english: "Dead men tell no tales.", chinese: "死人不会说话。", category: "secrecy" },
        { id: 547, english: "Death is the great leveler.", chinese: "死亡是伟大的平等者。", category: "death" },
        { id: 548, english: "Death pays all debts.", chinese: "一死百了。", category: "death" },
        { id: 549, english: "Death when it comes will have no denial.", chinese: "死神来临时无法拒绝。", category: "death" },
        { id: 550, english: "Debt is the worst poverty.", chinese: "债务是最糟糕的贫穷。", category: "debt" },
        { id: 551, english: "Deeds are fruits, words are but leaves.", chinese: "行动是果实，言语只是叶子。", category: "action" },
        { id: 552, english: "Deeds, not words.", chinese: "看行动，不听言。", category: "action" },
        { id: 553, english: "Delays are dangerous.", chinese: "拖延是危险的。", category: "procrastination" },
        { id: 554, english: "Deliberate slowly, execute promptly.", chinese: "深思熟虑，迅速执行。", category: "decision" },
        { id: 555, english: "Despair gives courage to a coward.", chinese: "绝望给懦夫勇气。", category: "desperation" },
        { id: 556, english: "Desperate diseases must have desperate remedies.", chinese: "重病需下猛药。", category: "solution" },
        { id: 557, english: "Diamond cuts diamond.", chinese: "棋逢对手。", category: "competition" },
        { id: 558, english: "Diligence is the mother of good luck.", chinese: "勤奋是好运之母。", category: "diligence" },
        { id: 559, english: "Dine with a friend but do not do business with him.", chinese: "与友共餐，不与友共事。", category: "business" },
        { id: 560, english: "Disappointment is the nurse of wisdom.", chinese: "失望是智慧之母。", category: "wisdom" },
        { id: 561, english: "Discretion is the better part of valor.", chinese: "谨慎是勇敢的主要部分。", category: "discretion" },
        { id: 562, english: "Diseases enter by the mouth.", chinese: "病从口入。", category: "health" },
        { id: 563, english: "Distance lends enchantment to the view.", chinese: "距离产生美。", category: "distance" },
        { id: 564, english: "Divide and rule.", chinese: "分而治之。", category: "strategy" },
        { id: 565, english: "Do as I say, not as I do.", chinese: "照我说的做，别照我做的做。", category: "hypocrisy" },
        { id: 566, english: "Do as most men do and men will speak well of thee.", chinese: "随大流，人说好。", category: "conformity" },
        { id: 567, english: "Do as you would be done by.", chinese: "己所不欲，勿施于人。", category: "morality" },
        { id: 568, english: "Do business, but be not a slave to it.", chinese: "做生意，但不要成为生意的奴隶。", category: "business" },
        { id: 569, english: "Do not all you can, spend not all you have, believe not all you hear, and tell not all you know.", chinese: "能不做的不做，钱不花光，话不全信，事不全说。", category: "wisdom" },
        { id: 570, english: "Do not cast your pearls before swine.", chinese: "不要对牛弹琴。", category: "wisdom" },
        { id: 571, english: "Do not count your chickens before they are hatched.", chinese: "不要过早乐观。", category: "planning" },
        { id: 572, english: "Do not cry for the moon.", chinese: "不要异想天开。", category: "expectation" },
        { id: 573, english: "Do not cut down the tree that gives you shade.", chinese: "不要砍倒给你遮荫的树。", category: "gratitude" },
        { id: 574, english: "Do not halloo until you are out of the wood.", chinese: "没出森林别欢呼。", category: "caution" },
        { id: 575, english: "Do not have too many irons in the fire.", chinese: "不要同时做太多事。", category: "focus" },
        { id: 576, english: "Do not judge by appearances.", chinese: "不要以貌取人。", category: "judgment" },
        { id: 577, english: "Do not keep a dog and bark yourself.", chinese: "养了狗就不要自己叫。", category: "delegation" },
        { id: 578, english: "Do not let the grass grow on the path of friendship.", chinese: "不要让友谊之路上长草。", category: "friendship" },
        { id: 579, english: "Do not look a gift horse in the mouth.", chinese: "礼物不要挑毛病。", category: "gratitude" },
        { id: 580, english: "Do not put new wine into old bottles.", chinese: "不要把新酒装进旧瓶子里。", category: "change" },
        { id: 581, english: "Do not put the cart before the horse.", chinese: "不要本末倒置。", category: "order" },
        { id: 582, english: "Do not rob Peter to pay Paul.", chinese: "不要拆东墙补西墙。", category: "finance" },
        { id: 583, english: "Do not run with the hare and hunt with the hounds.", chinese: "不要两面讨好。", category: "loyalty" },
        { id: 584, english: "Do not sell the bear's skin before you have caught him.", chinese: "没抓到熊别卖皮。", category: "planning" },
        { id: 585, english: "Do not speak of your happiness to one less fortunate than yourself.", chinese: "不要向比你不幸的人谈论你的幸福。", category: "sensitivity" },
        { id: 586, english: "Do not spur a willing horse.", chinese: "不要鞭打快马。", category: "motivation" },
        { id: 587, english: "Do not wash your dirty linen in public.", chinese: "家丑不可外扬。", category: "privacy" },
        { id: 588, english: "Do right and fear no man.", chinese: "行得正，不怕人。", category: "courage" },
        { id: 589, english: "Do unto others as you would have them do unto you.", chinese: "己所不欲，勿施于人。", category: "morality" },
        { id: 590, english: "Dog does not eat dog.", chinese: "同类不相残。", category: "loyalty" },
        { id: 591, english: "Dogs that put up many hares kill none.", chinese: "赶出许多兔子的狗一只也抓不到。", category: "focus" },
        { id: 592, english: "Doubt is the beginning of wisdom.", chinese: "怀疑是智慧的开端。", category: "wisdom" },
        { id: 593, english: "Draw not your bow till your arrow is fixed.", chinese: "箭未搭好别拉弓。", category: "preparation" },
        { id: 594, english: "Draw water with a sieve.", chinese: "竹篮打水一场空。", category: "futility" },
        { id: 595, english: "Dreams go by contraries.", chinese: "梦与现实相反。", category: "dreams" },
        { id: 596, english: "Drunken days have all their tomorrows.", chinese: "醉酒的日子都有明天。", category: "consequence" },
        { id: 597, english: "Drunkenness reveals what soberness conceals.", chinese: "酒后吐真言。", category: "truth" },
        { id: 598, english: "Dying is as natural as living.", chinese: "死如生一样自然。", category: "death" },
        { id: 599, english: "Eagles fly alone, but sheep flock together.", chinese: "鹰独自飞翔，羊群聚在一起。", category: "individuality" },
        { id: 600, english: "Eagles do not catch flies.", chinese: "老鹰不抓苍蝇。", category: "standards" },
        { id: 601, english: "Early mistakes are the seeds of future trouble.", chinese: "早期错误是未来麻烦的种子。", category: "mistake" },
        { id: 602, english: "Early sow, early mow.", chinese: "早种早收。", category: "timing" },
        { id: 603, english: "Early to bed and early to rise makes a man healthy, wealthy and wise.", chinese: "早睡早起使人健康、富有和聪明。", category: "health" },
        { id: 604, english: "Easier said than done.", chinese: "说起来容易做起来难。", category: "difficulty" },
        { id: 605, english: "East or West, home is best.", chinese: "东好西好，还是家好。", category: "home" },
        { id: 606, english: "Easy come, easy go.", chinese: "来得容易去得快。", category: "money" },
        { id: 607, english: "Eat at pleasure, drink with measure.", chinese: "吃随意，喝适量。", category: "moderation" },
        { id: 608, english: "Eat to live, not live to eat.", chinese: "吃饭是为了活着，活着不是为了吃饭。", category: "life" },
        { id: 609, english: "Education begins a gentleman, conversation completes him.", chinese: "教育开始造就绅士，交谈完成造就。", category: "education" },
        { id: 610, english: "Eggs have no business dancing with stones.", chinese: "鸡蛋不该与石头共舞。", category: "wisdom" },
        { id: 611, english: "Elbow grease gives the best polish.", chinese: "苦干出好活。", category: "work" },
        { id: 612, english: "Empty vessels make the most noise.", chinese: "空桶响声最大。", category: "emptiness" },
        { id: 613, english: "Enough is as good as a feast.", chinese: "够吃就是盛宴。", category: "satisfaction" },
        { id: 614, english: "Envy assails the noblest, the winds howl around the highest peak.", chinese: "嫉妒攻击最高贵者，风在最顶峰呼啸。", category: "envy" },
        { id: 615, english: "Envy never enriched any man.", chinese: "嫉妒从未使人富有。", category: "envy" },
        { id: 616, english: "Envy shoots at others and wounds herself.", chinese: "嫉妒射向他人，伤了自己。", category: "envy" },
        { id: 617, english: "Epigrams succeed where epics fail.", chinese: "史诗失败处，警句能成功。", category: "communication" },
        { id: 618, english: "Equity is a correction of the law where it is defective.", chinese: "衡平法是法律缺陷的修正。", category: "justice" },
        { id: 619, english: "Errors, like straws, upon the surface flow; he who would search for pearls must dive below.", chinese: "错误如稻草浮在水面；寻珠者必须潜入水底。", category: "depth" },
        { id: 620, english: "Even a clock that does not work is right twice a day.", chinese: "不走的钟一天也对两次。", category: "luck" },
        { id: 621, english: "Even a worm will turn.", chinese: "虫子急了也会翻身。", category: "desperation" },
        { id: 622, english: "Even Homer sometimes nods.", chinese: "智者千虑，必有一失。", category: "mistake" },
        { id: 623, english: "Even reckoning makes long friends.", chinese: "账目清楚，友谊长久。", category: "friendship" },
        { id: 624, english: "Every ass loves to hear himself bray.", chinese: "每头驴都爱听自己叫。", category: "vanity" },
        { id: 625, english: "Every barber knows that.", chinese: "理发师都知道。", category: "common" },
        { id: 626, english: "Every bean has its black.", chinese: "每颗豆都有黑点。", category: "imperfection" },
        { id: 627, english: "Every bird likes its own nest.", chinese: "每只鸟都喜欢自己的巢。", category: "home" },
        { id: 628, english: "Every bullet has its billet.", chinese: "每颗子弹都有归宿。", category: "fate" },
        { id: 629, english: "Every cloud has a silver lining.", chinese: "黑暗中总有一线光明。", category: "optimism" },
        { id: 630, english: "Every cock crows on its own dunghill.", chinese: "每只公鸡都在自己的粪堆上啼叫。", category: "territory" },
        { id: 631, english: "Every country has its customs.", chinese: "每个国家都有自己的习俗。", category: "culture" },
        { id: 632, english: "Every day is not Sunday.", chinese: "好日子不会天天有。", category: "reality" },
        { id: 633, english: "Every dog has his day.", chinese: "人人都有得意时。", category: "opportunity" },
        { id: 634, english: "Every dog is a lion at home.", chinese: "每条狗在家都是狮子。", category: "courage" },
        { id: 635, english: "Every dog is valiant at his own door.", chinese: "每条狗在自家门口都勇敢。", category: "courage" },
        { id: 636, english: "Every family has a skeleton in the cupboard.", chinese: "家家有本难念的经。", category: "family" },
        { id: 637, english: "Every flow has its ebb.", chinese: "潮涨必有潮落。", category: "cycles" },
        { id: 638, english: "Every fool can find faults that wise men cannot remedy.", chinese: "傻瓜也能找到智者无法补救的缺点。", category: "criticism" },
        { id: 639, english: "Every for the one and one for all.", chinese: "人人为我，我为人人。", category: "unity" },
        { id: 640, english: "Every heart has its own ache.", chinese: "人人都有伤心事。", category: "sorrow" },
        { id: 641, english: "Every heart knows its own bitterness.", chinese: "每个人的心都知道自己的苦楚。", category: "sorrow" },
        { id: 642, english: "Every horse thinks its own pack heaviest.", chinese: "每匹马都认为自己的驮包最重。", category: "perspective" },
        { id: 643, english: "Every jack has his jill.", chinese: "人各有偶。", category: "love" },
        { id: 644, english: "Every law has a loophole.", chinese: "每条法律都有漏洞。", category: "law" },
        { id: 645, english: "Every light has its shadow.", chinese: "每盏灯都有阴影。", category: "duality" },
        { id: 646, english: "Every little makes a mickle.", chinese: "积少成多。", category: "accumulation" },
        { id: 647, english: "Every man for himself.", chinese: "人人为己。", category: "selfishness" },
        { id: 648, english: "Every man has a fool in his sleeve.", chinese: "人人都有糊涂时。", category: "mistake" },
        { id: 649, english: "Every man has his hobby-horse.", chinese: "人人都有自己的爱好。", category: "hobby" },
        { id: 650, english: "Every man has his price.", chinese: "人人都有价码。", category: "humanity" },
        { id: 651, english: "Every man is a fool sometimes, and none at all times.", chinese: "人人有时是傻瓜，无人总是傻瓜。", category: "wisdom" },
        { id: 652, english: "Every man is the architect of his own fortune.", chinese: "每个人都是自己命运的建筑师。", category: "fate" },
        { id: 653, english: "Every man is the master of his own fortune.", chinese: "每个人都是自己命运的主人。", category: "fate" },
        { id: 654, english: "Every man thinks his own geese swans.", chinese: "每个人都认为自己的鹅是天鹅。", category: "perspective" },
        { id: 655, english: "Every man to his trade.", chinese: "各人干各人的行当。", category: "specialization" },
        { id: 656, english: "Every man's house is his castle.", chinese: "每个人的家都是他的城堡。", category: "privacy" },
        { id: 657, english: "Every medal has two sides.", chinese: "每个奖章都有两面。", category: "duality" },
        { id: 658, english: "Every medal has its reverse.", chinese: "每个奖章都有反面。", category: "duality" },
        { id: 659, english: "Every miller draws water to his own mill.", chinese: "每个磨坊主都往自己的磨坊引水。", category: "selfishness" },
        { id: 660, english: "Every mother's child is handsome.", chinese: "孩子都是自己的好。", category: "family" },
        { id: 661, english: "Every one's faults are not written in their foreheads.", chinese: "每个人的缺点都没写在额头上。", category: "deception" },
        { id: 662, english: "Every path has a puddle.", chinese: "每条路都有水坑。", category: "difficulty" },
        { id: 663, english: "Every potter praises his own pot.", chinese: "卖瓜的说瓜甜。", category: "self-promotion" },
        { id: 664, english: "Every promise is a debt.", chinese: "每个承诺都是债务。", category: "promise" },
        { id: 665, english: "Every question has its answer.", chinese: "每个问题都有答案。", category: "solution" },
        { id: 666, english: "Every road leads to Rome.", chinese: "条条大路通罗马。", category: "method" },
        { id: 667, english: "Every rose has its thorn.", chinese: "每朵玫瑰都有刺。", category: "reality" },
        { id: 668, english: "Every rule has its exception.", chinese: "每条规则都有例外。", category: "exception" },
        { id: 669, english: "Every shoe fits not every foot.", chinese: "不是每只鞋都适合每只脚。", category: "suitability" },
        { id: 670, english: "Every stick has two ends.", chinese: "每根棍子都有两头。", category: "duality" },
        { id: 671, english: "Every tide has its ebb.", chinese: "潮涨必有潮落。", category: "cycles" },
        { id: 672, english: "Every tree is known by its fruit.", chinese: "观其果而知其树。", category: "judgment" },
        { id: 673, english: "Every white has its black, and every sweet its sour.", chinese: "白中有黑，甜中有酸。", category: "duality" },
        { id: 674, english: "Every why has a wherefore.", chinese: "凡事皆有因。", category: "reason" },
        { id: 675, english: "Every wind is ill to a broken ship.", chinese: "破船怕风浪。", category: "vulnerability" },
        { id: 676, english: "Every wise man dreadeth his enemy.", chinese: "智者敬畏敌人。", category: "caution" },
        { id: 677, english: "Every word is not without its effect.", chinese: "每句话都有影响。", category: "communication" },
        { id: 678, english: "Every year of a man's life is a step towards death.", chinese: "人生的每一年都是走向死亡的一步。", category: "life" },
        { id: 679, english: "Evil communications corrupt good manners.", chinese: "近朱者赤，近墨者黑。", category: "influence" },
        { id: 680, english: "Evil gotten, evil spent.", chinese: "不义之财，挥霍而尽。", category: "money" },
        { id: 681, english: "Example is better than precept.", chinese: "身教重于言教。", category: "teaching" },
        { id: 682, english: "Exchange is no robbery.", chinese: "交换不是抢劫。", category: "trade" },
        { id: 683, english: "Expectation is better than realization.", chinese: "期待胜于实现。", category: "expectation" },
        { id: 684, english: "Experience is a dear teacher, but fools will learn at no other.", chinese: "经验是昂贵的老师，但傻瓜不愿向别人学习。", category: "learning" },
        { id: 685, english: "Experience is the best teacher.", chinese: "经验是最好的老师。", category: "learning" },
        { id: 686, english: "Experience is the father of wisdom.", chinese: "经验是智慧之父。", category: "wisdom" },
        { id: 687, english: "Experience is the mistress of fools.", chinese: "经验是傻瓜的老师。", category: "learning" },
        { id: 688, english: "Experience keeps a dear school, but fools learn in no other.", chinese: "经验学校学费高，傻瓜别处学不到。", category: "learning" },
        { id: 689, english: "Experience keeps no school, she teaches her pupils singly.", chinese: "经验不开学校，单独教导学生。", category: "learning" },
        { id: 690, english: "Experience without learning is better than learning without experience.", chinese: "有经验无学问胜过有学问无经验。", category: "learning" },
        { id: 691, english: "Extremes are dangerous.", chinese: "极端是危险的。", category: "moderation" },
        { id: 692, english: "Extremes meet.", chinese: "两极相通。", category: "duality" },
        { id: 693, english: "Facts are facts.", chinese: "事实就是事实。", category: "truth" },
        { id: 694, english: "Facts are stubborn things.", chinese: "事实是顽固的。", category: "truth" },
        { id: 695, english: "Faint heart never won fair lady.", chinese: "胆小鬼娶不到美娇娘。", category: "courage" },
        { id: 696, english: "Fair and softly goes far.", chinese: "温柔走得远。", category: "gentleness" },
        { id: 697, english: "Fair faces need no paint.", chinese: "美貌不需要化妆。", category: "beauty" },
        { id: 698, english: "Fair words butter no parsnips.", chinese: "好话不能当饭吃。", category: "words" },
        { id: 699, english: "Fair words fill not the belly.", chinese: "好话填不饱肚子。", category: "words" },
        { id: 700, english: "Faith will move mountains.", chinese: "信念能移山。", category: "faith" }
    ]
};
